<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.cloud.erp</groupId>
        <artifactId>erp-server</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <groupId>com.erp.server</groupId>
    <artifactId>erp-server-dmp</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>erp-server-dmp</name>
    <description>数据中台系统</description>
    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb</artifactId>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <!--公共服务-->
        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-model-plm</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>


        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-rpc-sys</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-rpc-workflow</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>com.alibaba</groupId>-->
<!--            <artifactId>fastjson</artifactId>-->
<!--            <version>1.2.78</version>-->
<!--        </dependency>-->

        <dependency>
            <groupId>com.k3cloud</groupId>
            <artifactId>k3cloud-webapi-sdk</artifactId>
            <version>8.0.3</version>
        </dependency>

        <dependency>
            <groupId>com.k3cloud</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.0</version>
        </dependency>
        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-model-dmp</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-rpc-plm</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-rpc-dmp</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

        <!--openfeign-->
        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-rpc-plm</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.xuxueli</groupId>
            <artifactId>xxl-job-core</artifactId>
            <version>2.3.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>${alibaba.druid.verison}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
            <version>${rocketmq.verion}</version>
            <exclusions>
                <exclusion>
                    <artifactId>fastjson</artifactId>
                    <groupId>com.alibaba</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <!--      optional 表示依赖是否向下传递 true表示不向下传递  默认值是false向下传递      -->
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-common-message</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.83</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>dev</id>
            <properties>
                <repository.id>snapshot-test</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-test/</repository.url>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>test</id>
            <properties>
                <repository.id>snapshot-test</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-test/</repository.url>
            </properties>
        </profile>
        <profile>
            <id>uat</id>
            <properties>
                <repository.id>snapshot-prod</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-prod/</repository.url>
            </properties>
        </profile>
        <profile>
            <id>prod</id>
            <properties>
                <repository.id>snapshot-prod</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-prod/</repository.url>
            </properties>
        </profile>
    </profiles>
    <distributionManagement>
        <snapshotRepository>
            <id>${repository.id}</id>
            <url>${repository.url}</url>
        </snapshotRepository>

    </distributionManagement>
    <repositories>
        <repository>
            <id>nexus</id>
            <name>Internal Maven Server</name>
            <url>http://172.16.100.11:8089/repository/maven-public/</url>
        </repository>
    </repositories>

    <build>
        <finalName>${project.name}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
