package com.erp.model.mrp.enums;

import com.common.core.constant.EnumMessage;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum CfgRuleSuggestedAmountNodeEnum implements EnumMessage {


    SUGGESTED_STOCK_UP("SUGGESTED_STOCK_UP","建议备货"),
    SUGGESTED_PURCHASE("SUGGESTED_PURCHASE","建议采购"),
    SUGGESTED_TIME("SUGGESTED_TIME","建议时间"),
    SUGGESTED_SHIPPING_QTY("SUGGESTED_SHIPPING_QTY","建议发货量：(本地直发FBA)"),
    SUGGESTED_PURCHASE_QTY("SUGGESTED_PURCHASE_QTY","建议采购量：(本地直发FBA)"),

    TIME_FRAME("TIME_FRAME","建议时间范围"),
    DELIVERY_VOLUME_AGING("DELIVERY_VOLUME_AGING","建议发货量-时效"),
    DELIVERY_VOLUME_INVENTORY("DELIVERY_VOLUME_INVENTORY","建议发货量-库存"),
    PURCHASE_VOLUME_AGING("PURCHASE_VOLUME_AGING","建议采购量-时效"),
    DELIVERY_DELIVERY_DAYS("DELIVERY_DELIVERY_DAYS","本地发FBA时效"),
    DELIVERY_IN_STOCK_DAYS("DELIVERY_IN_STOCK_DAYS","FBA入库时间"),
    DELIVERY_LOGISTICS_CYCLE_DAYS("DELIVERY_LOGISTICS_CYCLE_DAYS","本地仓发货频率"),
    DELIVERY_SAFE_DAYS("DELIVERY_SAFE_DAYS","FBA安全天数"),
    DELIVERY_FBA_USABLE_QTY("DELIVERY_FBA_USABLE_QTY","FBA可用"),
    DELIVERY_FBA_IN_TRANSIT_QTY("DELIVERY_FBA_IN_TRANSIT_QTY","FBA在途"),
    DELIVERY_FBA_PLAN_DELIVERY_QTY("DELIVERY_FBA_PLAN_DELIVERY_QTY","FBA预计发货"),
    DELIVERY_OVERSEAS_USABLE_QTY("DELIVERY_OVERSEAS_USABLE_QTY","海外仓可用"),
    DELIVERY_OVERSEAS_IN_TRANSIT_QTY("DELIVERY_OVERSEAS_IN_TRANSIT_QTY","海外仓在途"),
    DELIVERY_OVERSEAS_PLAN_DELIVERY_QTY("DELIVERY_OVERSEAS_PLAN_DELIVERY_QTY","海外仓预计发货"),

    PURCHASE_PURCHASE_APPROVE_DAYS("PURCHASE_PURCHASE_APPROVE_DAYS","审批时长"),
    PURCHASE_PRODUCTION_DAYS("PURCHASE_PRODUCTION_DAYS","生产周期"),
    PURCHASE_SUPPLIER_DELIVERY_DAYS("PURCHASE_SUPPLIER_DELIVERY_DAYS","供应商发货时长"),
    PURCHASE_QC_DAYS("PURCHASE_QC_DAYS","质检入库天数"),
    PURCHASE_PURCHASE_CYCLE_DAYS("PURCHASE_PURCHASE_CYCLE_DAYS","采购频率"),
    PURCHASE_DELIVERY_DAYS("PURCHASE_DELIVERY_DAYS","本地发FBA时效"),
    PURCHASE_IN_STOCK_DAYS("PURCHASE_IN_STOCK_DAYS","FBA入库时间"),
    PURCHASE_LOGISTICS_CYCLE_DAYS("PURCHASE_LOGISTICS_CYCLE_DAYS","本地仓发货频率"),
    PURCHASE_SAFE_DAYS("PURCHASE_SAFE_DAYS","FBA安全天数"),
    PURCHASE_FBA_USABLE_QTY("PURCHASE_FBA_USABLE_QTY","FBA可用"),
    PURCHASE_FBA_IN_TRANSIT_QTY("PURCHASE_FBA_IN_TRANSIT_QTY","FBA在途"),
    PURCHASE_FBA_PLAN_DELIVERY_QTY("PURCHASE_FBA_PLAN_DELIVERY_QTY","FBA预计发货"),
    PURCHASE_OVERSEAS_USABLE_QTY("PURCHASE_OVERSEAS_USABLE_QTY","海外仓可用"),
    PURCHASE_OVERSEAS_IN_TRANSIT_QTY("PURCHASE_OVERSEAS_IN_TRANSIT_QTY","海外仓在途"),
    PURCHASE_OVERSEAS_PLAN_DELIVERY_QTY("PURCHASE_OVERSEAS_PLAN_DELIVERY_QTY","海外仓预计发货"),
    PURCHASE_LOCAL_USABLE_QTY("PURCHASE_LOCAL_USABLE_QTY","本地仓可用"),
    PURCHASE_LOCAL_IN_TRANSIT_QTY("PURCHASE_LOCAL_IN_TRANSIT_QTY","本地在途"),
    PURCHASE_LOCAL_PLAN_PURCHASE_QTY("PURCHASE_LOCAL_PLAN_PURCHASE_QTY","预计采购"),
    ;

    private final String code;

    private final String name;

    @Override
    public String getCode() {
        return code;
    }

    @Override
    public String getName() {
        return name;
    }
}
