/*
 * Selling Partner API for Catalog Items
 * The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.erp.server.dmp.amz;

import cn.hutool.json.JSONUtil;
import com.common.core.exception.ServiceException;
import com.erp.model.dmp.dto.AmazonShopInfoDTO;
import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.*;
import com.erp.sdk.oms.amz.spapi.api.CatalogApi;
import com.erp.sdk.oms.amz.spapi.api.CatalogV0Api;
import com.erp.sdk.oms.amz.spapi.client.ApiException;
import com.erp.sdk.oms.amz.spapi.enums.AmazonMarketplaceEnum;
import com.erp.sdk.oms.amz.spapi.model.catalogitems.GetCatalogItemResponse;
import com.erp.sdk.oms.amz.spapi.model.catalogitems.ListCatalogCategoriesResponse;
import com.erp.sdk.oms.amz.spapi.model.catalogitems.ListCatalogItemsResponse;
import com.erp.sdk.oms.amz.spapi.utils.AmazonSpApiConfigUtils;
import com.erp.server.dmp.ErpServerDmpApplication;
import com.erp.server.dmp.service.CfgAppClientService;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Profile;
import org.springframework.test.context.junit4.SpringRunner;

import javax.annotation.Resource;
import java.util.Arrays;
import java.util.List;


/**
 * API tests for CatalogV0Api
 */
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerDmpApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@Profile("dev")
public class CatalogV0ApiTest {

    @Resource
    private CfgAppClientService cfgAppClientService;

    public CatalogV0Api amazonAuthorizationGrant(AmazonMarketplaceEnum marketplaceEnum) {
//        AWSAuthenticationCredentials awsAuthenticationCredentials = AmazonSpApiConfigUtils.buildAWSAuthenticationCredentials(marketplaceEnum.getEndpointsEnum());
//        LWAAuthorizationCredentials lwaAuthorizationCredentials = AmazonSpApiConfigUtils.buildLWAAuthorizationCredentials();
//        AWSAuthenticationCredentialsProvider awsAuthenticationCredentialsProvider = AmazonSpApiConfigUtils.buildAWSAuthenticationCredentialsProvider();
//        CatalogV0Api catalogApi = new CatalogV0Api.Builder()
//                .awsAuthenticationCredentials(awsAuthenticationCredentials)
//                .lwaAuthorizationCredentials(lwaAuthorizationCredentials)
//                .awsAuthenticationCredentialsProvider(awsAuthenticationCredentialsProvider)
//                //注意，这里的endpoint分北美，欧洲，远东三个地域，每个区域的链接是不一样的
//                //北美，https://sellingpartnerapi-na.amazon.com
//                //欧洲，https://sellingpartnerapi-eu.amazon.com
//                //远东，https://sellingpartnerapi-fe.amazon.com
//                .endpoint(marketplaceEnum.getEndpointsEnum().getEndpointsByProfile())
//                .build();
//        if (null == catalogApi) {
//            throw new RuntimeException("授权失败，未获取到API实例的话抛出异常，进行重试");
//        }
        return null;
    }

    /**
     * Effective September 30, 2022, the &#x60;getCatalogItem&#x60; operation will no longer be available in the Selling Partner API for Catalog Items v0. This operation is available in the latest version of the [Selling Partner API for Catalog Items v2022-04-01](doc:catalog-items-api-v2022-04-01-reference). Integrations that rely on this operation should migrate to the latest version to avoid service disruption.  _Note:_ The [&#x60;listCatalogCategories&#x60;](#get-catalogv0categories) operation is not being deprecated and you can continue to make calls to it.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCatalogItemTest() throws ApiException {
        String marketplaceId = "A1AM78C64UM0Y8";
        String asin = null;
        CatalogV0Api api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US);
        GetCatalogItemResponse response = api.getCatalogItem(marketplaceId, asin);
        System.out.println("CatalogItemV0");
        System.out.println(JSONUtil.toJsonStr(response));
        // TODO: test validations
    }

    /**
     * Returns the parent categories to which an item belongs, based on the specified ASIN or SellerSKU.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 2 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listCatalogCategoriesTest() throws ApiException {
        String marketplaceId = null;
        String ASIN = null;
        String sellerSKU = null;
        CatalogV0Api api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US);
        ListCatalogCategoriesResponse response = api.listCatalogCategories(marketplaceId, ASIN, sellerSKU);
        // TODO: test validations
    }

    /**
     * Effective September 30, 2022, the &#x60;listCatalogItems&#x60; operation will no longer be available in the Selling Partner API for Catalog Items v0. As an alternative, &#x60;searchCatalogItems&#x60; is available in the latest version of the [Selling Partner API for Catalog Items v2022-04-01](doc:catalog-items-api-v2022-04-01-reference). Integrations that rely on the &#x60;listCatalogItems&#x60; operation should migrate to the &#x60;searchCatalogItems&#x60;operation to avoid service disruption.  _Note:_ The [&#x60;listCatalogCategories&#x60;](#get-catalogv0categories) operation is not being deprecated and you can continue to make calls to it.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listCatalogItemsTest() throws ApiException {
        String marketplaceId = AmazonMarketplaceEnum.US.getMarketplaceId();
        String query = null;
        String queryContextId = null;
        String sellerSKU = null;
        String UPC = null;
        String EAN = null;
        String ISBN = null;
        String JAN = null;
        CatalogV0Api api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US);
        ListCatalogItemsResponse response = api.listCatalogItems(marketplaceId, query, queryContextId, sellerSKU, UPC, EAN, ISBN, JAN);
        // TODO: test validations
        System.out.println("listCatalogItemsTest");
        System.out.println(JSONUtil.toJsonStr(response));
    }
}