/*
 * Selling Partner API for Catalog Items
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * OpenAPI spec version: 2022-04-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.erp.server.dmp.amz;

import cn.hutool.json.JSONUtil;
import com.common.core.exception.ServiceException;
import com.erp.model.dmp.dto.AmazonShopInfoDTO;
import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.RateLimitConfiguration;
import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.RateLimitConfigurationOnRequests;
import com.erp.sdk.oms.amz.spapi.api.CatalogApi;
import com.erp.sdk.oms.amz.spapi.client.ApiException;
import com.erp.sdk.oms.amz.spapi.enums.AmazonMarketplaceEnum;
import com.erp.sdk.oms.amz.spapi.model.catalogitems.Item;
import com.erp.sdk.oms.amz.spapi.model.catalogitems.ItemSearchResults;
import com.erp.server.dmp.ErpServerDmpApplication;
import com.erp.server.dmp.service.CfgAppClientService;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Profile;
import org.springframework.test.context.junit4.SpringRunner;

import javax.annotation.Resource;
import java.util.Arrays;
import java.util.List;

/**
 * API tests for CatalogApi
 */
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerDmpApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@Profile("dev")
public class CatalogApiTest {

    @Resource
    private CfgAppClientService cfgAppClientService;

    /**
     * 
     *
     * Retrieves details for an item in the Amazon catalog.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 5 | 5 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may observe higher rate and burst values than those shown here. For more information, refer to the [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCatalogItemTest() throws ApiException {
        String asin = "B08LZ58T2L";
        List<String> marketplaceIds = Arrays.asList("A1AM78C64UM0Y8");
//        String asin = "B07N4M94X4";
//        List<String> marketplaceIds = Arrays.asList("ATVPDKIKX0DER");
        List<String> includedData = Arrays.asList("attributes","dimensions","identifiers","images","productTypes","salesRanks","summaries","relationships");
//        List<String> includedData = Arrays.asList("attributes","dimensions","identifiers","images","productTypes","salesRanks","summaries","relationships","vendorDetails");
//        List<String> includedData = null;
        String locale = null;
//        CatalogApi api = CatalogApi.initApi(AmazonMarketplaceEnum.US.getEndpointsEnum(), false);
//        Item response = api.getCatalogItem(asin, marketplaceIds, includedData, locale);
//        System.out.println("Catalog信息");
//        System.out.println(JSONUtil.toJsonStr(response));
    }
    
    /**
     * 
     *
     * Search for and return a list of Amazon catalog items and associated information either by identifier or by keywords.  **Usage Plans:**  | Rate (requests per second) | Burst | | ---- | ---- | | 5 | 5 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may observe higher rate and burst values than those shown here. For more information, refer to the [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchCatalogItemsTest() throws ApiException {
        // 2350+2351
        // 788185949481
        //B08TBLHVTP
//        List<String> marketplaceIds = Arrays.asList("ATVPDKIKX0DER");
//        List<String> identifiers = Arrays.asList("1963-US7");
//        String identifiersType = "SKU";
        AmazonMarketplaceEnum marketplaceEnum = AmazonMarketplaceEnum.JP;
        String shopId = "1735516266715680769";
        List<String> marketplaceIds = Arrays.asList(marketplaceEnum.getMarketplaceId());
        List<String> identifiers = Arrays.asList("788185949481");
        String identifiersType = "JAN";
        List<String> includedData = Arrays.asList("attributes","dimensions","identifiers","images","productTypes","salesRanks","summaries","relationships");;
        String locale = null;
        String sellerId = null;
        List<String> keywords = null;
        List<String> brandNames = null;
        List<String> classificationIds = null;
        Integer pageSize = null;
        String pageToken = null;
        String keywordsLocale = null;
        // 获取店铺授权信息
        AmazonShopInfoDTO shopInfoDTO = cfgAppClientService.cacheAndFindShopAuth(shopId);
        if (null == shopInfoDTO) {
            throw new ServiceException("未找到店铺授权:" + shopId);
        }

        RateLimitConfiguration rateLimitConfig = RateLimitConfigurationOnRequests.builder()
                .rateLimitPermit(0.5)
                .waitTimeOutInMilliSeconds(10000L)
                .build();
        //查询商品详情
        CatalogApi api =  CatalogApi.init(marketplaceEnum.getEndpointsEnum(), shopInfoDTO, false,  rateLimitConfig);
//        CatalogApi api = CatalogApi.initApi(AmazonMarketplaceEnum.US.getEndpointsEnum(), true);
        ItemSearchResults response = api.searchCatalogItems(marketplaceIds, identifiers, identifiersType, includedData, locale, sellerId, keywords, brandNames, classificationIds, pageSize, pageToken, keywordsLocale);
        System.out.println("CatalogItems信息");
        System.out.println(JSONUtil.toJsonStr(response));
        // TODO: test validations
    }
    
}
