/*
 * Selling Partner API for Fulfillment Inbound
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.erp.server.dmp.amz;


import cn.hutool.json.JSONUtil;
import com.common.core.exception.ServiceException;
import com.common.core.utils.date.DateUtil;
import com.erp.model.dmp.dto.AmazonShopInfoDTO;
import com.erp.sdk.oms.amz.spapi.api.FbaInboundApi;
import com.erp.sdk.oms.amz.spapi.client.ApiException;
import com.erp.sdk.oms.amz.spapi.client.JSON;
import com.erp.sdk.oms.amz.spapi.enums.AmazonFbaShipmentStatusEnum;
import com.erp.sdk.oms.amz.spapi.enums.AmazonMarketplaceEnum;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentinbound.*;
import com.erp.sdk.oms.amz.spapi.utils.AmazonSpApiInitUtils;
import com.erp.server.dmp.ErpServerDmpApplication;
import com.erp.server.dmp.service.CfgAppClientService;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Profile;
import org.springframework.test.context.junit4.SpringRunner;

import javax.annotation.Resource;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

/**
 * API tests for FbaInboundApi
 */
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerDmpApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@Profile("dev")
public class FbaInboundApiHistoryTest {
    @Resource
    private CfgAppClientService cfgAppClientService;



    /**
     * Returns a list of items in a specified inbound shipment, or a list of items that were updated within a specified time frame.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getShipmentItemsTest() throws ApiException {
        String shopId = "1735479610549735425";
        // 获取店铺授权信息
        AmazonShopInfoDTO shopInfoDTO = cfgAppClientService.cacheAndFindShopAuth(shopId);
        if (null == shopInfoDTO) {
            throw new ServiceException("未找到店铺授权:" + shopId);
        }
//        String queryType = "SHIPMENT";
        String queryType = "DATE_RANGE";
        AmazonMarketplaceEnum marketplaceEnum = AmazonMarketplaceEnum.getByCountryCode(shopInfoDTO.getDictCountryCode());
        String marketplaceId = marketplaceEnum.getMarketplaceId();
//        String lastUpdatedAfter = null;
//        String lastUpdatedBefore = null;
//        String nextToken = "NextToken";
//        LocalDateTime startTime = LocalDateTime.of(2023, 10, 31, 0, 0, 0);
//        LocalDateTime now = LocalDateTime.now();
//        String lastUpdatedAfter = DateUtil.plus8SameUtcOffset(startTime).toString();
//        String lastUpdatedBefore = DateUtil.plus8SameUtcOffset(now).toString();
        String lastUpdatedAfter = "2024-02-02T00:00:00.000Z";
        String lastUpdatedBefore = "2024-02-05T00:00:00.000Z";

        String nextToken = null;
        FbaInboundApi api = AmazonSpApiInitUtils.create(FbaInboundApi.class, shopInfoDTO ,false);
        GetShipmentItemsResponse response = api.getShipmentItems(queryType, marketplaceId, lastUpdatedAfter, lastUpdatedBefore, nextToken);
        System.out.println("货件详情:");
        System.out.println(JSONUtil.toJsonStr(response));
    }

    /**
     * Returns a list of items in a specified inbound shipment.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getShipmentItemsByShipmentIdTest() throws ApiException {
        for (int i = 0; i < 3; i++) {

        }
        String shipmentId = "FBA17DZ9039Z";
        String marketplaceId = AmazonMarketplaceEnum.US.getMarketplaceId();
        FbaInboundApi api = null;
        GetShipmentItemsResponse response = api.getShipmentItemsByShipmentId(shipmentId, marketplaceId);
        System.out.println("通过shipmentId查询货件详情");
        System.out.println(JSONUtil.toJsonStr(response));
        // TODO: test validations
    }

    /**
     * Returns a list of inbound shipments based on criteria that you specify.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getShipmentsTest() throws ApiException {
        String shopId = "1735588142481674247";
        // 获取店铺授权信息
        AmazonShopInfoDTO shopInfoDTO = cfgAppClientService.cacheAndFindShopAuth(shopId);
        if (null == shopInfoDTO) {
            throw new ServiceException("未找到店铺授权:" + shopId);
        }
        AmazonMarketplaceEnum marketplaceEnum = AmazonMarketplaceEnum.getByCountryCode(shopInfoDTO.getDictCountryCode());
        FbaInboundApi api = AmazonSpApiInitUtils.create(FbaInboundApi.class, shopInfoDTO ,false);
        String queryType = "SHIPMENT";
//        String queryType = "DATE_RANGE";
//        String queryType = AmazonFbaQueryTypeEnum.NEXT_TOKEN.getCode();
        String marketplaceId = marketplaceEnum.getMarketplaceId();
        List<String> shipmentStatusList = null;
        List<String> shipmentIdList = Arrays.asList("FBA15HMCLVH2");
//        LocalDateTime startTime = LocalDateTime.of(2023, 11, 1, 0, 0, 0);
//        LocalDateTime now = LocalDateTime.now();
//        String lastUpdatedAfter = DateUtil.plus8SameUtcOffset(startTime).toString();
//        String lastUpdatedBefore = DateUtil.plus8SameUtcOffset(now).toString();
        String lastUpdatedAfter = null;
        String lastUpdatedBefore = null;
        String nextToken = null;
//        String nextToken = "AAAAAAAAAAC+Qqz8LL08LOj0DOtm6jc55wEAAAAAAACYz902f0AjXDETsiNeDKlnpPMySCR107y4nGltTWt+rnw87weJ+9zv9CLmPcRf4hiSSCfF52xQLGA/hq1Ab24WKhbU5aFl9/uDAn0QTs48jZe8s+FIX6N5ECslLH8+LPS2h0Xh2/YshZ5S1ZvpWkU/cnZ39ffkjZmgE1MoriD3v1nqQ6JfxzbJSzFQNo9JTFSSBSqStod7npOeaWnlDpR6Rsd+X3YGi9uj8wW8qENbl3MiK4gJh+qHZA6V2mtHJnv2A9571TphAls3oPBev5ubLRJPUhGyRH9V2g16Rzzi84eA7iQ/wn6kLnRKIstfIHvgN5aQEo/s+l0r6Az7IYs2jSjkjQIQ6c5OGS5tQoxVHGAJm3gP4ZxqP4vsZJBZbhizhpA8qEwtfHs0c8fqxUtHxqO0/bcEtBdkUSBR9eQF0twYQLaQyvAI5IRlSEw/Ecw0eSuMg7Ql6+ShhjVKP55JikOhl7LvNy9jtaTkjFvP28t2xeV0ujvUyVOsrzfjmiHDGDXhxq9gjuWTiSC68QI28+heqH5bsYHgyzdQa/zoe0MazcKIi62rpNWyF95kBh0zzBTSSLopvqCiezOpLjiyKqVKEOT0TsDZ715Zbe9JxcOnutb1PBxJFxBfoMjtk3ZmTJhGbNqa";
        GetShipmentsResponse response = api.getShipments(queryType, marketplaceId, shipmentStatusList, shipmentIdList, lastUpdatedAfter, lastUpdatedBefore, nextToken);
        System.out.println("货件信息");
        System.out.println(JSON.toJsonStr(response));
        // TODO: test validations
    }


    /**
     * Returns a list of inbound shipments based on criteria that you specify.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllShipmentsTest() throws ApiException {
        FbaInboundApi api = null;
        String queryType = "DATE_RANGE";
        String marketplaceId = "ATVPDKIKX0DER";
        List<String> shipmentStatusList = AmazonFbaShipmentStatusEnum.getAllStatus();
        List<String> shipmentIdList = null;
        LocalDateTime startTime = LocalDateTime.of(2023, 11, 13, 0, 0, 0);
        LocalDateTime now = LocalDateTime.now();
        String lastUpdatedAfter = DateUtil.plus8SameUtcOffset(startTime).toString();
        String lastUpdatedBefore = DateUtil.plus8SameUtcOffset(now).toString();
        String nextToken = null;
        InboundShipmentList response = api.getAllShipments(queryType, marketplaceId, shipmentStatusList, shipmentIdList, lastUpdatedAfter, lastUpdatedBefore, nextToken);
        System.out.println("所有货件信息");
        System.out.println(JSON.toJsonStr(response));
        // TODO: test validations
    }

}
