/*
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * OpenAPI spec version: 2020-07-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.erp.server.dmp.amz;

import cn.hutool.json.JSONObject;
import cn.hutool.json.JSONUtil;
import com.erp.model.dmp.dto.AmazonShopInfoDTO;
import com.erp.sdk.oms.amz.spapi.api.FbaInboundApi;
import com.erp.sdk.oms.amz.spapi.api.FbaOutboundApi;
import com.erp.sdk.oms.amz.spapi.client.ApiException;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.CancelFulfillmentOrderResponse;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.CreateFulfillmentOrderRequest;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.CreateFulfillmentOrderResponse;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.CreateFulfillmentReturnRequest;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.CreateFulfillmentReturnResponse;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.GetDeliveryOffersRequest;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.GetDeliveryOffersResponse;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.GetFeatureInventoryResponse;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.GetFeatureSkuResponse;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.GetFeaturesResponse;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.GetFulfillmentOrderResponse;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.GetFulfillmentPreviewRequest;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.GetFulfillmentPreviewResponse;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.GetPackageTrackingDetailsResponse;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.ListAllFulfillmentOrdersResponse;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.ListReturnReasonCodesResponse;

import java.time.OffsetDateTime;

import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.SubmitFulfillmentOrderStatusUpdateRequest;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.SubmitFulfillmentOrderStatusUpdateResponse;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.UpdateFulfillmentOrderRequest;
import com.erp.sdk.oms.amz.spapi.model.fulfillmentoutbound.UpdateFulfillmentOrderResponse;
import com.erp.sdk.oms.amz.spapi.utils.AmazonSpApiInitUtils;
import com.erp.server.dmp.ErpServerDmpApplication;
import com.erp.server.dmp.service.CfgAppClientService;
import lombok.extern.slf4j.Slf4j;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.LWAException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.cloud.client.discovery.DiscoveryClient;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
import org.springframework.cloud.openfeign.EnableFeignClients;
import org.springframework.context.annotation.Profile;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.junit4.SpringRunner;

import javax.annotation.Resource;

/**
 * API tests for FbaOutboundApi
 */
@Slf4j
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerDmpApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@ActiveProfiles("dev")
public class FbaOutboundApiTest {

    @Resource
    private CfgAppClientService cfgAppClientService;
    @Resource
    private DiscoveryClient discoveryClient;

    @BeforeEach
    void waitNacos() throws InterruptedException {
        while (discoveryClient.getInstances("erp-oms").isEmpty()) {
            System.out.println("等待 Nacos 注册实例");
            Thread.sleep(100);
        }
    }


    private final FbaOutboundApi api = new FbaOutboundApi(null);

    /**
     *
     *
     * Requests that Amazon stop attempting to fulfill the fulfillment order indicated by the specified order identifier.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws ApiException if the Api call fails
     * @throws LWAException If calls to fetch LWA access token fails
     */
    @Test
    public void cancelFulfillmentOrderTest() throws ApiException, LWAException {
        String sellerFulfillmentOrderId = null;
        CancelFulfillmentOrderResponse response = api.cancelFulfillmentOrder(sellerFulfillmentOrderId);

        // TODO: test validations
    }

    /**
     *
     *
     * Requests that Amazon ship items from the seller&#x27;s inventory in Amazon&#x27;s fulfillment network to a destination address.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api)
     *
     * @throws ApiException if the Api call fails
     * @throws LWAException If calls to fetch LWA access token fails
     */
    @Test
    public void createFulfillmentOrderTest() throws ApiException, LWAException {
        String str = "{\"marketplaceId\":\"A1VC38T7YXB528\",\"sellerFulfillmentOrderId\":\"WFHD25102706819\",\"displayableOrderId\":\"430315-20251023-0158533478\",\"displayableOrderDate\":\"2025-10-27T02:24:46.126Z\",\"displayableOrderComment\":\"WFHD25102706819\",\"shippingSpeedCategory\":\"Expedited\",\"destinationAddress\":{\"name\":\"石川 大樹\",\"addressLine1\":\"大字下落合1074-1サンクタス与野タワーレジデンス2002号\",\"addressLine2\":\"\",\"addressLine3\":\"\",\"city\":\"さいたま市中央区\",\"districtOrCounty\":\"\",\"stateOrRegion\":\"埼玉県\",\"postalCode\":\"338-0002\",\"countryCode\":\"JP\",\"phone\":\"090-5423-7124\"},\"fulfillmentPolicy\":\"FillOrKill\",\"items\":[{\"sellerSku\":\"3090+0605-JP1\",\"sellerFulfillmentOrderItemId\":\"1982634200921341954\",\"quantity\":1,\"fulfillmentNetworkSku\":\"X0012ZSPXV\",\"perUnitDeclaredValue\":{\"currencyCode\":\"JPY\",\"value\":\"5880.0000\"}}]}";
        JSONObject jsonObject = JSONUtil.parseObj(str);
        CreateFulfillmentOrderRequest body = JSONUtil.toBean(jsonObject, CreateFulfillmentOrderRequest.class);
        String shopId = jsonObject.getStr("shopId", "");
        AmazonShopInfoDTO shopInfoDTO = cfgAppClientService.cacheAndFindShopAuth(shopId);
        FbaOutboundApi fbaOutboundApi = AmazonSpApiInitUtils.create(FbaOutboundApi.class, shopInfoDTO, false);
        CreateFulfillmentOrderResponse response = fbaOutboundApi.createFulfillmentOrder(body);

// TODO: test validations
    }

    /**
     *
     *
     * Creates a fulfillment return.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws ApiException if the Api call fails
     * @throws LWAException If calls to fetch LWA access token fails
     */
    @Test
    public void createFulfillmentReturnTest() throws ApiException, LWAException {
        CreateFulfillmentReturnRequest body = null;
        String sellerFulfillmentOrderId = null;
        CreateFulfillmentReturnResponse response = api.createFulfillmentReturn(body, sellerFulfillmentOrderId);

// TODO: test validations
    }

    /**
     *
     *
     * Returns delivery options that include an estimated delivery date and offer expiration, based on criteria that you specify.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 5 | 30 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws ApiException if the Api call fails
     * @throws LWAException If calls to fetch LWA access token fails
     */
    @Test
    public void deliveryOffersTest() throws ApiException, LWAException {
        GetDeliveryOffersRequest body = null;
        GetDeliveryOffersResponse response = api.deliveryOffers(body);

// TODO: test validations
    }

    /**
     *
     *
     * Returns a list of inventory items that are eligible for the fulfillment feature you specify.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api)..
     *
     * @throws ApiException if the Api call fails
     * @throws LWAException If calls to fetch LWA access token fails
     */
    @Test
    public void getFeatureInventoryTest() throws ApiException, LWAException {
        String marketplaceId = null;
        String featureName = null;
        String nextToken = null;
        OffsetDateTime queryStartDate = null;
        GetFeatureInventoryResponse response = api.getFeatureInventory(marketplaceId, featureName, nextToken, queryStartDate);

// TODO: test validations
    }

    /**
     *
     *
     * Returns the number of items with the sellerSKU you specify that can have orders fulfilled using the specified feature. Note that if the sellerSKU isn&#x27;t eligible, the response will contain an empty skuInfo object. The parameters for this operation may contain special characters that require URL encoding. To avoid errors with SKUs when encoding URLs, refer to [URL Encoding](https://developer-docs.amazon.com/sp-api/docs/url-encoding).  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws ApiException if the Api call fails
     * @throws LWAException If calls to fetch LWA access token fails
     */
    @Test
    public void getFeatureSKUTest() throws ApiException, LWAException {
        String marketplaceId = null;
        String featureName = null;
        String sellerSku = null;
        GetFeatureSkuResponse response = api.getFeatureSKU(marketplaceId, featureName, sellerSku);

// TODO: test validations
    }

    /**
     *
     *
     * Returns a list of features available for Multi-Channel Fulfillment orders in the marketplace you specify, and whether the seller for which you made the call is enrolled for each feature.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws ApiException if the Api call fails
     * @throws LWAException If calls to fetch LWA access token fails
     */
    @Test
    public void getFeaturesTest() throws ApiException, LWAException {
        String marketplaceId = null;
        GetFeaturesResponse response = api.getFeatures(marketplaceId);

// TODO: test validations
    }

    /**
     *
     *
     * Returns the fulfillment order indicated by the specified order identifier.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws ApiException if the Api call fails
     * @throws LWAException If calls to fetch LWA access token fails
     */
    @Test
    public void getFulfillmentOrderTest() throws ApiException, LWAException {
        String sellerFulfillmentOrderId = null;
        GetFulfillmentOrderResponse response = api.getFulfillmentOrder(sellerFulfillmentOrderId);

// TODO: test validations
    }

    /**
     *
     *
     * Returns a list of fulfillment order previews based on shipping criteria that you specify.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws ApiException if the Api call fails
     * @throws LWAException If calls to fetch LWA access token fails
     */
    @Test
    public void getFulfillmentPreviewTest() throws ApiException, LWAException {
        GetFulfillmentPreviewRequest body = null;
        GetFulfillmentPreviewResponse response = api.getFulfillmentPreview(body);

// TODO: test validations
    }

    /**
     *
     *
     * Returns delivery tracking information for a package in an outbound shipment for a Multi-Channel Fulfillment order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws ApiException if the Api call fails
     * @throws LWAException If calls to fetch LWA access token fails
     */
    @Test
    public void getPackageTrackingDetailsTest() throws ApiException, LWAException {
        Integer packageNumber = null;
        GetPackageTrackingDetailsResponse response = api.getPackageTrackingDetails(packageNumber);

// TODO: test validations
    }

    /**
     *
     *
     * Returns a list of fulfillment orders fulfilled after (or at) a specified date-time, or indicated by the next token parameter.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api)
     *
     * @throws ApiException if the Api call fails
     * @throws LWAException If calls to fetch LWA access token fails
     */
    @Test
    public void listAllFulfillmentOrdersTest() throws ApiException, LWAException {
        String queryStartDate = "2025-08-01T00:00:00";
        String nextToken = null;
        String shopId = "1925396781138022402";
        AmazonShopInfoDTO shopInfoDTO = cfgAppClientService.cacheAndFindShopAuth(shopId);
        // 初始化API
        FbaOutboundApi api = AmazonSpApiInitUtils.create(FbaOutboundApi.class, shopInfoDTO, false);
        ListAllFulfillmentOrdersResponse response = api.listAllFulfillmentOrders(queryStartDate, nextToken);
        System.out.println("listAllFulfillmentOrdersTest");
        System.out.println(JSONUtil.toJsonStr(response));
        // TODO: test validations
    }

    /**
     *
     *
     * Returns a list of return reason codes for a seller SKU in a given marketplace. The parameters for this operation may contain special characters that require URL encoding. To avoid errors with SKUs when encoding URLs, refer to [URL Encoding](https://developer-docs.amazon.com/sp-api/docs/url-encoding).  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws ApiException if the Api call fails
     * @throws LWAException If calls to fetch LWA access token fails
     */
    @Test
    public void listReturnReasonCodesTest() throws ApiException, LWAException {
        String sellerSku = null;
        String marketplaceId = null;
        String sellerFulfillmentOrderId = null;
        String language = null;
        ListReturnReasonCodesResponse response = api.listReturnReasonCodes(sellerSku, marketplaceId, sellerFulfillmentOrderId, language);

// TODO: test validations
    }

    /**
     *
     *
     * Requests that Amazon update the status of an order in the sandbox testing environment. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Fulfillment Outbound Dynamic Sandbox Guide](https://developer-docs.amazon.com/sp-api/docs/fulfillment-outbound-dynamic-sandbox-guide) and [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.
     *
     * @throws ApiException if the Api call fails
     * @throws LWAException If calls to fetch LWA access token fails
     */
    @Test
    public void submitFulfillmentOrderStatusUpdateTest() throws ApiException, LWAException {
        SubmitFulfillmentOrderStatusUpdateRequest body = null;
        String sellerFulfillmentOrderId = null;
        SubmitFulfillmentOrderStatusUpdateResponse response = api.submitFulfillmentOrderStatusUpdate(body, sellerFulfillmentOrderId);

// TODO: test validations
    }

    /**
     *
     *
     * Updates and/or requests shipment for a fulfillment order with an order hold on it.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 30 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws ApiException if the Api call fails
     * @throws LWAException If calls to fetch LWA access token fails
     */
    @Test
    public void updateFulfillmentOrderTest() throws ApiException, LWAException {
        UpdateFulfillmentOrderRequest body = null;
        String sellerFulfillmentOrderId = null;
        UpdateFulfillmentOrderResponse response = api.updateFulfillmentOrder(body, sellerFulfillmentOrderId);

        // TODO: test validations
    }
}