/*
 * Selling Partner API for Feeds
 * The Selling Partner API for Feeds lets you upload data to Amazon on behalf of a selling partner.
 *
 * OpenAPI spec version: 2021-06-30
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.erp.server.dmp.amz;


import com.erp.model.dmp.dto.AmazonShopInfoDTO;
import com.erp.sdk.oms.amz.spapi.api.FeedsApi;
import com.erp.sdk.oms.amz.spapi.client.ApiException;
import com.erp.sdk.oms.amz.spapi.client.JSON;
import com.erp.sdk.oms.amz.spapi.enums.AmazonEndpointsEnum;
import com.erp.sdk.oms.amz.spapi.enums.AmazonMarketplaceEnum;
import com.erp.sdk.oms.amz.spapi.model.feeds.*;
import com.erp.server.dmp.ErpServerDmpApplication;
import okhttp3.*;
import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpPut;
import org.apache.http.entity.FileEntity;
import org.apache.http.entity.InputStreamEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Profile;
import org.springframework.test.context.junit4.SpringRunner;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

/**
 * API tests for FeedsApi
 */
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerDmpApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@Profile("dev")
public class FeedsApiTest {


    /**
     * Cancels the feed that you specify. Only feeds with processingStatus&#x3D;IN_QUEUE can be cancelled. Cancelled feeds are returned in subsequent calls to the getFeed and getFeeds operations.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 0.0222 | 10 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cancelFeedTest() throws ApiException {
//        String feedId = null;
//        FeedsApi api = FeedsApi.initApi(AmazonMarketplaceEnum.US);
//        api.cancelFeed(feedId);

        // TODO: test validations
    }

    /**
     * Creates a feed. Upload the contents of the feed document before calling this operation.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 0.0083 | 15 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createFeedTest() throws ApiException {
        CreateFeedSpecification body = null;
////        FeedsApi api = FeedsApi.initApi(AmazonMarketplaceEnum.US);
//        CreateFeedResponse response = api.createFeed(body);

        // TODO: test validations
    }

    /**
     * Creates a feed document for the feed type that you specify. This operation returns a presigned URL for uploading the feed document contents. It also returns a feedDocumentId value that you can pass in with a subsequent call to the createFeed operation.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 0.0083 | 15 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createFeedDocumentTest() throws ApiException, IOException {
        CreateFeedDocumentSpecification body = new CreateFeedDocumentSpecification();
        body.setContentType("application/pdf");
        AmazonShopInfoDTO shopInfoDTO = new AmazonShopInfoDTO();
        shopInfoDTO.setClientId("amzn1.application-oa2-client.aa03ca5c8fd741a49df6e35aac3c3287");
        shopInfoDTO.setSecretKey("t6CqSJE9o5OSONJiW+pCz7EFRHwJFtX3RIJSRP4B");
        shopInfoDTO.setAccessKeyId("AKIARVXX3YJGDV2NGA4L");
        shopInfoDTO.setRefreshToken("Atzr|IwEBIGMAY2S_GKCS6zsuZzJzKkh8FxQO0Ox_e2rGDsMcc5edGjctvjXjC-TtSWg2M3XGaNisFQqg2z_KwROD8xVOazVQkZBc4f4VIgTsIDPSlZ2fIHaONs_HA6J7hToolnOgbcli2M_CX1vXkPPxCRbW1JrQQlIDfdiHkMakJ5VAAnFPokQf3vcLv0P1gngOfbCL1KdhKyDBLGQLfEkwdKQ1r0jaeU6jkT6XB8iyDYvo_f-Ms87R-Xv6J4XMFhOtY_Z9BhixpGkNhbjz_ns0I-ejfcpLnDgHer02Syqi2ZTPIsF_pSOHtVs1yZj-OGdB0V0f66EOopfvV_53HnkmMNNS6Em7");
        shopInfoDTO.setAccessToken("Atza|IwEBIM9f4smxHNb26lLYf2FnST99jUcyepdw67K9U0XsK3fQDHFjw_7jD-Tt49olnkWsKf0TMHeyFkOsvSuPoEy8ADUX9az6nJmWXC6TabsuZ5Pyc5SsD4MEAtQyzgHm76KkEuiID5yMQKc2DUrmIcwVRx6WZ_bBTK8lYgqM9oUlteUL2cjaXN_KbUsu0igoE0w3qZC_h5Ua9r7xKAozP4qba6z6CNxCpuxIdxThwmKRXKLplvEoHT_CthoU6lOG3zN7gnCKieC6CjxM2urRL8KtL564eG_Z7YSSfzQbitIy8mWdodsxqN4N5BGWqDLtYn-5plV6m1b_LR8NZQzUDnh_I2mBYehl1_IeAhr5Ptc2A2g8Yw");
        shopInfoDTO.setAuthUrl("https://api.amazon.com/auth/o2/token");
        shopInfoDTO.setRoleStr("arn:aws:iam::115410190924:role/DehouRole");
        shopInfoDTO.setClientSecret("amzn1.oa2-cs.v1.fbb86fa8cb4ef1d12371197a1637e6429f3876d7b5520d39054519a82b05e988");
        FeedsApi api = FeedsApi.initApi(AmazonEndpointsEnum.US_WAST_2,shopInfoDTO);
        CreateFeedDocumentResponse response = api.createFeedDocument(body);
        String url = response.getUrl();
        System.out.println(url);
        File fileToUpload = new File("C:\\Users\\Administrator\\Desktop\\testamz\\invoice-Abed.pdf");
        InputStream inputStream = Files.newInputStream(fileToUpload.toPath());
        try (CloseableHttpClient httpClient = HttpClients.createDefault()) {
            HttpPut putRequest = new HttpPut(url);
            putRequest.setHeader("Content-Type", "application/pdf");
            putRequest.setEntity(new InputStreamEntity(inputStream));

            // 执行请求
            HttpResponse httpResponse = httpClient.execute(putRequest);
            int statusCode = httpResponse.getStatusLine().getStatusCode();
            if (statusCode == 200 || statusCode == 201) {
                System.out.println("文件上传成功");
                CreateFeedSpecification createFeedSpecification = new CreateFeedSpecification();
                createFeedSpecification.setFeedType("UPLOAD_VAT_INVOICE");
                createFeedSpecification.setInputFeedDocumentId(response.getFeedDocumentId());
                createFeedSpecification.setMarketplaceIds(Arrays.asList("A17E79C6D8DWNP"));
                FeedOptions feedOptions = new FeedOptions();
                feedOptions.put("OrderId","404-7019951-2767504");
                feedOptions.put("InvoiceNumber","InvoiceNumber-WJ123456");
                feedOptions.put("DocumentType","Invoice");
                createFeedSpecification.setFeedOptions(feedOptions);
                CreateFeedResponse createFeedResponse = api.createFeed(createFeedSpecification);
                System.out.println(createFeedResponse);
            } else {
                System.out.println("上传失败，状态码：" + statusCode);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * Returns feed details (including the resultDocumentId, if available) for the feed that you specify.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2.0 | 15 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFeedTest() throws ApiException {
//        String feedId = null;
//        FeedsApi api = FeedsApi.initApi(AmazonMarketplaceEnum.US);
//        Feed response = api.getFeed(feedId);

        // TODO: test validations
    }

    /**
     * Returns the information required for retrieving a feed document&#39;s contents.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 0.0222 | 10 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFeedDocumentTest() throws ApiException {
//        String feedDocumentId = null;
//        FeedsApi api = FeedsApi.initApi(AmazonMarketplaceEnum.US);
//        FeedDocument response = api.getFeedDocument(feedDocumentId);

        // TODO: test validations
    }

    /**
     * Returns feed details for the feeds that match the filters that you specify.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 0.0222 | 10 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFeedsTest() throws ApiException {
//        List<String> feedTypes = null;
//        List<String> marketplaceIds = null;
//        Integer pageSize = null;
//        List<String> processingStatuses = null;
//        OffsetDateTime createdSince = null;
//        OffsetDateTime createdUntil = null;
//        String nextToken = null;
//        FeedsApi api = FeedsApi.initApi(AmazonMarketplaceEnum.US);
//        GetFeedsResponse response = api.getFeeds(feedTypes, marketplaceIds, pageSize, processingStatuses, createdSince, createdUntil, nextToken);

        // TODO: test validations
    }

}
