/*
 * Selling Partner API for Reports
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * OpenAPI spec version: 2021-06-30
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.erp.server.dmp.amz;

import com.amazon.sqs.javamessaging.message.SQSTextMessage;
import com.erp.sdk.oms.amz.spapi.api.ReportsApi;
import com.erp.sdk.oms.amz.spapi.client.ApiException;
import com.erp.sdk.oms.amz.spapi.client.JSON;
import com.erp.sdk.oms.amz.spapi.enums.AmazonMarketplaceEnum;
import com.erp.sdk.oms.amz.spapi.model.reports.*;
import com.erp.server.dmp.ErpServerDmpApplication;
import com.erp.server.dmp.service.mq.JmsAmazonSqsConsumer;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Profile;
import org.springframework.test.context.junit4.SpringRunner;

import javax.annotation.Resource;
import java.util.Arrays;
import java.util.List;

/**
 * API tests for ReportsApi
 */
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerDmpApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@Profile("dev")
public class JmsConsumerTest {

    @Resource
    private JmsAmazonSqsConsumer jmsAmazonSqsConsumer;


    /**
     * 库存管理
     */
    @Test
    public void consumerTest() throws Exception {
        SQSTextMessage sqsTextMessage = new SQSTextMessage();
        sqsTextMessage.setText("{\n" +
                "  \"notificationVersion\" : \"2020-09-04\",\n" +
                "  \"notificationType\" : \"REPORT_PROCESSING_FINISHED\",\n" +
                "  \"payloadVersion\" : \"1.0\",\n" +
                "  \"eventTime\" : \"2023-11-08T09:45:39.054Z\",\n" +
                "  \"payload\" : {\n" +
                "    \"reportProcessingFinishedNotification\" : {\n" +
                "      \"sellerId\" : \"AZFY4CTNEDLZX\",\n" +
                "      \"reportId\" : \"728735019671\",\n" +
                "      \"reportType\" : \"GET_FBA_MYI_ALL_INVENTORY_DATA\",\n" +
                "      \"processingStatus\" : \"DONE\",\n" +
                "      \"reportDocumentId\" : \"amzn1.spdoc.1.4.na.2d0bcb71-6156-4f48-ae75-e938007bbb52.TX9QAR79N9HUR.2650\"\n" +
                "    }\n" +
                "  },\n" +
                "  \"notificationMetadata\" : {\n" +
                "    \"applicationId\" : \"amzn1.sp.solution.c49ad2b8-5338-493f-b312-550e59f0b2b4\",\n" +
                "    \"subscriptionId\" : \"f80d1da5-c932-4e1f-a36d-e434bca8deb6\",\n" +
                "    \"publishTime\" : \"2023-11-10T13:00:48.096Z\",\n" +
                "    \"notificationId\" : \"test-a79a47eb-f5c6-4d74-81a7-0e132468e6cf\"\n" +
                "  }\n" +
                "}");
        jmsAmazonSqsConsumer.consumerListener(sqsTextMessage);
    }

    /**
     * 预留报告
     */
    @Test
    public void consumer2Test() throws Exception {
        SQSTextMessage sqsTextMessage = new SQSTextMessage();
        sqsTextMessage.setText("{\n" +
                "  \"notificationVersion\" : \"2020-09-04\",\n" +
                "  \"notificationType\" : \"REPORT_PROCESSING_FINISHED\",\n" +
                "  \"payloadVersion\" : \"1.0\",\n" +
                "  \"eventTime\" : \"2023-11-08T09:45:39.054Z\",\n" +
                "  \"payload\" : {\n" +
                "    \"reportProcessingFinishedNotification\" : {\n" +
                "      \"sellerId\" : \"AZFY4CTNEDLZX\",\n" +
                "      \"reportId\" : \"728736019671\",\n" +
                "      \"reportType\" : \"GET_RESERVED_INVENTORY_DATA\",\n" +
                "      \"processingStatus\" : \"DONE\",\n" +
                "      \"reportDocumentId\" : \"amzn1.spdoc.1.4.na.1c673ff8-11a1-42bf-a07c-d9a6d02bfbf8.T2G3AC9GCLSG9A.2681\"\n" +
                "    }\n" +
                "  },\n" +
                "  \"notificationMetadata\" : {\n" +
                "    \"applicationId\" : \"amzn1.sp.solution.c49ad2b8-5338-493f-b312-550e59f0b2b4\",\n" +
                "    \"subscriptionId\" : \"f80d1da5-c932-4e1f-a36d-e434bca8deb6\",\n" +
                "    \"publishTime\" : \"2023-11-10T13:00:48.096Z\",\n" +
                "    \"notificationId\" : \"test1-a79a47eb-f5c6-4d74-81a7-0e132468e6cf\"\n" +
                "  }\n" +
                "}");
        jmsAmazonSqsConsumer.consumerListener(sqsTextMessage);
    }


    /**
     * 库龄报告
     */
    @Test
    public void consumer3Test() throws Exception {
        SQSTextMessage sqsTextMessage = new SQSTextMessage();
        sqsTextMessage.setText("{\n" +
                "  \"notificationVersion\" : \"2020-09-04\",\n" +
                "  \"notificationType\" : \"REPORT_PROCESSING_FINISHED\",\n" +
                "  \"payloadVersion\" : \"1.0\",\n" +
                "  \"eventTime\" : \"2023-11-08T09:45:39.054Z\",\n" +
                "  \"payload\" : {\n" +
                "    \"reportProcessingFinishedNotification\" : {\n" +
                "      \"sellerId\" : \"AZFY4CTNEDLZX\",\n" +
                "      \"reportId\" : \"728730019671\",\n" +
                "      \"reportType\" : \"GET_FBA_INVENTORY_PLANNING_DATA\",\n" +
                "      \"processingStatus\" : \"DONE\",\n" +
                "      \"reportDocumentId\" : \"amzn1.spdoc.1.4.na.96b9d852-8954-4ee0-8e58-10c7e380b30e.T3KRSTU9KGSS1F.19600\"\n" +
                "    }\n" +
                "  },\n" +
                "  \"notificationMetadata\" : {\n" +
                "    \"applicationId\" : \"amzn1.sp.solution.c49ad2b8-5338-493f-b312-550e59f0b2b4\",\n" +
                "    \"subscriptionId\" : \"f80d1da5-c932-4e1f-a36d-e434bca8deb6\",\n" +
                "    \"publishTime\" : \"2023-11-10T13:00:48.096Z\",\n" +
                "    \"notificationId\" : \"test3-a79a47eb-f5c6-4d74-81a7-0e132468e6cf\"\n" +
                "  }\n" +
                "}");
        jmsAmazonSqsConsumer.consumerListener(sqsTextMessage);
    }
}
