/*
 * Selling Partner API for Listings Items
 * The Selling Partner API for Listings Items (Listings Items API) provides programmatic access to selling partner listings on Amazon. Use this API in collaboration with the Selling Partner API for Product Type Definitions, which you use to retrieve the information about Amazon product types needed to use the Listings Items API.  For more information, see the [Listings Items API Use Case Guide](doc:listings-items-api-v2021-08-01-use-case-guide).
 *
 * OpenAPI spec version: 2021-08-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.erp.server.dmp.amz;

import cn.hutool.json.JSONUtil;
import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.AWSAuthenticationCredentials;
import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.AWSAuthenticationCredentialsProvider;
import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.LWAAuthorizationCredentials;
import com.erp.sdk.oms.amz.spapi.api.ListingsApi;
import com.erp.sdk.oms.amz.spapi.client.ApiException;
import com.erp.sdk.oms.amz.spapi.utils.AmazonSpApiConfigUtil;
import com.erp.sdk.oms.amz.spapi.enums.AmazonMarketplaceEnum;
import com.erp.sdk.oms.amz.spapi.model.listingsitems.Item;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import com.erp.server.dmp.ErpServerDmpApplication;
import org.springframework.context.annotation.Profile;
import org.springframework.test.context.junit4.SpringRunner;
import org.junit.Test;

import java.util.Arrays;
import java.util.List;

/**
 * API tests for ListingsApi
 */
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerDmpApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@Profile("dev")
public class ListingsApiTest {

    private final ListingsApi api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US);

    public ListingsApi amazonAuthorizationGrant(AmazonMarketplaceEnum marketplaceEnum) {
        AWSAuthenticationCredentials awsAuthenticationCredentials = AmazonSpApiConfigUtil.buildAWSAuthenticationCredentials(marketplaceEnum.getEndpointsEnum());
        LWAAuthorizationCredentials lwaAuthorizationCredentials = AmazonSpApiConfigUtil.buildLWAAuthorizationCredentials();
        AWSAuthenticationCredentialsProvider awsAuthenticationCredentialsProvider = AmazonSpApiConfigUtil.buildAWSAuthenticationCredentialsProvider();
        ListingsApi listingsApi = new ListingsApi.Builder()
                .awsAuthenticationCredentials(awsAuthenticationCredentials)
                .lwaAuthorizationCredentials(lwaAuthorizationCredentials)
                .awsAuthenticationCredentialsProvider(awsAuthenticationCredentialsProvider)
                //注意，这里的endpoint分北美，欧洲，远东三个地域，每个区域的链接是不一样的
                //北美，https://sellingpartnerapi-na.amazon.com
                //欧洲，https://sellingpartnerapi-eu.amazon.com
                //远东，https://sellingpartnerapi-fe.amazon.com
                .endpoint(marketplaceEnum.getEndpointsEnum().getEndpointsByProfile())
                .build();
        if (null == listingsApi) {
            throw new RuntimeException("授权失败，未获取到API实例的话抛出异常，进行重试");
        }
        return listingsApi;
    }

    
//    /**
//     *
//     *
//     * Delete a listings item for a selling partner.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 5 | 10 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void deleteListingsItemTest() throws ApiException {
//        String sellerId = null;
//        String sku = null;
//        List<String> marketplaceIds = null;
//        String issueLocale = null;
//        ListingsItemSubmissionResponse response = api.deleteListingsItem(sellerId, sku, marketplaceIds, issueLocale);
//        System.out.println(response);
//        // TODO: test validations
//    }
//
    /**
     * 
     *
     * Returns details about a listings item for a selling partner.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 5 | 10 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getListingsItemTest() throws ApiException {
        String sellerId = "AZFY4CTNEDLZX";
        String sku = "1963-US7";
        List<String> marketplaceIds = Arrays.asList("A1AM78C64UM0Y8");;
        String issueLocale = null;
        List<String> includedData = null;
        Item response = api.getListingsItem(sellerId, sku, marketplaceIds, issueLocale, includedData);
        System.out.println("ListingsItem信息");
        System.out.println(JSONUtil.toJsonStr(response));

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Partially update (patch) a listings item for a selling partner. Only top-level listings item attributes can be patched. Patching nested attributes is not supported.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 5 | 10 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws ApiException
     *          if the Api call fails
     */
//    @Test
//    public void patchListingsItemTest() throws ApiException {
//        String sellerId = null;
//        String sku = null;
//        List<String> marketplaceIds = null;
//        ListingsItemPatchRequest body = null;
//        String issueLocale = null;
//        ListingsItemSubmissionResponse response = api.patchListingsItem(sellerId, sku, marketplaceIds, body, issueLocale);
//
//        // TODO: test validations
//    }
    
    /**
     * 
     *
     * Creates a new or fully-updates an existing listings item for a selling partner.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 5 | 10 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws ApiException
     *          if the Api call fails
     */
//    @Test
//    public void putListingsItemTest() throws ApiException {
//        String sellerId = null;
//        String sku = null;
//        List<String> marketplaceIds = null;
//        ListingsItemPutRequest body = null;
//        String issueLocale = null;
//        ListingsItemSubmissionResponse response = api.putListingsItem(sellerId, sku, marketplaceIds, body, issueLocale);
//
//        // TODO: test validations
//    }
    
}
