/*
 * Selling Partner API for Listings Restrictions
 * The Selling Partner API for Listings Restrictions provides programmatic access to restrictions on Amazon catalog listings.  For more information, see the [Listings Restrictions API Use Case Guide](doc:listings-restrictions-api-v2021-08-01-use-case-guide).
 *
 * OpenAPI spec version: 2021-08-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.erp.server.dmp.amz;

import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.AWSAuthenticationCredentials;
import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.AWSAuthenticationCredentialsProvider;
import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.LWAAuthorizationCredentials;
import com.erp.sdk.oms.amz.spapi.api.ListingsRestrictionsApi;
import com.erp.sdk.oms.amz.spapi.client.ApiException;
import com.erp.sdk.oms.amz.spapi.utils.AmazonSpApiConfigUtils;
import com.erp.sdk.oms.amz.spapi.enums.AmazonMarketplaceEnum;
import com.erp.sdk.oms.amz.spapi.model.listingsrestrictions.RestrictionList;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import com.erp.server.dmp.ErpServerDmpApplication;
import org.springframework.context.annotation.Profile;
import org.springframework.test.context.junit4.SpringRunner;
import org.junit.Test;

import java.util.List;

/**
 * API tests for ListingsApi
 */
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerDmpApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@Profile("dev")
public class ListingsRestrictionsApiTest {

    private final ListingsRestrictionsApi api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US);

    public ListingsRestrictionsApi amazonAuthorizationGrant(AmazonMarketplaceEnum marketplaceEnum) {
//        AWSAuthenticationCredentials awsAuthenticationCredentials = AmazonSpApiConfigUtils.buildAWSAuthenticationCredentials(marketplaceEnum.getEndpointsEnum());
//        LWAAuthorizationCredentials lwaAuthorizationCredentials = AmazonSpApiConfigUtils.buildLWAAuthorizationCredentials();
//        AWSAuthenticationCredentialsProvider awsAuthenticationCredentialsProvider = AmazonSpApiConfigUtils.buildAWSAuthenticationCredentialsProvider();
//        ListingsRestrictionsApi listingsRestrictionsApi = new ListingsRestrictionsApi.Builder()
//                .awsAuthenticationCredentials(awsAuthenticationCredentials)
//                .lwaAuthorizationCredentials(lwaAuthorizationCredentials)
//                .awsAuthenticationCredentialsProvider(awsAuthenticationCredentialsProvider)
//                //注意，这里的endpoint分北美，欧洲，远东三个地域，每个区域的链接是不一样的
//                //北美，https://sellingpartnerapi-na.amazon.com
//                //欧洲，https://sellingpartnerapi-eu.amazon.com
//                //远东，https://sellingpartnerapi-fe.amazon.com
//                .endpoint(marketplaceEnum.getEndpointsEnum().getEndpointsByProfile())
//                .build();
//        if (null == listingsRestrictionsApi) {
//            throw new RuntimeException("授权失败，未获取到API实例的话抛出异常，进行重试");
//        }
//        return listingsRestrictionsApi;
        return null;
    }

    
    /**
     * 
     *
     * Returns listing restrictions for an item in the Amazon Catalog.   **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 5 | 10 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getListingsRestrictionsTest() throws ApiException {
        String asin = null;
        String sellerId = null;
        List<String> marketplaceIds = null;
        String conditionType = null;
        String reasonLocale = null;
        RestrictionList response = api.getListingsRestrictions(asin, sellerId, marketplaceIds, conditionType, reasonLocale);

        // TODO: test validations
    }
    
}
