/*
 * Selling Partner API for Notifications
 * The Selling Partner API for Notifications lets you subscribe to notifications that are relevant to a selling partner's business. Using this API you can create a destination to receive notifications, subscribe to notifications, delete notification subscriptions, and more.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.erp.server.dmp.amz;

import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.AWSAuthenticationCredentials;
import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.AWSAuthenticationCredentialsProvider;
import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.LWAAuthorizationCredentials;
import com.erp.sdk.oms.amz.spapi.api.NotificationsApi;
import com.erp.sdk.oms.amz.spapi.client.ApiException;
import com.erp.sdk.oms.amz.spapi.client.JSON;
import com.erp.sdk.oms.amz.spapi.enums.AmazonMarketplaceEnum;
import com.erp.sdk.oms.amz.spapi.model.notifications.*;
import com.erp.sdk.oms.amz.spapi.utils.AmazonSpApiConfigUtils;
import com.erp.server.dmp.ErpServerDmpApplication;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Profile;
import org.springframework.test.context.junit4.SpringRunner;

/**
 * API tests for NotificationsApi
 */
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerDmpApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@Profile("dev")
public class NotificationsApiTest {

    public NotificationsApi amazonAuthorizationGrantScope(AmazonMarketplaceEnum marketplaceEnum, boolean isSandbox) {
        AWSAuthenticationCredentials awsAuthenticationCredentials = AmazonSpApiConfigUtils.buildAWSAuthenticationCredentials(marketplaceEnum.getEndpointsEnum());
        LWAAuthorizationCredentials lwaAuthorizationCredentials = AmazonSpApiConfigUtils.buildLWAAuthorizationScopeCredentials();
        AWSAuthenticationCredentialsProvider awsAuthenticationCredentialsProvider = AmazonSpApiConfigUtils.buildAWSAuthenticationCredentialsProvider();
        NotificationsApi reportApi = new NotificationsApi.Builder()
                .lwaAuthorizationCredentials(lwaAuthorizationCredentials)
                .awsAuthenticationCredentials(awsAuthenticationCredentials)
                .awsAuthenticationCredentialsProvider(awsAuthenticationCredentialsProvider)
                .endpoint(isSandbox ? marketplaceEnum.getEndpointsEnum().getEndpointsByProfile() : marketplaceEnum.getEndpointsEnum().getEndpoints())
                .build();
        if (null == reportApi) {
            throw new RuntimeException("授权失败，未获取到API实例的话抛出异常，进行重试");
        }
        return reportApi;
    }

    public NotificationsApi amazonAuthorizationGrant(AmazonMarketplaceEnum marketplaceEnum, boolean isSandbox) {
        AWSAuthenticationCredentials awsAuthenticationCredentials = AmazonSpApiConfigUtils.buildAWSAuthenticationCredentials(marketplaceEnum.getEndpointsEnum());
        LWAAuthorizationCredentials lwaAuthorizationCredentials = AmazonSpApiConfigUtils.buildLWAAuthorizationCredentials();
        AWSAuthenticationCredentialsProvider awsAuthenticationCredentialsProvider = AmazonSpApiConfigUtils.buildAWSAuthenticationCredentialsProvider();
        NotificationsApi reportApi = new NotificationsApi.Builder()
                .lwaAuthorizationCredentials(lwaAuthorizationCredentials)
                .awsAuthenticationCredentials(awsAuthenticationCredentials)
                .awsAuthenticationCredentialsProvider(awsAuthenticationCredentialsProvider)
                .endpoint(isSandbox ? marketplaceEnum.getEndpointsEnum().getEndpointsByProfile() : marketplaceEnum.getEndpointsEnum().getEndpoints())
                .build();
        if (null == reportApi) {
            throw new RuntimeException("授权失败，未获取到API实例的话抛出异常，进行重试");
        }
        return reportApi;
    }


    /**
     * Creates a destination resource to receive notifications. The createDestination API is grantless. For more information, see \&quot;Grantless operations\&quot; in the Selling Partner API Developer Guide.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createDestinationTest() throws Exception {
        // 沙箱环境
//        CreateDestinationRequest body = new CreateDestinationRequest();
        // 正式环境
        CreateDestinationRequest body = new CreateDestinationRequest();
        body.setName("ERP消息通知队列");
        DestinationResourceSpecification specification = new DestinationResourceSpecification();
        SqsResource sqsResource = new SqsResource();
//        sqsResource.setArn("arn:aws:sqs:us-east-1:700518745840:test_erp");
        sqsResource.setArn("arn:aws:sqs:us-east-1:700518745840:erpNotifications");
        specification.setSqs(sqsResource);

//        EventBridgeResourceSpecification eventBridgeResourceSpecification = new EventBridgeResourceSpecification();
//        eventBridgeResourceSpecification.setAccountId("700518745840");
//        eventBridgeResourceSpecification.setRegion(AmazonMarketplaceEnum.US.getEndpointsEnum().getRegion());
//        specification.setEventBridge(eventBridgeResourceSpecification);
        body.setResourceSpecification(specification);

        NotificationsApi api = amazonAuthorizationGrantScope(AmazonMarketplaceEnum.US, false);
        CreateDestinationResponse response = api.createDestination(body);
        System.out.println("创建目标");
        System.out.println(JSON.toJsonStr(response));
        // TODO: test validations
        // 沙箱:
        // {"payload":{"name":"SQSDestination","destinationId":"TEST_CASE_200_DESTINATION_ID","resource":{"sqs":{"arn":"arn:aws:sqs:us-east-2:444455556666:queue1"}}}}
        // 正式环境测试
        // {"payload":{"name":"测试服Destination","destinationId":"5ace5b8e-bdff-4a74-ae7b-bc6d640f8b5d","resource":{"eventBridge":{"name":"aws.partner/sellingpartnerapi.amazon.com/700518745840/amzn1.sp.solution.c49ad2b8-5338-493f-b312-550e59f0b2b4","region":"us-east-1","accountId":"700518745840"}}}}
        // {"payload":{"name":"测试服Destination","destinationId":"cda7f9f6-ad95-4500-b800-706727405ec9","resource":{"sqs":{"arn":"arn:aws:sqs:us-east-1:700518745840:test_erp"}}}}
        // ERP消息通知队列
        // {"payload":{"name":"ERP消息通知队列","destinationId":"278e5b05-6ff9-4e94-8273-9ab9ed0dfb2b","resource":{"sqs":{"arn":"arn:aws:sqs:us-east-1:700518745840:erpNotifications"}}}}
    }

    /**
     * Creates a subscription for the specified notification type to be delivered to the specified destination. Before you can subscribe, you must first create the destination by calling the createDestination operation.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSubscriptionTest() throws ApiException {
        CreateSubscriptionRequest body = new CreateSubscriptionRequest();
        body.setPayloadVersion("1.0");
        body.setDestinationId("278e5b05-6ff9-4e94-8273-9ab9ed0dfb2b");
        String notificationType = "REPORT_PROCESSING_FINISHED";
//        String notificationType = "reportProcessingFinished";
        NotificationsApi api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US, false);
        CreateSubscriptionResponse response = api.createSubscription(body, notificationType);
        System.out.println("创建订阅");
        System.out.println(JSON.toJsonStr(response));
        // {"payload":{"subscriptionId":"1cc84b10-6f1c-406b-a9b2-3f688d564e94","payloadVersion":"1.0","destinationId":"cda7f9f6-ad95-4500-b800-706727405ec9"}}
        // {"payload":{"subscriptionId":"bdab9dad-e1e7-4334-a0b4-316c4f17c7ad","payloadVersion":"1.0","destinationId":"278e5b05-6ff9-4e94-8273-9ab9ed0dfb2b"}}
        // {"payload":{"subscriptionId":"f80d1da5-c932-4e1f-a36d-e434bca8deb6","payloadVersion":"1.0","destinationId":"278e5b05-6ff9-4e94-8273-9ab9ed0dfb2b"}}
    }

    /**
     * Deletes the destination that you specify. The deleteDestination API is grantless. For more information, see \&quot;Grantless operations\&quot; in the Selling Partner API Developer Guide.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteDestinationTest() throws Exception {
        String destinationId = "cda7f9f6-ad95-4500-b800-706727405ec9";
        NotificationsApi api = amazonAuthorizationGrantScope(AmazonMarketplaceEnum.US, false);
        DeleteDestinationResponse response = api.deleteDestination(destinationId);
        System.out.println("删除目标");
        System.out.println(JSON.toJsonStr(response));

        // TODO: test validations
    }

    /**
     * Deletes the subscription indicated by the subscription identifier and notification type that you specify. The subscription identifier can be for any subscription associated with your application. After you successfully call this operation, notifications will stop being sent for the associated subscription. The deleteSubscriptionById API is grantless. For more information, see \&quot;Grantless operations\&quot; in the Selling Partner API Developer Guide.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteSubscriptionByIdTest() throws ApiException {
//        String subscriptionId = null;
//        String subscriptionId = "1cc84b10-6f1c-406b-a9b2-3f688d564e94";
        String subscriptionId = "bdab9dad-e1e7-4334-a0b4-316c4f17c7ad";
        String notificationType = "REPORT_PROCESSING_FINISHED";

        NotificationsApi api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US, false);
        DeleteSubscriptionByIdResponse response = api.deleteSubscriptionById(subscriptionId, notificationType);
        System.out.println("删除订阅");
        System.out.println(JSON.toJsonStr(response));
        // TODO: test validations
    }

    /**
     * Returns information about the destination that you specify. The getDestination API is grantless. For more information, see \&quot;Grantless operations\&quot; in the Selling Partner API Developer Guide.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDestinationTest() throws Exception {
//        String destinationId = "5ace5b8e-bdff-4a74-ae7b-bc6d640f8b5d";
        String destinationId = "cda7f9f6-ad95-4500-b800-706727405ec9";
        NotificationsApi api = amazonAuthorizationGrantScope(AmazonMarketplaceEnum.US, false);
        GetDestinationResponse response = api.getDestination(destinationId);
        System.out.println("获取Destination信息");
        System.out.println(JSON.toJsonStr(response));
        // {"payload":{"name":"测试服Destination","destinationId":"5ace5b8e-bdff-4a74-ae7b-bc6d640f8b5d","resource":{"eventBridge":{"name":"aws.partner/sellingpartnerapi.amazon.com/700518745840/amzn1.sp.solution.c49ad2b8-5338-493f-b312-550e59f0b2b4","region":"us-east-1","accountId":"700518745840"}}}}
        // {"payload":{"name":"测试服Destination","destinationId":"cda7f9f6-ad95-4500-b800-706727405ec9","resource":{"sqs":{"arn":"arn:aws:sqs:us-east-1:700518745840:test_erp"}}}}
        // TODO: test validations
    }

    /**
     * Returns information about all destinations. The getDestinations API is grantless. For more information, see \&quot;Grantless operations\&quot; in the Selling Partner API Developer Guide.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDestinationsTest() throws Exception {
        NotificationsApi api = amazonAuthorizationGrantScope(AmazonMarketplaceEnum.US, false);
        GetDestinationsResponse response = api.getDestinations();
        System.out.println("getDestinationsTest");
        System.out.println(JSON.toJsonStr(response));
        // TODO: test validations
    }

    /**
     * Returns information about subscriptions of the specified notification type. You can use this API to get subscription information when you do not have a subscription identifier.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSubscriptionTest() throws Exception {
        String notificationType = "REPORT_PROCESSING_FINISHED";
        NotificationsApi api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US, false);
        GetSubscriptionResponse response = api.getSubscription(notificationType);
        System.out.println("获取订阅信息");
        System.out.println(JSON.toJsonStr(response));
        // TODO: test validations
        // {"payload":{"subscriptionId":"1cc84b10-6f1c-406b-a9b2-3f688d564e94","payloadVersion":"1.0","destinationId":"cda7f9f6-ad95-4500-b800-706727405ec9"}}
        // {"payload":{"subscriptionId":"bdab9dad-e1e7-4334-a0b4-316c4f17c7ad","payloadVersion":"1.0","destinationId":"278e5b05-6ff9-4e94-8273-9ab9ed0dfb2b"}}
        //
    }

    /**
     * Returns information about a subscription for the specified notification type. The getSubscriptionById API is grantless. For more information, see \&quot;Grantless operations\&quot; in the Selling Partner API Developer Guide.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSubscriptionByIdTest() throws ApiException {
        String subscriptionId = "f80d1da5-c932-4e1f-a36d-e434bca8deb6";
        String notificationType = "REPORT_PROCESSING_FINISHED";
        NotificationsApi api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US, false);
        GetSubscriptionByIdResponse response = api.getSubscriptionById(subscriptionId, notificationType);
        System.out.println("通过id查询Subscription");
        System.out.println(JSON.toJsonStr(response));
        // {"payload":{"subscriptionId":"1cc84b10-6f1c-406b-a9b2-3f688d564e94","payloadVersion":"1.0","destinationId":"cda7f9f6-ad95-4500-b800-706727405ec9"}}
        // {"payload":{"subscriptionId":"f80d1da5-c932-4e1f-a36d-e434bca8deb6","payloadVersion":"1.0","destinationId":"278e5b05-6ff9-4e94-8273-9ab9ed0dfb2b"}}
        //
        // TODO: test validations
    }

}
