/*
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.erp.server.dmp.amz;

import com.common.core.exception.ServiceException;
import com.erp.model.dmp.dto.AmazonShopInfoDTO;
import com.erp.sdk.oms.amz.spapi.api.ProductPricingApi;
import com.erp.sdk.oms.amz.spapi.client.ApiException;
import com.erp.sdk.oms.amz.spapi.client.JSON;
import com.erp.sdk.oms.amz.spapi.model.productpricing.GetOffersResponse;
import com.erp.sdk.oms.amz.spapi.model.productpricing.GetPricingResponse;
import com.erp.sdk.oms.amz.spapi.utils.AmazonSpApiInitUtils;
import com.erp.server.dmp.ErpServerDmpApplication;
import com.erp.server.dmp.service.CfgAppClientService;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Profile;
import org.springframework.test.context.junit4.SpringRunner;

import javax.annotation.Resource;
import java.util.Arrays;
import java.util.List;

/**
 * API tests for ProductPricingApi
 */
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerDmpApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@Profile("dev")
public class ProductPricingApiTest {
    @Resource
    private CfgAppClientService cfgAppClientService;


    private final ProductPricingApi api = new ProductPricingApi(null);

    
    /**
     * 
     *
     * Returns competitive pricing information for a seller&#39;s offer listings based on seller SKU or ASIN.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 1 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCompetitivePricingTest() throws ApiException {
        String marketplaceId = null;
        String itemType = null;
        List<String> asins = null;
        List<String> skus = null;
        GetPricingResponse response = api.getCompetitivePricing(marketplaceId, itemType, asins, skus);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns the lowest priced offers for a single item based on ASIN.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 1 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getItemOffersTest() throws ApiException {
        String marketplaceId = null;
        String itemCondition = null;
        String asin = null;
        GetOffersResponse response = api.getItemOffers(marketplaceId, itemCondition, asin);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns the lowest priced offers for a single SKU listing.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 1 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getListingOffersTest() throws ApiException {
        String marketplaceId = null;
        String itemCondition = null;
        String sellerSKU = null;
        GetOffersResponse response = api.getListingOffers(marketplaceId, itemCondition, sellerSKU);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns pricing information for a seller&#39;s offer listings based on seller SKU or ASIN.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 1 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPricingTest() throws ApiException {
        String marketplaceId = "A13V1IB3VIYZZH";
        String itemType = "Sku";
        List<String> asins = null;
        List<String> skus = Arrays.asList("2958-EU2");
        String itemCondition = null;
//        String sellerId = "A1FND2G4OYN01O";
//        String sku = "2958-EU2";
        String shopId = "1735512797405515786";
        // 获取店铺授权信息
        AmazonShopInfoDTO shopInfoDTO = cfgAppClientService.cacheAndFindShopAuth(shopId);
        if (null == shopInfoDTO) {
            throw new ServiceException("未找到店铺授权:" + shopId);
        }
        // 亚马逊订单下载
        ProductPricingApi api = AmazonSpApiInitUtils.create(ProductPricingApi.class, shopInfoDTO, false);

        GetPricingResponse response = api.getPricing(marketplaceId, itemType, asins, skus, itemCondition);
        System.out.println("结果");
        System.out.println(JSON.toJsonStr(response));
        // TODO: test validations
    }
    
}
