/*
 * Selling Partner API for Reports
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * OpenAPI spec version: 2021-06-30
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.erp.server.dmp.amz;

import cn.hutool.json.JSONUtil;
import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.AWSAuthenticationCredentials;
import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.AWSAuthenticationCredentialsProvider;
import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.LWAAuthorizationCredentials;
import com.erp.sdk.oms.amz.spapi.api.ReportsApi;
import com.erp.sdk.oms.amz.spapi.client.ApiException;
import com.erp.sdk.oms.amz.spapi.client.JSON;
import com.erp.sdk.oms.amz.spapi.enums.AmazonReportRecordTypeEnum;
import com.erp.sdk.oms.amz.spapi.utils.AmazonSpApiConfigUtils;
import com.erp.sdk.oms.amz.spapi.enums.AmazonMarketplaceEnum;
import com.erp.sdk.oms.amz.spapi.model.reports.*;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import com.erp.server.dmp.ErpServerDmpApplication;
import org.springframework.context.annotation.Profile;
import org.springframework.test.context.junit4.SpringRunner;
import org.junit.Test;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * API tests for ReportsApi
 */
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerDmpApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@Profile("dev")
public class ReportsApiTest {

    public ReportsApi amazonAuthorizationGrant(AmazonMarketplaceEnum marketplaceEnum, boolean isSandbox) {
        AWSAuthenticationCredentials awsAuthenticationCredentials = AmazonSpApiConfigUtils.buildAWSAuthenticationCredentials(marketplaceEnum.getEndpointsEnum());
        LWAAuthorizationCredentials lwaAuthorizationCredentials = AmazonSpApiConfigUtils.buildLWAAuthorizationCredentials();
        AWSAuthenticationCredentialsProvider awsAuthenticationCredentialsProvider = AmazonSpApiConfigUtils.buildAWSAuthenticationCredentialsProvider();
        ReportsApi reportApi = new ReportsApi.Builder()
                .awsAuthenticationCredentials(awsAuthenticationCredentials)
                .lwaAuthorizationCredentials(lwaAuthorizationCredentials)
                .awsAuthenticationCredentialsProvider(awsAuthenticationCredentialsProvider)
                //注意，这里的endpoint分北美，欧洲，远东三个地域，每个区域的链接是不一样的
                //北美，https://sellingpartnerapi-na.amazon.com
                //欧洲，https://sellingpartnerapi-eu.amazon.com
                //远东，https://sellingpartnerapi-fe.amazon.com
                .endpoint(isSandbox ? marketplaceEnum.getEndpointsEnum().getEndpointsByProfile() : marketplaceEnum.getEndpointsEnum().getEndpoints())
                .build();
        if (null == reportApi) {
            throw new RuntimeException("授权失败，未获取到API实例的话抛出异常，进行重试");
        }
        return reportApi;
    }

    /**
     * Cancels the report that you specify. Only reports with processingStatus&#x3D;IN_QUEUE can be cancelled. Cancelled reports are returned in subsequent calls to the getReport and getReports operations.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 0.0222 | 10 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cancelReportTest() throws ApiException {
        String reportId = null;
        ReportsApi api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US, true);
        api.cancelReport(reportId);

        // TODO: test validations
    }

    /**
     * Cancels the report schedule that you specify.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 0.0222 | 10 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cancelReportScheduleTest() throws ApiException {
        // 正式环境参数
//        String reportScheduleId = "50003019648";
//        String reportScheduleId = "50004019668";
//        String reportScheduleId = "50007019671";
//        String reportScheduleId = "50006019671";
        String reportScheduleId = "50005019671";
        ReportsApi api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US, false);
        api.cancelReportSchedule(reportScheduleId);

        // TODO: test validations
    }

    /**
     * Creates a report.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 0.0167 | 15 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createReportTest() throws ApiException {
        CreateReportSpecification body = new CreateReportSpecification();
//        body.setReportType("GET_MERCHANT_LISTINGS_DATA");
//        body.setReportType("GET_MERCHANT_LISTINGS_ALL_DATA");
//        body.setMarketplaceIds(Arrays.asList("A1AM78C64UM0Y8"));

        // 亚马逊物流管理库存 - 已存档
//        body.setReportType("GET_FBA_MYI_ALL_INVENTORY_DATA");
        // 亚马逊物流预留库存报告
//        body.setReportType("GET_RESERVED_INVENTORY_DATA");
        // 亚马逊物流管理库存状况报告
        body.setReportType("GET_FBA_INVENTORY_PLANNING_DATA");
        body.setMarketplaceIds(Arrays.asList("ATVPDKIKX0DER"));
        ReportsApi api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US, false);
        CreateReportResponse response = api.createReport(body);
        System.out.println("创建报告");
        System.out.println(JSONUtil.toJsonStr(response));

        // 亚马逊物流管理库存{"reportId":"724464019664"}
        // 亚马逊库存库龄报告{"reportId":"724476019664"}
        // 亚马逊库存库龄报告{"reportId":"728730019671"}
        // 亚马逊物流预留库存报告{"reportId":"724489019664"}
        // 亚马逊物流管理库存状况报告{"reportId":"724480019664"}
        // 亚马逊物流管理库存状况报告{"reportId":"727590019669"}
        // 亚马逊物流管理库存状况报告{"reportId":"727635019669"}
        // TODO: test validations
        // Listing {"reportId":"727614019669"}
    }

    /**
     * Creates a report schedule. If a report schedule with the same report type and marketplace IDs already exists, it will be cancelled and replaced with this one.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 0.0222 | 10 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createReportScheduleTest() throws ApiException {
        CreateReportScheduleSpecification body = new CreateReportScheduleSpecification();

        // 正式环境参数
//        body.setReportType("GET_MERCHANT_LISTINGS_DATA");
//        body.setMarketplaceIds(Arrays.asList("A1AM78C64UM0Y8"));
//        body.setNextReportCreationTime("2023-10-18T03:00:00.000Z");
//        body.setPeriod(CreateReportScheduleSpecification.PeriodEnum.PT1H);
        body.setReportType("GET_FBA_INVENTORY_PLANNING_DATA");
        body.setMarketplaceIds(Arrays.asList("ATVPDKIKX0DER"));
        body.setNextReportCreationTime("2023-11-11T00:00:00.000Z");
        body.setPeriod(CreateReportScheduleSpecification.PeriodEnum.P2D);
        // 沙箱参数
//        body.setReportType("FEE_DISCOUNTS_REPORT");
//        body.setPeriod(CreateReportScheduleSpecification.PeriodEnum.PT5M);
//        String time = "2019-12-10T20:11:24.000Z";
//        body.setNextReportCreationTime(time);
//        body.setMarketplaceIds(Arrays.asList("A1PA6795UKMFR9","ATVPDKIKX0DER"));
        ReportsApi api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US, false);
        CreateReportScheduleResponse response = api.createReportSchedule(body);
        System.out.println("创建自动更新报告");
        System.out.println(JSONUtil.toJsonStr(response));
        // {"reportScheduleId":"50002019648"}
        // {"reportScheduleId":"50004019668"}
        // TODO: test validations
    }

    /**
     * Returns report details (including the reportDocumentId, if available) for the report that you specify.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2.0 | 15 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getReportTest() throws ApiException {
        // 沙箱环境参数
//        String reportId = "ID323";
        // 正式环境参数
//        String reportId = "716008019646";
        // 亚马逊物流管理库存{"reportId":"724464019664"}
//        String reportId = "724464019664";
        String reportId = "727635019669";
        // 亚马逊物流管理库存状况报告{"reportId":"724480019664"}
//        String reportId = "724480019664";
        // 亚马逊物流预留库存报告{"reportId":"724489019664"}
//        String reportId = "724489019664";
        ReportsApi api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US, false);
        Report response = api.getReport(reportId);
        System.out.println("获取报告");
        System.out.println(JSON.toJsonStr(response));
        // {"marketplaceIds":["ATVPDKIKX0DER"],"reportId":"724464019664","reportType":"GET_FBA_MYI_ALL_INVENTORY_DATA","dataStartTime":1698972068000,"dataEndTime":1698972068000,"createdTime":1698972068000,"processingStatus":"DONE","processingStartTime":1698972074000,"processingEndTime":1698972085000,"reportDocumentId":"amzn1.spdoc.1.4.na.c92cf4e4-7473-47c1-8bf5-7d201a147570.T157CJXNIMCGN5.2650"}

        // {"marketplaceIds":["ATVPDKIKX0DER"],"reportId":"724480019664","reportType":"GET_FBA_INVENTORY_PLANNING_DATA","dataStartTime":1698974243000,"dataEndTime":1698974243000,"createdTime":1698974243000,"processingStatus":"DONE","processingStartTime":1698974250000,"processingEndTime":1698974262000,"reportDocumentId":"amzn1.spdoc.1.4.na.534c50b5-5a71-41e5-ab3f-8b569d68a0e0.T2OKFOUSONXBF0.19600"}

        // {"marketplaceIds":["ATVPDKIKX0DER"],"reportId":"724489019664","reportType":"GET_RESERVED_INVENTORY_DATA","dataStartTime":1698975699000,"dataEndTime":1698975699000,"createdTime":1698975699000,"processingStatus":"DONE","processingStartTime":1698975706000,"processingEndTime":1698975719000,"reportDocumentId":"amzn1.spdoc.1.4.na.3f9ae729-3c81-4962-8337-70773b6650ed.T23ILE2UF410OH.2681"}

        // {"marketplaceIds":["ATVPDKIKX0DER"],"reportId":"727635019669","reportType":"GET_RESERVED_INVENTORY_DATA","dataStartTime":"2023-11-08T08:29:26Z","dataEndTime":"2023-11-08T08:29:26Z","createdTime":"2023-11-08T08:29:26Z","processingStatus":"DONE","processingStartTime":"2023-11-08T08:29:33Z","processingEndTime":"2023-11-08T08:29:44Z","reportDocumentId":"amzn1.spdoc.1.4.na.18f1e850-6241-49b5-b63a-06454c34636b.T28BAFXFYWABBZ.2681"}
        // TODO: test validations
    }

    /**
     * Returns the information required for retrieving a report document&#39;s contents.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 0.0167 | 15 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getReportDocumentTest() throws ApiException {
        // 正式环境参数
//        String reportDocumentId = "amzn1.spdoc.1.4.na.584baa05-f1b8-4d53-88fc-5c5b32051236.T2SXAUMO86QN6T.300";
        // 亚马逊物流管理库存
        String reportDocumentId = "amzn1.spdoc.1.4.na.c92cf4e4-7473-47c1-8bf5-7d201a147570.T157CJXNIMCGN5.2650";
        // 亚马逊物流管理库存状况报告
//        String reportDocumentId = "amzn1.spdoc.1.4.na.534c50b5-5a71-41e5-ab3f-8b569d68a0e0.T2OKFOUSONXBF0.19600";
        // 亚马逊物流预留库存报告
//        String reportDocumentId = "amzn1.spdoc.1.4.na.3f9ae729-3c81-4962-8337-70773b6650ed.T23ILE2UF410OH.2681";
        // 沙箱环境参数
//        String reportDocumentId = "0356cf79-b8b0-4226-b4b9-0ee058ea5760";
        ReportsApi api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US, false);
        ReportDocument response = api.getReportDocument(reportDocumentId);

        System.out.println("报告文档");
        System.out.println(JSONUtil.toJsonStr(response));
        // 亚马逊物流管理库存
        // {"reportDocumentId":"amzn1.spdoc.1.4.na.c92cf4e4-7473-47c1-8bf5-7d201a147570.T157CJXNIMCGN5.2650","url":"https://tortuga-prod-na.s3-external-1.amazonaws.com/2a2d3258-3b23-4f23-8eb6-c019f45bab25.amzn1.tortuga.4.na.T1507HA60E8SWN?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231103T004815Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=AKIA5U6MO6RAETTDXOQT%2F20231103%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=c3e2ede4089507b180769c7d0459665988e9cf4f4f5730c01a1a2468094de64d"}

        // 亚马逊物流管理库存状况报告
        // {"reportDocumentId":"amzn1.spdoc.1.4.na.534c50b5-5a71-41e5-ab3f-8b569d68a0e0.T2OKFOUSONXBF0.19600","url":"https://tortuga-prod-na.s3-external-1.amazonaws.com/a19570c6-30f3-4bf1-b21a-0e4c366cc9d8.amzn1.tortuga.4.na.T1SJJIE84P543J?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231103T013522Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=AKIA5U6MO6RAETTDXOQT%2F20231103%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=21578a95a6409a4408d23b517916174b67bac17feb3aafd7e1c3be180c83a8c1"}
        // {"reportDocumentId":"amzn1.spdoc.1.4.na.534c50b5-5a71-41e5-ab3f-8b569d68a0e0.T2OKFOUSONXBF0.19600","url":"https://tortuga-prod-na.s3-external-1.amazonaws.com/a19570c6-30f3-4bf1-b21a-0e4c366cc9d8.amzn1.tortuga.4.na.T1SJJIE84P543J?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231106T041213Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=AKIA5U6MO6RAETTDXOQT%2F20231106%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=f073b581da98440bde014d11814991861d8d5aeaed5abfcc7790cac93d5d9702"}
        // {"reportDocumentId":"amzn1.spdoc.1.4.na.534c50b5-5a71-41e5-ab3f-8b569d68a0e0.T2OKFOUSONXBF0.19600","url":"https://tortuga-prod-na.s3-external-1.amazonaws.com/a19570c6-30f3-4bf1-b21a-0e4c366cc9d8.amzn1.tortuga.4.na.T1SJJIE84P543J?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231106T042355Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=AKIA5U6MO6RAETTDXOQT%2F20231106%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=e2e046a268f65fef133d6f47477d1a108df4cb4c8420035ca81e89660335278c"}

        // 亚马逊物流预留库存报告
        // {"reportDocumentId":"amzn1.spdoc.1.4.na.3f9ae729-3c81-4962-8337-70773b6650ed.T23ILE2UF410OH.2681","url":"https://tortuga-prod-na.s3-external-1.amazonaws.com/f36c2976-2253-451b-bb3d-e6e47a43ffca.amzn1.tortuga.4.na.TUE3ZIC1NB3GN?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231103T014513Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=AKIA5U6MO6RAETTDXOQT%2F20231103%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=4d70013cd08b5ef7b76a2fa0fad6fd05667e4f2e5a99aeab70502d2cec59085c"}
        // {"reportDocumentId":"amzn1.spdoc.1.4.na.3f9ae729-3c81-4962-8337-70773b6650ed.T23ILE2UF410OH.2681","url":"https://tortuga-prod-na.s3-external-1.amazonaws.com/f36c2976-2253-451b-bb3d-e6e47a43ffca.amzn1.tortuga.4.na.TUE3ZIC1NB3GN?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231106T035045Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=AKIA5U6MO6RAETTDXOQT%2F20231106%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=6917ebea79e4002c53e43a9fafee2e6889f462e25bbf3f9d7f93bffde5dba47d"}


        // TODO: test validations
    }

    /**
     * Returns report schedule details for the report schedule that you specify.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 0.0222 | 10 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getReportScheduleTest() throws ApiException {
        // 沙箱参数
//        String reportScheduleId = "ID323";
        // 正式环境参数
        String reportScheduleId = "50002019648";
        ReportsApi api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US, false);
        ReportSchedule response = api.getReportSchedule(reportScheduleId);
        System.out.println("getReportScheduleTest");
        System.out.println(JSONUtil.toJsonStr(response));
        // {"reportScheduleId":"ReportScheduleId1","reportType":"FEE_DISCOUNTS_REPORT","period":"PT5M","nextReportCreationTime":1576158440677}
        // {"reportScheduleId":"50002019648","reportType":"GET_MERCHANT_LISTINGS_DATA","marketplaceIds":["A1AM78C64UM0Y8"],"period":"PT1H","nextReportCreationTime":"2023-10-18T10:45:00+00:00"}
        // TODO: test validations
    }

    /**
     * Returns report schedule details that match the filters that you specify.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 0.0222 | 10 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getReportSchedulesTest() throws ApiException {
//        List<String> reportTypes = Arrays.asList("GET_MERCHANT_LISTINGS_DATA");
        List<String> reportTypes = Stream.of(AmazonReportRecordTypeEnum.values())
                .map(AmazonReportRecordTypeEnum::getRecordType)
                .collect(Collectors.toList());

        ReportsApi api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US, false);
        ReportScheduleList response = api.getReportSchedules(reportTypes);
        System.out.println("getReportSchedulesTest");
        System.out.println(JSON.toJsonStr(response));
        // {"reportSchedules":[{"reportScheduleId":"50003019648","reportType":"GET_MERCHANT_LISTINGS_DATA","marketplaceIds":["A1AM78C64UM0Y8"],"period":"PT1H","nextReportCreationTime":"2023-10-18T04:06:25Z"}]}
        // TODO: test validations
        // {"reportSchedules":[{"reportScheduleId":"50007019671","reportType":"GET_MERCHANT_LISTINGS_DATA","marketplaceIds":["ATVPDKIKX0DER"],"period":"PT15M","nextReportCreationTime":"2023-11-22T02:58:30Z"}]}
        // {"reportSchedules":[{"reportScheduleId":"50001018714","reportType":"GET_FBA_MYI_ALL_INVENTORY_DATA","period":"PT24H","nextReportCreationTime":"2023-11-22T16:00:00Z"},{"reportScheduleId":"50006019671","reportType":"GET_RESERVED_INVENTORY_DATA","marketplaceIds":["ATVPDKIKX0DER"],"period":"PT15M","nextReportCreationTime":"2023-11-22T03:00:00Z"},{"reportScheduleId":"50005019671","reportType":"GET_FBA_MYI_ALL_INVENTORY_DATA","marketplaceIds":["ATVPDKIKX0DER"],"period":"PT15M","nextReportCreationTime":"2023-11-22T03:00:00Z"}]}
    }

    /**
     * Returns report details for the reports that match the filters that you specify.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 0.0222 | 10 |  For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getReportsTest() throws Exception {
        List<String> reportTypes = Arrays.asList("GET_MERCHANT_LISTINGS_DATA");
//        List<String> reportTypes = Arrays.asList("GET_FBA_MYI_ALL_INVENTORY_DATA");
//        List<String> reportTypes = Arrays.asList("GET_FBA_MYI_ALL_INVENTORY_DATA");
//        List<String> reportTypes = Arrays.asList(AmazonReportRecordTypeEnum.GET_MERCHANT_LISTINGS_DATA.getRecordType());
        List<String> processingStatuses = null;
        List<String> marketplaceIds = null;
        Integer pageSize = 100;
        String createdSince = null;
        String createdUntil = null;
        String nextToken = null;
        ReportsApi api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US, false);
        GetReportsResponse response = api.getReports(reportTypes, processingStatuses, marketplaceIds, pageSize, createdSince, createdUntil, nextToken);
        System.out.println("getReportsTest");
        System.out.println(JSON.toJsonStr(response));
        // TODO: test validations
    }

}
