/*
 * Selling Partner API for Sellers
 * The Selling Partner API for Sellers lets you retrieve information on behalf of sellers about their seller account, such as the marketplaces they participate in. Along with listing the marketplaces that a seller can sell in, the API also provides additional information about the marketplace such as the default language and the default currency. The API also provides seller-specific information such as whether the seller has suspended listings in that marketplace.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.erp.server.dmp.amz;

import cn.hutool.core.util.StrUtil;
import com.common.core.utils.StrUtils;
import com.erp.sdk.oms.amz.spapi.documents.DownloadHandler;
import com.erp.server.dmp.ErpServerDmpApplication;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Profile;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;


/**
 * API tests for DownloadParseCsv
 */
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerDmpApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@Profile("dev")
public class ReportDownloadFastDFSAndGenCfgTest {


    @Test
    public void genCfgReportFieldByTitleFromFilePath() {
        // 报告下载的路径
        String filePath = "group1/M00/52/43/rBBkDGckLvqAYPHPAAARxhnc_M0.T21BZK";
        // 配置开始的ID号
//        Long id = 1691000000000000000L;
        Long id = null;
        // 配置报告的下载类型
        String recordType = "GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_REPLACEMENT_DATA";

        String url = "";
        String compressionAlgorithm = "";
        // url 解析

        Set<String> columnName = null;
        try {
            // FastDFS 解析
            columnName = DownloadHandler.getReportTitleFromFilePath(filePath);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        printlnSql(columnName, id, recordType);
    }

    @Test
    public void genCfgReportFieldByUrl() {
        // 报告下载的路径
        String url = "https://tortuga-prod-na.s3-external-1.amazonaws.com/6d8e6985-ac6e-46ea-9d49-e175cffcb5e6.amzn1.tortuga.4.na.T21BZKD35Q9EIF?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241101T012015Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=AKIA5U6MO6RACOWQRBEF%2F20241101%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=9f211b52776cbca674e55eb38f8cb48bf0ba815b573953038439aa204c6075a4";
        // 配置开始的ID号 (null == 按函数 snow_next_id())
//        Long id = 1691000000000000000L;
        Long id = null;
        // 配置报告的下载类型
        String recordType = "GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_REPLACEMENT_DATA";
        // 来源报告压缩方式=按报告信息提供
        String compressionAlgorithm = "text";
        // url 解析
        Set<String> columnName = null;
        try {
            // FastDFS 解析
            columnName = DownloadHandler.getReportTitleFromUrl(url, compressionAlgorithm);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        printlnSql(columnName, id, recordType);

    }


    private static void printlnSql(Set<String> columnName, Long id, String recordType) {
        LinkedHashMap<String, String> hashMap = new LinkedHashMap<>();
        for (String s : columnName) {
            System.out.println(s);
        }

        System.out.println("每个字段信息结束=====");
        System.out.println("每个字段驼峰信息开始=====");
        for (String s : columnName) {
            if (s.contains("-")) {
                String camelStr = StrUtils.underlineToCamel(s, true);
                hashMap.put(s, camelStr);
                System.out.println(camelStr);
            } else if (s.contains(" ")){
                String camelStr = StrUtils.underlineToCamel(s, true);
                hashMap.put(s, camelStr);
                System.out.println(camelStr);
            } else {
                hashMap.put(s, s);
            }
        }
        System.out.println("每个字段驼峰信息结束=====");
//        Long id= 1680776062189170030L;
//        String recordType = "GET_MERCHANT_LISTINGS_DATA";
//        Long id= 140000000000000000L;
//        String recordType = "GET_RESERVED_INVENTORY_DATA";
//        Long id= 130000000000000000L;
//        String recordType = "GET_FBA_INVENTORY_PLANNING_DATA";


        for (Map.Entry<String, String> entry : hashMap.entrySet()) {
            String sqlStr = "";
            String idStr = null == id ? "snow_next_id()" : id.toString();
            if (null == id) {
                sqlStr = "INSERT INTO \"public\".\"cfg_amz_report_field\"  (\"id\",\"remark\", \"column_name\", \"field_name\", \"report_type\", \"status\") VALUES  ({},'','{}','{}', '{}', 't');";
            } else {
                sqlStr = "INSERT INTO \"public\".\"cfg_amz_report_field\"  (\"id\",\"remark\", \"column_name\", \"field_name\", \"report_type\", \"status\") VALUES  ('{}','','{}','{}', '{}', 't');";
            }
            String currentSql = StrUtil.format(sqlStr, idStr, entry.getKey(), entry.getValue(), recordType);
            System.out.println(currentSql);
            if (null != id){
                id++;
            }
        }
    }

}
