/*
 * Selling Partner API for Shipment Invoicing
 * The Selling Partner API for Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s Fulfillment by Amazon (FBA) orders.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.erp.server.dmp.amz;

import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.AWSAuthenticationCredentials;
import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.AWSAuthenticationCredentialsProvider;
import com.erp.sdk.oms.amz.spapi.SellingPartnerAPIAA.LWAAuthorizationCredentials;
import com.erp.sdk.oms.amz.spapi.api.ListingsRestrictionsApi;
import com.erp.sdk.oms.amz.spapi.api.ShipmentInvoiceApi;
import com.erp.sdk.oms.amz.spapi.client.ApiException;
import com.erp.sdk.oms.amz.spapi.utils.AmazonSpApiConfigUtils;
import com.erp.sdk.oms.amz.spapi.enums.AmazonMarketplaceEnum;
import com.erp.sdk.oms.amz.spapi.model.listingsrestrictions.RestrictionList;
import com.erp.sdk.oms.amz.spapi.model.shipmentinvoicing.GetInvoiceStatusResponse;
import com.erp.sdk.oms.amz.spapi.model.shipmentinvoicing.GetShipmentDetailsResponse;
import com.erp.sdk.oms.amz.spapi.model.shipmentinvoicing.SubmitInvoiceRequest;
import com.erp.sdk.oms.amz.spapi.model.shipmentinvoicing.SubmitInvoiceResponse;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import com.erp.server.dmp.ErpServerDmpApplication;
import org.springframework.context.annotation.Profile;
import org.springframework.test.context.junit4.SpringRunner;
import org.junit.Test;

import java.util.List;


/**
 * API tests for ShipmentInvoiceApi
 */
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerDmpApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@Profile("dev")
public class ShipmentInvoiceApiTest {

    private final ShipmentInvoiceApi api = amazonAuthorizationGrant(AmazonMarketplaceEnum.US);

    public ShipmentInvoiceApi amazonAuthorizationGrant(AmazonMarketplaceEnum marketplaceEnum) {
//        AWSAuthenticationCredentials awsAuthenticationCredentials = AmazonSpApiConfigUtils.buildAWSAuthenticationCredentials(marketplaceEnum.getEndpointsEnum());
//        LWAAuthorizationCredentials lwaAuthorizationCredentials = AmazonSpApiConfigUtils.buildLWAAuthorizationCredentials();
//        AWSAuthenticationCredentialsProvider awsAuthenticationCredentialsProvider = AmazonSpApiConfigUtils.buildAWSAuthenticationCredentialsProvider();
//        ShipmentInvoiceApi shipmentInvoiceApi = new ShipmentInvoiceApi.Builder()
//                .awsAuthenticationCredentials(awsAuthenticationCredentials)
//                .lwaAuthorizationCredentials(lwaAuthorizationCredentials)
//                .awsAuthenticationCredentialsProvider(awsAuthenticationCredentialsProvider)
//                //注意，这里的endpoint分北美，欧洲，远东三个地域，每个区域的链接是不一样的
//                //北美，https://sellingpartnerapi-na.amazon.com
//                //欧洲，https://sellingpartnerapi-eu.amazon.com
//                //远东，https://sellingpartnerapi-fe.amazon.com
//                .endpoint(marketplaceEnum.getEndpointsEnum().getEndpointsByProfile())
//                .build();
//        if (null == shipmentInvoiceApi) {
//            throw new RuntimeException("授权失败，未获取到API实例的话抛出异常，进行重试");
//        }
//        return shipmentInvoiceApi;
        return null;
    }

    /**
     * 
     *
     * Returns the invoice status for the shipment you specify.  **Usage Plans:**  | Plan type | Rate (requests per second) | Burst | | ---- | ---- | ---- | |Default| 1.133 | 25 | |Selling partner specific| Variable | Variable |  The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInvoiceStatusTest() throws ApiException {
        String shipmentId = null;
        GetInvoiceStatusResponse response = api.getInvoiceStatus(shipmentId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns the shipment details required to issue an invoice for the specified shipment.  **Usage Plans:**  | Plan type | Rate (requests per second) | Burst | | ---- | ---- | ---- | |Default| 1.133 | 25 | |Selling partner specific| Variable | Variable |  The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getShipmentDetailsTest() throws ApiException {
        String shipmentId = null;
        GetShipmentDetailsResponse response = api.getShipmentDetails(shipmentId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Submits a shipment invoice document for a given shipment.  **Usage Plans:**  | Plan type | Rate (requests per second) | Burst | | ---- | ---- | ---- | |Default| 1.133 | 25 | |Selling partner specific| Variable | Variable |  The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void submitInvoiceTest() throws ApiException {
        String shipmentId = null;
        SubmitInvoiceRequest body = null;
        SubmitInvoiceResponse response = api.submitInvoice(shipmentId, body);

        // TODO: test validations
    }

    /**
     * API tests for ListingsApi
     */
    @RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerDmpApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@Profile("dev")
    public static class ListingsRestrictionsApiTest {

        private final ListingsRestrictionsApi api = new ListingsRestrictionsApi();


        /**
         *
         *
         * Returns listing restrictions for an item in the Amazon Catalog.   **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 5 | 10 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
         *
         * @throws ApiException
         *          if the Api call fails
         */
        @Test
        public void getListingsRestrictionsTest() throws ApiException {
            String asin = null;
            String sellerId = null;
            List<String> marketplaceIds = null;
            String conditionType = null;
            String reasonLocale = null;
            RestrictionList response = api.getListingsRestrictions(asin, sellerId, marketplaceIds, conditionType, reasonLocale);

            // TODO: test validations
        }

    }
}
