/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * OpenAPI spec version: 2024-05-09
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.erp.sdk.oms.amz.spapi.model.awd;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.erp.sdk.oms.amz.spapi.model.awd.DistributionPackageQuantity;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Represents the packages to inbound.
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-16T16:01:04.182857+08:00[Asia/Shanghai]")

public class InboundPackages {
  @SerializedName("packagesToInbound")
  private List<DistributionPackageQuantity> packagesToInbound = new ArrayList<DistributionPackageQuantity>();

  public InboundPackages packagesToInbound(List<DistributionPackageQuantity> packagesToInbound) {
    this.packagesToInbound = packagesToInbound;
    return this;
  }

  public InboundPackages addPackagesToInboundItem(DistributionPackageQuantity packagesToInboundItem) {
    this.packagesToInbound.add(packagesToInboundItem);
    return this;
  }

   /**
   * List of packages to be inbounded.
   * @return packagesToInbound
  **/
  
  public List<DistributionPackageQuantity> getPackagesToInbound() {
    return packagesToInbound;
  }

  public void setPackagesToInbound(List<DistributionPackageQuantity> packagesToInbound) {
    this.packagesToInbound = packagesToInbound;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InboundPackages inboundPackages = (InboundPackages) o;
    return Objects.equals(this.packagesToInbound, inboundPackages.packagesToInbound);
  }

  @Override
  public int hashCode() {
    return Objects.hash(packagesToInbound);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InboundPackages {\n");
    
    sb.append("    packagesToInbound: ").append(toIndentedString(packagesToInbound)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
