package com.erp.model.dmp.mabang;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

@Data
@NoArgsConstructor
@ToString
public class OrderEntity {

    private String _id;
    private String platformOrderId;
    private String salesRecordNumber;
    private Integer orderStatus;
    private Integer myLogisticsChannelId;
    private String trackNumber;
    private String trackNumber1;
    private String trackNumber2;
    private String orderWeight;
    private String buyerUserId;
    private String buyerName;
    private String shopId;
    private String companyId;
    private String countryCode;
    private BigDecimal orderCost;
    private String transportTime;
    private String quickPickTime;
    private Integer canSend;
    private String createDate;
    private Integer isReturned;
    private Integer isRefund;
    private String paidTime;

    private BigDecimal orderFee;
    private String platformId;
    private String expressTime;
    private Integer isUnion;
    private Integer isSplit;
    private Integer isResend;
    private Integer hasGoods;
    private String hasBattery;
    private String isSyncLogisticsDescr;
    private String paypalId;
    private String isSyncLogistics;
    private String isSyncPlatform;
    private String isSyncPlatformDescr;
    private String district;
    private String paypalEmail;
    private String closeDate;
    private String street1;
    private String street2;
    private String isVirtual;
    private String city;
    private String province;
    private String postCode;
    private String phone1;
    private String phone2;
    private String email;
    private String isNewOrder;
    private String doorcode;
    private Integer fbaFlag;
    private String fbaStartDateTime;
    private String fbaEndDateTime;
    private String CarrierCode;
    private String operTime;
    private String shippingService;
    private String packageWeight;
    private String platformOrderStatus;
    private String hasMagnetic;
    private String hasPowder;
    private String hasTort;
    private String remark;
    private String sellerMessage;
    private String currencyId;
    private BigDecimal currencyRate;
    private BigDecimal itemTotal;
    private BigDecimal shippingFee;
    private BigDecimal platformFee;
    private BigDecimal shippingTotalOrigin;
    private BigDecimal itemTotalOrigin;
    private String refundFeeOrigin;
    private String refundFeeCurrencyId;
    private String originFax;
    private String beforeStatus;
    private String otherExpend;
    private String otherIncome;
    private String insuranceFee;
    private String insuranceFeeOrigin;
    private String paypalFee;
    private String paypalFeeOrigin;
    private BigDecimal itemTotalCost;
    private String shippingCost;
    private String shippingPreCost;
    private String packageFee;
    private String fbaPerOrderFulfillmentFee;
    private String fbaCommission;
    private String promotionAmount;
    private String allianceFeeOrigin;
    private String voucherPriceOrigin;
    private String subsidyAmountOrigin;
    private String CODCharge;
    private String allianceFee;
    private String ShippingChargeback;
    private String fbaPerUnitFulfillmentFee;
    private String fbaWeightBasedFee;
    private String platformFeeOrigin;
    private String voucherPrice;
    private BigDecimal subsidyAmount;
    private String isWms;
    private String payType;
    private String VendorID;
    private String abnnumber;
    private String countryNameEN;
    private String countryNameCN;
    private String shopName;
    private String myLogisticsChannelName;
    private String myLogisticsId;
    private String myLogisticsName;
    private String orderType;
    private String erpOrderId;
    private String shippingWeight;
    private List<OrderItemEntity> orderItem;
    private String extendAttr;
}
