# 当前使用的 账套ID(即数据中心id)
# 第三方系统登录授权的账套ID（即open.kingdee.com网站的第三方系统登录授权中的数据中心标识）
# 在第三方系统登录授权页面点击“生成测试链接”按钮后即可查看
X-KDApi-AcctID = 604578a4a54a6f

# 第三方系统登录授权的 集成用户名称
# 补丁版本为PT-146894 [7.7.0.202111]及后续的版本，则为指定用户登录列表中任一用户
# 若第三方系统登录授权已勾选“允许全部用户登录”，则无以上限制
X-KDApi-UserName = 瞿育忠

# 第三方系统登录授权的应用ID
X-KDApi-AppID = 237496_016p4bjt3qA/S4Xv2Z0r77+M5N781AMo

# 第三方系统登录授权的应用密钥
X-KDApi-AppSec = 46a860e5bcd144848bc9394c9c4dfbfa

# 账套语系，默认2052
# X-KDApi-LCID = 2052

# 组织编码，启用多组织时配置对应的组织编码才有效
# X-KDApi-OrgNum = *******

# 服务Url地址(公有云无需配置，私有云需要配置金蝶云星空产品地址，K3Cloud/结尾)
X-KDApi-ServerUrl = http://47.106.224.95:8089/k3cloud/