<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.cloud.erp</groupId>
        <artifactId>erp-server</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.erp.server</groupId>
    <artifactId>erp-server-scm</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>erp-server-scm</name>
    <description>供应链系统</description>

    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <!--公共服务-->

        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-model-sys</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <!--公共服务结束-->

        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-common-message</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>


        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>${alibaba.druid.verison}</version>
        </dependency>
        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-model-scm</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-model-wms</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-rpc-sys</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-rpc-dmp</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-rpc-wms</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-rpc-workflow</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-rpc-plm</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-rpc-oms</artifactId>
            <version>0.0.1-SNAPSHOT</version>



            <scope>compile</scope>
        </dependency>

    </dependencies>

    <profiles>
        <profile>
            <id>dev</id>
            <properties>
                <repository.id>snapshot-test</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-test/</repository.url>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>test</id>
            <properties>
                <repository.id>snapshot-test</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-test/</repository.url>
            </properties>
        </profile>
        <profile>
            <id>uat</id>
            <properties>
                <repository.id>snapshot-prod</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-prod/</repository.url>
            </properties>
        </profile>
        <profile>
            <id>prod</id>
            <properties>
                <repository.id>snapshot-prod</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-prod/</repository.url>
            </properties>
        </profile>
    </profiles>
    <distributionManagement>
        <snapshotRepository>
            <id>${repository.id}</id>
            <url>${repository.url}</url>
        </snapshotRepository>
    </distributionManagement>

    <build>
        <finalName>${project.name}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
