/*
 * Selling Partner API for Tokens
 * The Selling Partner API for Tokens provides a secure way to access a customer's PII (Personally Identifiable Information). You can call the Tokens API to get a Restricted Data Token (RDT) for one or more restricted resources that you specify. The RDT authorizes subsequent calls to restricted operations that correspond to the restricted resources that you specified.  For more information, see the [Tokens API Use Case Guide](doc:tokens-api-use-case-guide).
 *
 * OpenAPI spec version: 2021-03-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.erp.server.dmp.wdt;

import cn.hutool.json.JSONUtil;
import com.common.core.utils.BeanMapperUtils;
import com.erp.server.dmp.ErpServerDmpApplication;
import com.sdk.wangdian.dto.WdtVirtualWarehouseDto;
import com.sdk.wangdian.sdk.Pager;
import com.sdk.wangdian.sdk.api.setting.SettingAPI;
import com.sdk.wangdian.sdk.api.setting.dto.VirtualWarehouseQueryRequest;
import com.sdk.wangdian.sdk.api.setting.dto.VirtualWarehouseQueryResponse;
import com.sdk.wangdian.server.WangDianClientService;
import lombok.extern.slf4j.Slf4j;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Profile;
import org.springframework.test.context.junit4.SpringRunner;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 *
 */
@Slf4j
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerDmpApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@Profile("dev")
public class WdtSdkTest {

    @Test
    public void virtualWarehouseTest() throws Exception{
        VirtualWarehouseQueryRequest query = new VirtualWarehouseQueryRequest();

        Pager pager = new Pager();
        pager.setPageNo(0);
        pager.setPageSize(100);
        pager.setCalcTotal(true);
        query.setStartTime(LocalDateTime.now().minusDays(30).format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
        query.setEndTime(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));

        WangDianClientService clientService = null;
//        WangDianClientService clientService = new WangDianClientService();


        SettingAPI settingAPI = clientService.get(SettingAPI.class);
        List<VirtualWarehouseQueryResponse.VirtualWarehouseDto> warehouseList = new ArrayList<>();
        boolean hasNext = true;
        int pageSize = 200;

        //分页循环拉取数据
        while (hasNext) {
            VirtualWarehouseQueryResponse response = null;
            try {
                response = settingAPI.queryVirtualWarehouse(query, pager);
            } catch (Exception e) {
                log.error("拉取旺店通虚拟仓数据失败，原因【{}】", e.getMessage(), e);
                List<WdtVirtualWarehouseDto> wdtVirtualWarehouseDtos = BeanMapperUtils.copyList(WdtVirtualWarehouseDto.class, warehouseList);
            }
            if (response == null || response.getVirtualWarehouseList().isEmpty()) {
                List<WdtVirtualWarehouseDto> wdtVirtualWarehouseDtos = BeanMapperUtils.copyList(WdtVirtualWarehouseDto.class, warehouseList);
                System.out.println(JSONUtil.toJsonStr(wdtVirtualWarehouseDtos));
            }
            System.out.println(JSONUtil.toJsonStr(response.getVirtualWarehouseList()));
            warehouseList.addAll(response.getVirtualWarehouseList());
            Integer totalCount = response.getTotal();
            if (totalCount <= (pager.getPageNo() + 1) * pageSize) {
                hasNext = false;
            }
            pager.setPageNo(pager.getPageNo() + 1);
        }
    }
}