<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.10.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.cloud</groupId>
    <artifactId>erp-gateway</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>erp-gateway</name>
    <description>Api 网关服务</description>
    <properties>
        <java.version>1.8</java.version>
        <spring-cloud.version>Hoxton.SR11</spring-cloud.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <alibaba.druid.verison>1.2.15</alibaba.druid.verison>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-model-sys</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-web</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <profiles>
        <profile>
            <id>dev</id>
            <properties>
                <repository.id>snapshot-test</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-test/</repository.url>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>test</id>
            <properties>
                <repository.id>snapshot-test</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-test/</repository.url>
            </properties>
        </profile>
        <profile>
            <id>uat</id>
            <properties>
                <repository.id>snapshot-prod</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-prod/</repository.url>
            </properties>
        </profile>
        <profile>
            <id>prod</id>
            <properties>
                <repository.id>snapshot-prod</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-prod/</repository.url>
            </properties>
        </profile>
    </profiles>
    <distributionManagement>
        <snapshotRepository>
            <id>${repository.id}</id>
            <url>${repository.url}</url>
        </snapshotRepository>
    </distributionManagement>

    <build>
        <finalName>${project.name}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
