<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <groupId>com.cloud.erp</groupId>
        <artifactId>erp-server</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.erp.server</groupId>
    <artifactId>erp-server-admin</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>erp-server-admin</name>
    <description>管理后台服务</description>

    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!--忽略测试-->
        <maven.test.skip>true</maven.test.skip>
        <!--换成你的harbor仓库地址-->
        <docker.repostory>172.16.100.92:5000</docker.repostory>
        <!--换成你的仓库项目名称-->
        <docker.registry.name>sdc-erp</docker.registry.name>
        <docker.image.tag>1.0.0</docker.image.tag>
        <docker.maven.plugin.version>1.4.10</docker.maven.plugin.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.5.4</version>
        </dependency>


        <!--model-->
        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-model-admin</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-model-sys</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>dev</id>
            <properties>
                <repository.id>snapshot-test</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-test/</repository.url>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>test</id>
            <properties>
                <repository.id>snapshot-test</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-test/</repository.url>
            </properties>
        </profile>
        <profile>
            <id>uat</id>
            <properties>
                <repository.id>snapshot-prod</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-prod/</repository.url>
            </properties>
        </profile>
        <profile>
            <id>prod</id>
            <properties>
                <repository.id>snapshot-prod</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-prod/</repository.url>
            </properties>
        </profile>
    </profiles>
    <distributionManagement>
        <snapshotRepository>
            <id>${repository.id}</id>
            <url>${repository.url}</url>
        </snapshotRepository>
    </distributionManagement>

    <build>
        <finalName>${project.name}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>dockerfile-maven-plugin</artifactId>
                <version>${docker.maven.plugin.version}</version>
                <executions>
                    <execution>
                        <id>default</id>
                        <goals>
                            <goal>build</goal>
                            <goal>push</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <contextDirectory>${project.basedir}</contextDirectory>
                    <useMavenSettingsForAuth>true</useMavenSettingsForAuth>
                    <repository>${docker.repostory}/${docker.registry.name}/${project.artifactId}</repository>
                    <!--换成你的harbor仓库账号密码-->
                    <username>sdc-user</username>
                    <password>Sdc123456</password>
                    <tag>${docker.image.tag}</tag>
                    <buildArgs>
                        <JAR_FILE>target/${project.build.finalName}.jar</JAR_FILE>
                    </buildArgs>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <targetPath>${project.build.directory}/classes</targetPath>
                <includes>
                    <include>**/*</include>
                </includes>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

</project>
