package com.erp.server.tms.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.erp.model.tms.dto.TmsB2cDeclareReconciliationDetailDTO;
import com.erp.model.tms.entity.TmsB2cDeclareReconciliationDetailEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.time.LocalDate;
import java.util.List;


/**
 * <p>
 * b2c报关对账单明细 Mapper 接口
 * </p>
 *
 * @author will
 * @since 2024-03-19
 */
@Mapper
public interface TmsB2cDeclareReconciliationDetailMapper extends BaseMapper<TmsB2cDeclareReconciliationDetailEntity> {

    /**
     * @description: 分页查询
     * @author Will
     * @date: 2024/3/26 10:50
     * @param query
     * @param params
     * @return IPage<ListDTO>
     */
    IPage<TmsB2cDeclareReconciliationDetailDTO.ListDTO> paging(Page query,@Param("params")  TmsB2cDeclareReconciliationDetailDTO.PagingParamDTO params);

    /**
     * 导出Excel查询
     * @param params
     * @return
     */
    List<TmsB2cDeclareReconciliationDetailDTO.ListDTO> listExport(@Param("params") TmsB2cDeclareReconciliationDetailDTO.ExportDTO params);
    Page<TmsB2cDeclareReconciliationDetailDTO.ListDTO> listExport(@Param("page") Page<TmsB2cDeclareReconciliationDetailDTO.ListDTO> page, @Param("params") TmsB2cDeclareReconciliationDetailDTO.ExportDTO params);
    /**
     * @description: 查询币别
     * @author Will
     * @date: 2024/3/28 15:59
     * @param id
     * @return String
     */
    String getCurrencyById(@Param("id")String id);
    /**
     * @description: 查询可生成对账单数据
     * @author Will
     * @date: 2024/4/7 9:31
     * @param startDate
     * @param endDate
     * @return List<TmsB2cDeclareReconciliationDetailEntity>
     */
    List<TmsB2cDeclareReconciliationDetailEntity> listAutoGenerateDeclareReconciliation(@Param("startDate")LocalDate startDate,@Param("endDate") LocalDate endDate);
    
    List<TmsB2cDeclareReconciliationDetailEntity> listAutoGenerateCost(@Param("startDate")LocalDate startDate,@Param("endDate") LocalDate endDate);
}
