package com.erp.server.tms.service.logistics;

import cn.hutool.json.JSONUtil;
import com.common.business.annotation.LogisticsPlatformType;
import com.common.business.enums.LogisticsPlatformEnum;
import com.common.core.controller.vo.ApiResult;
import com.common.core.utils.FileUtil;
import com.common.core.utils.ValidatorUtil;
import com.erp.model.tms.entity.LogisticsSaleChannelEntity;
import com.erp.model.tms.enums.BusinessTypeEnum;
import com.erp.model.tms.enums.RequestStatusEnums;
import com.erp.model.tms.vo.request.*;
import com.erp.model.tms.vo.response.*;
import com.erp.server.tms.convert.LogisticsOrderConverter;
import com.erp.server.tms.handler.AbstractLogisticsHandler;
import com.erp.server.tms.service.LogisticsOperateService;
import com.sdk.tms.express.model.base.BaseResponse;
import com.sdk.tms.express.model.base.BaseResult;
import com.sdk.tms.express.model.order.request.*;
import com.sdk.tms.express.model.order.response.*;
import com.sdk.tms.express.service.ExpressShipperService;
import io.seata.common.util.CollectionUtils;
import io.seata.common.util.StringUtils;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.*;
import java.util.stream.Collectors;

/**
 * @author Jim
 * @ClassName AmazonLogisticsHandlerImpl
 * @description: 亚马逊物流接口开发
 * @date 2023年12月25日
 */
@Slf4j
@Component
@LogisticsPlatformType(LogisticsPlatformEnum.AMAZON)
public class AmazonLogisticsHandlerImpl extends AbstractLogisticsHandler {

    /**
     * 渠道查询
     *
     */
    public ApiResult<List<LogisticsSaleChannelEntity>> getChannel(ChanelQueryVO chanelQueryVO) {
        List<LogisticsSaleChannelEntity> entityList = new ArrayList<>();
            entityList.add(new LogisticsSaleChannelEntity().setCode("17FEIA").setPlatformChannelId("17FEIA").setCnName("17FEIA").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("360lion").setPlatformChannelId("360lion").setCnName("360lion").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("4PX").setPlatformChannelId("4PX").setCnName("4PX").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("A-1").setPlatformChannelId("A-1").setCnName("A-1").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("AAA Cooper").setPlatformChannelId("AAA Cooper").setCnName("AAA Cooper").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("ABF").setPlatformChannelId("ABF").setCnName("ABF").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("AFL/Fedex").setPlatformChannelId("AFL/Fedex").setCnName("AFL/Fedex").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("ALLJOY").setPlatformChannelId("ALLJOY").setCnName("ALLJOY").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("AMAUK").setPlatformChannelId("AMAUK").setCnName("AMAUK").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("AMAZON HORIZON").setPlatformChannelId("AMAZON HORIZON").setCnName("AMAZON HORIZON").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Amazon Shipping").setPlatformChannelId("Amazon Shipping").setCnName("Amazon Shipping").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("AMZL").setPlatformChannelId("AMZL").setCnName("AMZL").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("AMZL_UK").setPlatformChannelId("AMZL_UK").setCnName("AMZL_UK").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Andere").setPlatformChannelId("Andere").setCnName("Andere").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Anjun").setPlatformChannelId("Anjun").setCnName("Anjun").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("AO").setPlatformChannelId("AO").setCnName("AO").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("AO Deutschland").setPlatformChannelId("AO Deutschland").setCnName("AO Deutschland").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("APC").setPlatformChannelId("APC").setCnName("APC").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("APC Overnight").setPlatformChannelId("APC Overnight").setCnName("APC Overnight").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("APC POSTAL LOGISTICS").setPlatformChannelId("APC POSTAL LOGISTICS").setCnName("APC POSTAL LOGISTICS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("APG eCommerce").setPlatformChannelId("APG eCommerce").setCnName("APG eCommerce").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Aramex").setPlatformChannelId("Aramex").setCnName("Aramex").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("ARAS").setPlatformChannelId("ARAS").setCnName("ARAS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Aras Kargo").setPlatformChannelId("Aras Kargo").setCnName("Aras Kargo").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Arco Spedizioni").setPlatformChannelId("Arco Spedizioni").setCnName("Arco Spedizioni").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Arkas").setPlatformChannelId("Arkas").setCnName("Arkas").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Arrow XL").setPlatformChannelId("Arrow XL").setCnName("Arrow XL").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Asendia").setPlatformChannelId("Asendia").setCnName("Asendia").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Asgard").setPlatformChannelId("Asgard").setCnName("Asgard").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Assett").setPlatformChannelId("Assett").setCnName("Assett").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("AT POST").setPlatformChannelId("AT POST").setCnName("AT POST").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("ATS").setPlatformChannelId("ATS").setCnName("ATS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("AUSSIE_POST").setPlatformChannelId("AUSSIE_POST").setCnName("AUSSIE_POST").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Australia Post").setPlatformChannelId("Australia Post").setCnName("Australia Post").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Australia Post-ArticleID").setPlatformChannelId("Australia Post-ArticleID").setCnName("Australia Post-ArticleID").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Australia Post-Consignment").setPlatformChannelId("Australia Post-Consignment").setCnName("Australia Post-Consignment").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("B2C").setPlatformChannelId("B2C").setCnName("B2C").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("B2C Europe").setPlatformChannelId("B2C Europe").setCnName("B2C Europe").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("B2CShip").setPlatformChannelId("B2CShip").setCnName("B2CShip").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Balnak").setPlatformChannelId("Balnak").setCnName("Balnak").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Bartolini").setPlatformChannelId("Bartolini").setCnName("Bartolini").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Beijing Quanfeng Express").setPlatformChannelId("Beijing Quanfeng Express").setCnName("Beijing Quanfeng Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Best Buy").setPlatformChannelId("Best Buy").setCnName("Best Buy").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Best Express").setPlatformChannelId("Best Express").setCnName("Best Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Better Trucks").setPlatformChannelId("Better Trucks").setCnName("Better Trucks").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("BJS").setPlatformChannelId("BJS").setCnName("BJS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Blowhorn").setPlatformChannelId("Blowhorn").setCnName("Blowhorn").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Blue Package").setPlatformChannelId("Blue Package").setCnName("Blue Package").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("BlueDart").setPlatformChannelId("BlueDart").setCnName("BlueDart").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Bo臒azi莽i").setPlatformChannelId("Bo臒azi莽i").setCnName("Bo臒azi莽i").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Bombax").setPlatformChannelId("Bombax").setCnName("Bombax").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Bombino Express").setPlatformChannelId("Bombino Express").setCnName("Bombino Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("BPOST").setPlatformChannelId("BPOST").setCnName("BPOST").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("BR1 Express").setPlatformChannelId("BR1 Express").setCnName("BR1 Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("BRT").setPlatformChannelId("BRT").setCnName("BRT").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Buylogic").setPlatformChannelId("Buylogic").setCnName("Buylogic").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Canada Post").setPlatformChannelId("Canada Post").setCnName("Canada Post").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Canpar").setPlatformChannelId("Canpar").setCnName("Canpar").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("CargoLine").setPlatformChannelId("CargoLine").setCnName("CargoLine").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Caribou").setPlatformChannelId("Caribou").setCnName("Caribou").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Cart2India").setPlatformChannelId("Cart2India").setCnName("Cart2India").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("CBL").setPlatformChannelId("CBL").setCnName("CBL").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("CDC").setPlatformChannelId("CDC").setCnName("CDC").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("CELERITAS").setPlatformChannelId("CELERITAS").setCnName("CELERITAS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Centex").setPlatformChannelId("Centex").setCnName("Centex").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("CEVA").setPlatformChannelId("CEVA").setCnName("CEVA").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Ceva Lojistik").setPlatformChannelId("Ceva Lojistik").setCnName("Ceva Lojistik").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("China Post").setPlatformChannelId("China Post").setCnName("China Post").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Chrono Express").setPlatformChannelId("Chrono Express").setCnName("Chrono Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Chronopost").setPlatformChannelId("Chronopost").setCnName("Chronopost").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Chukou1").setPlatformChannelId("Chukou1").setCnName("Chukou1").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Cititrans").setPlatformChannelId("Cititrans").setCnName("Cititrans").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("City Link").setPlatformChannelId("City Link").setCnName("City Link").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("CityPost").setPlatformChannelId("CityPost").setCnName("CityPost").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("CNE").setPlatformChannelId("CNE").setCnName("CNE").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Coliposte").setPlatformChannelId("Coliposte").setCnName("Coliposte").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Colis Priv茅").setPlatformChannelId("Colis Priv茅").setCnName("Colis Priv茅").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Colissimo").setPlatformChannelId("Colissimo").setCnName("Colissimo").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Consegna Mezzi Propri").setPlatformChannelId("Consegna Mezzi Propri").setCnName("Consegna Mezzi Propri").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Conway").setPlatformChannelId("Conway").setCnName("Conway").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Correios").setPlatformChannelId("Correios").setCnName("Correios").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Correos").setPlatformChannelId("Correos").setCnName("Correos").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Correos Express").setPlatformChannelId("Correos Express").setCnName("Correos Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("COSCO").setPlatformChannelId("COSCO").setCnName("COSCO").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("CouriersPlease").setPlatformChannelId("CouriersPlease").setCnName("CouriersPlease").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("CTT EXPRESS").setPlatformChannelId("CTT EXPRESS").setCnName("CTT EXPRESS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Cubyn").setPlatformChannelId("Cubyn").setCnName("Cubyn").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DACHSER").setPlatformChannelId("DACHSER").setCnName("DACHSER").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DAIPOST").setPlatformChannelId("DAIPOST").setCnName("DAIPOST").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DB Schenker").setPlatformChannelId("DB Schenker").setCnName("DB Schenker").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DEL Deliveries").setPlatformChannelId("DEL Deliveries").setCnName("DEL Deliveries").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Delhivery").setPlatformChannelId("Delhivery").setCnName("Delhivery").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Delivengo").setPlatformChannelId("Delivengo").setCnName("Delivengo").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Delivery Group").setPlatformChannelId("Delivery Group").setCnName("Delivery Group").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Der Kurier").setPlatformChannelId("Der Kurier").setCnName("Der Kurier").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Deutsche Post").setPlatformChannelId("Deutsche Post").setCnName("Deutsche Post").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DFL").setPlatformChannelId("DFL").setCnName("DFL").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DHL").setPlatformChannelId("DHL").setCnName("DHL").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DHL eCommerce").setPlatformChannelId("DHL eCommerce").setCnName("DHL eCommerce").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DHL Express").setPlatformChannelId("DHL Express").setCnName("DHL Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DHL Freight").setPlatformChannelId("DHL Freight").setCnName("DHL Freight").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DHL Global Mail").setPlatformChannelId("DHL Global Mail").setCnName("DHL Global Mail").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DHL Home Delivery").setPlatformChannelId("DHL Home Delivery").setCnName("DHL Home Delivery").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DHL Kargo").setPlatformChannelId("DHL Kargo").setCnName("DHL Kargo").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DHL-Paket").setPlatformChannelId("DHL-Paket").setCnName("DHL-Paket").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DHL Parcel UK").setPlatformChannelId("DHL Parcel UK").setCnName("DHL Parcel UK").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DHLPL").setPlatformChannelId("DHLPL").setCnName("DHLPL").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Digital Delivery").setPlatformChannelId("Digital Delivery").setCnName("Digital Delivery").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DirectLog").setPlatformChannelId("DirectLog").setCnName("DirectLog").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Dotzot").setPlatformChannelId("Dotzot").setCnName("Dotzot").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DPB").setPlatformChannelId("DPB").setCnName("DPB").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DPD").setPlatformChannelId("DPD").setCnName("DPD").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DPD Local").setPlatformChannelId("DPD Local").setCnName("DPD Local").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DSV").setPlatformChannelId("DSV").setCnName("DSV").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DTDC").setPlatformChannelId("DTDC").setCnName("DTDC").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DX").setPlatformChannelId("DX").setCnName("DX").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DX Express").setPlatformChannelId("DX Express").setCnName("DX Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DX Freight").setPlatformChannelId("DX Freight").setCnName("DX Freight").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DX Secure").setPlatformChannelId("DX Secure").setCnName("DX Secure").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("DYNAMIC EXPRESS").setPlatformChannelId("DYNAMIC EXPRESS").setCnName("DYNAMIC EXPRESS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("ECMS").setPlatformChannelId("ECMS").setCnName("ECMS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("ECMS express").setPlatformChannelId("ECMS express").setCnName("ECMS express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Ecom Express").setPlatformChannelId("Ecom Express").setCnName("Ecom Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Ecom Shipping solutions PVT ltd").setPlatformChannelId("Ecom Shipping solutions PVT ltd").setCnName("Ecom Shipping solutions PVT ltd").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("EINSA SOURCING").setPlatformChannelId("EINSA SOURCING").setCnName("EINSA SOURCING").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("EKI Trans").setPlatformChannelId("EKI Trans").setCnName("EKI Trans").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Emirates Post").setPlatformChannelId("Emirates Post").setCnName("Emirates Post").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Emons").setPlatformChannelId("Emons").setCnName("Emons").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Endopack").setPlatformChannelId("Endopack").setCnName("Endopack").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Energo").setPlatformChannelId("Energo").setCnName("Energo").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Envialia").setPlatformChannelId("Envialia").setCnName("Envialia").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("ePost Global").setPlatformChannelId("ePost Global").setCnName("ePost Global").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Equick").setPlatformChannelId("Equick").setCnName("Equick").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Estafeta").setPlatformChannelId("Estafeta").setCnName("Estafeta").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Estes").setPlatformChannelId("Estes").setCnName("Estes").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("EUB").setPlatformChannelId("EUB").setCnName("EUB").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Europaczka").setPlatformChannelId("Europaczka").setCnName("Europaczka").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Exapaq").setPlatformChannelId("Exapaq").setCnName("Exapaq").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("FAST EST").setPlatformChannelId("FAST EST").setCnName("FAST EST").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Fastway").setPlatformChannelId("Fastway").setCnName("Fastway").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("FedEx").setPlatformChannelId("FedEx").setCnName("FedEx").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Fedex Freight").setPlatformChannelId("Fedex Freight").setCnName("Fedex Freight").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("FEDEX JP").setPlatformChannelId("FEDEX JP").setCnName("FEDEX JP").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("FedEx SmartPost").setPlatformChannelId("FedEx SmartPost").setCnName("FedEx SmartPost").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("FERCAM").setPlatformChannelId("FERCAM").setCnName("FERCAM").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Fillo Kargo").setPlatformChannelId("Fillo Kargo").setCnName("Fillo Kargo").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("First Flight").setPlatformChannelId("First Flight").setCnName("First Flight").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("First Flight China").setPlatformChannelId("First Flight China").setCnName("First Flight China").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("First Mile").setPlatformChannelId("First Mile").setCnName("First Mile").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Fleetan").setPlatformChannelId("Fleetan").setCnName("Fleetan").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Flyt").setPlatformChannelId("Flyt").setCnName("Flyt").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("FRACHTPOST").setPlatformChannelId("FRACHTPOST").setCnName("FRACHTPOST").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("FRANCE EXPRESS").setPlatformChannelId("FRANCE EXPRESS").setCnName("FRANCE EXPRESS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Gati").setPlatformChannelId("Gati").setCnName("Gati").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("GEL").setPlatformChannelId("GEL").setCnName("GEL").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("GEL Express").setPlatformChannelId("GEL Express").setCnName("GEL Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("geodis").setPlatformChannelId("geodis").setCnName("geodis").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Geodis Calberson").setPlatformChannelId("Geodis Calberson").setCnName("Geodis Calberson").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Geopost Kargo").setPlatformChannelId("Geopost Kargo").setCnName("Geopost Kargo").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("GFS").setPlatformChannelId("GFS").setCnName("GFS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("GLS").setPlatformChannelId("GLS").setCnName("GLS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("GO!").setPlatformChannelId("GO!").setCnName("GO!").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Gojavas").setPlatformChannelId("Gojavas").setCnName("Gojavas").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("GRUPO LOGISTIC").setPlatformChannelId("GRUPO LOGISTIC").setCnName("GRUPO LOGISTIC").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Hellmann").setPlatformChannelId("Hellmann").setCnName("Hellmann").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Heppner").setPlatformChannelId("Heppner").setCnName("Heppner").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Hermes").setPlatformChannelId("Hermes").setCnName("Hermes").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Hermes (Corporate)").setPlatformChannelId("Hermes (Corporate)").setCnName("Hermes (Corporate)").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Hermes Einrichtungsservice").setPlatformChannelId("Hermes Einrichtungsservice").setCnName("Hermes Einrichtungsservice").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Hermes Logistik Gruppe").setPlatformChannelId("Hermes Logistik Gruppe").setCnName("Hermes Logistik Gruppe").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Hermes UK").setPlatformChannelId("Hermes UK").setCnName("Hermes UK").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Hlog").setPlatformChannelId("Hlog").setCnName("Hlog").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("HNC").setPlatformChannelId("HNC").setCnName("HNC").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Home Logistics").setPlatformChannelId("Home Logistics").setCnName("Home Logistics").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("honesteye").setPlatformChannelId("honesteye").setCnName("honesteye").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Hongkong Post").setPlatformChannelId("Hongkong Post").setCnName("Hongkong Post").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Horoz Lojistik").setPlatformChannelId("Horoz Lojistik").setCnName("Horoz Lojistik").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Hotpoint Logistics").setPlatformChannelId("Hotpoint Logistics").setCnName("Hotpoint Logistics").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("HRP").setPlatformChannelId("HRP").setCnName("HRP").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("HS code").setPlatformChannelId("HS code").setCnName("HS code").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("HUAHAN Logistics").setPlatformChannelId("HUAHAN Logistics").setCnName("HUAHAN Logistics").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("HubEurope").setPlatformChannelId("HubEurope").setCnName("HubEurope").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Hunter Logistics").setPlatformChannelId("Hunter Logistics").setCnName("Hunter Logistics").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Huxloe").setPlatformChannelId("Huxloe").setCnName("Huxloe").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Huxloe Logistics").setPlatformChannelId("Huxloe Logistics").setCnName("Huxloe Logistics").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("ICC Worldwide").setPlatformChannelId("ICC Worldwide").setCnName("ICC Worldwide").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("IDS").setPlatformChannelId("IDS").setCnName("IDS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("IDS Netzwerk").setPlatformChannelId("IDS Netzwerk").setCnName("IDS Netzwerk").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("iMile").setPlatformChannelId("iMile").setCnName("iMile").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("India Post").setPlatformChannelId("India Post").setCnName("India Post").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("InPost").setPlatformChannelId("InPost").setCnName("InPost").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Interlink").setPlatformChannelId("Interlink").setCnName("Interlink").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Interno").setPlatformChannelId("Interno").setCnName("Interno").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Intersoft").setPlatformChannelId("Intersoft").setCnName("Intersoft").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("iParcel").setPlatformChannelId("iParcel").setCnName("iParcel").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("ITD Global").setPlatformChannelId("ITD Global").setCnName("ITD Global").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("J&amp;T Express").setPlatformChannelId("J&amp;T Express").setCnName("J&amp;T Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Japan Post").setPlatformChannelId("Japan Post").setCnName("Japan Post").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("JCEX").setPlatformChannelId("JCEX").setCnName("JCEX").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Jersey Post").setPlatformChannelId("Jersey Post").setCnName("Jersey Post").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Jiufang").setPlatformChannelId("Jiufang").setCnName("Jiufang").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("JP EXPRESS").setPlatformChannelId("JP EXPRESS").setCnName("JP EXPRESS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("JPL UPU").setPlatformChannelId("JPL UPU").setCnName("JPL UPU").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("JS Express").setPlatformChannelId("JS Express").setCnName("JS Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("JT").setPlatformChannelId("JT").setCnName("JT").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Kargokar").setPlatformChannelId("Kargokar").setCnName("Kargokar").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("KEAVO").setPlatformChannelId("KEAVO").setCnName("KEAVO").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Kerry").setPlatformChannelId("Kerry").setCnName("Kerry").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Kuehne+Nagel").setPlatformChannelId("Kuehne+Nagel").setCnName("Kuehne+Nagel").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Kybotech").setPlatformChannelId("Kybotech").setCnName("Kybotech").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("La Poste").setPlatformChannelId("La Poste").setCnName("La Poste").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Landmark").setPlatformChannelId("Landmark").setCnName("Landmark").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Landmark Global").setPlatformChannelId("Landmark Global").setCnName("Landmark Global").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Lasership").setPlatformChannelId("Lasership").setCnName("Lasership").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Lemonmode").setPlatformChannelId("Lemonmode").setCnName("Lemonmode").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("LF Logistic").setPlatformChannelId("LF Logistic").setCnName("LF Logistic").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Liccardi").setPlatformChannelId("Liccardi").setCnName("Liccardi").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Liccardi Trasporti").setPlatformChannelId("Liccardi Trasporti").setCnName("Liccardi Trasporti").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Logistik Gruppe").setPlatformChannelId("Logistik Gruppe").setCnName("Logistik Gruppe").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Loomis").setPlatformChannelId("Loomis").setCnName("Loomis").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Mail Alliance").setPlatformChannelId("Mail Alliance").setCnName("Mail Alliance").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Mail Americas").setPlatformChannelId("Mail Americas").setCnName("Mail Americas").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Mainpost").setPlatformChannelId("Mainpost").setCnName("Mainpost").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("MBE").setPlatformChannelId("MBE").setCnName("MBE").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Metro Kargo").setPlatformChannelId("Metro Kargo").setCnName("Metro Kargo").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Mezzi propri").setPlatformChannelId("Mezzi propri").setCnName("Mezzi propri").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("MHI").setPlatformChannelId("MHI").setCnName("MHI").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Milkman").setPlatformChannelId("Milkman").setCnName("Milkman").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("MNG Kargo").setPlatformChannelId("MNG Kargo").setCnName("MNG Kargo").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Mondial Relay").setPlatformChannelId("Mondial Relay").setCnName("Mondial Relay").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("MRW").setPlatformChannelId("MRW").setCnName("MRW").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("MZZ-Briefdienst").setPlatformChannelId("MZZ-Briefdienst").setCnName("MZZ-Briefdienst").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Nacex").setPlatformChannelId("Nacex").setCnName("Nacex").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("NAQEL EXPRESS").setPlatformChannelId("NAQEL EXPRESS").setCnName("NAQEL EXPRESS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Narpost Kargo").setPlatformChannelId("Narpost Kargo").setCnName("Narpost Kargo").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("New Zealand Post").setPlatformChannelId("New Zealand Post").setCnName("New Zealand Post").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Newgistics").setPlatformChannelId("Newgistics").setCnName("Newgistics").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Nexive").setPlatformChannelId("Nexive").setCnName("Nexive").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Ninjavan").setPlatformChannelId("Ninjavan").setCnName("Ninjavan").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("NipponExpress").setPlatformChannelId("NipponExpress").setCnName("NipponExpress").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("NITTSU").setPlatformChannelId("NITTSU").setCnName("NITTSU").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("NOVEO").setPlatformChannelId("NOVEO").setCnName("NOVEO").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("NowBikes").setPlatformChannelId("NowBikes").setCnName("NowBikes").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("NTL").setPlatformChannelId("NTL").setCnName("NTL").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("OCS Worldwide").setPlatformChannelId("OCS Worldwide").setCnName("OCS Worldwide").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Old Dominion").setPlatformChannelId("Old Dominion").setCnName("Old Dominion").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("OneWorldExpress").setPlatformChannelId("OneWorldExpress").setCnName("OneWorldExpress").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("ONTIME").setPlatformChannelId("ONTIME").setCnName("ONTIME").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("OnTrac").setPlatformChannelId("OnTrac").setCnName("OnTrac").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("OSM").setPlatformChannelId("OSM").setCnName("OSM").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("OSM Worldwide").setPlatformChannelId("OSM Worldwide").setCnName("OSM Worldwide").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Other").setPlatformChannelId("Other").setCnName("Other").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Otro").setPlatformChannelId("Otro").setCnName("Otro").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Overnite Express").setPlatformChannelId("Overnite Express").setCnName("Overnite Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Palletline").setPlatformChannelId("Palletline").setCnName("Palletline").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Palletways").setPlatformChannelId("Palletways").setCnName("Palletways").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Panther").setPlatformChannelId("Panther").setCnName("Panther").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Parcel Hub").setPlatformChannelId("Parcel Hub").setCnName("Parcel Hub").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Parcel Monkey").setPlatformChannelId("Parcel Monkey").setCnName("Parcel Monkey").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Parcel Station").setPlatformChannelId("Parcel Station").setCnName("Parcel Station").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Parcel2go").setPlatformChannelId("Parcel2go").setCnName("Parcel2go").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("ParcelDenOnline").setPlatformChannelId("ParcelDenOnline").setCnName("ParcelDenOnline").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Parcelforce").setPlatformChannelId("Parcelforce").setCnName("Parcelforce").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Parcelhub").setPlatformChannelId("Parcelhub").setCnName("Parcelhub").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Parcelink Logistics").setPlatformChannelId("Parcelink Logistics").setCnName("Parcelink Logistics").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Parcelnet").setPlatformChannelId("Parcelnet").setCnName("Parcelnet").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("ParcelOne").setPlatformChannelId("ParcelOne").setCnName("ParcelOne").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("PDC Logistics").setPlatformChannelId("PDC Logistics").setCnName("PDC Logistics").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Pilot").setPlatformChannelId("Pilot").setCnName("Pilot").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Pilot Freight").setPlatformChannelId("Pilot Freight").setCnName("Pilot Freight").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("PIN").setPlatformChannelId("PIN").setCnName("PIN").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Polish Post").setPlatformChannelId("Polish Post").setCnName("Polish Post").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Pos Laju").setPlatformChannelId("Pos Laju").setCnName("Pos Laju").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Post Modern").setPlatformChannelId("Post Modern").setCnName("Post Modern").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Poste Italiane").setPlatformChannelId("Poste Italiane").setCnName("Poste Italiane").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("PostNL").setPlatformChannelId("PostNL").setCnName("PostNL").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("PostNord").setPlatformChannelId("PostNord").setCnName("PostNord").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Professional").setPlatformChannelId("Professional").setCnName("Professional").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("PTT Kargo").setPlatformChannelId("PTT Kargo").setCnName("PTT Kargo").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("PUROLATOR").setPlatformChannelId("PUROLATOR").setCnName("PUROLATOR").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Qxpress").setPlatformChannelId("Qxpress").setCnName("Qxpress").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("R+L").setPlatformChannelId("R+L").setCnName("R+L").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Raben Group").setPlatformChannelId("Raben Group").setCnName("Raben Group").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("RBNA").setPlatformChannelId("RBNA").setCnName("RBNA").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("REDUR").setPlatformChannelId("REDUR").setCnName("REDUR").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Rhenus").setPlatformChannelId("Rhenus").setCnName("Rhenus").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Rieck").setPlatformChannelId("Rieck").setCnName("Rieck").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Rivigo").setPlatformChannelId("Rivigo").setCnName("Rivigo").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("RMLGB").setPlatformChannelId("RMLGB").setCnName("RMLGB").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Roadrunner").setPlatformChannelId("Roadrunner").setCnName("Roadrunner").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Royal Mail").setPlatformChannelId("Royal Mail").setCnName("Royal Mail").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("RR Donnelley").setPlatformChannelId("RR Donnelley").setCnName("RR Donnelley").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Safexpress").setPlatformChannelId("Safexpress").setCnName("Safexpress").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("SAGAWA").setPlatformChannelId("SAGAWA").setCnName("SAGAWA").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("SAGAWA EXPRESS").setPlatformChannelId("SAGAWA EXPRESS").setCnName("SAGAWA EXPRESS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Saia").setPlatformChannelId("Saia").setCnName("Saia").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Sailpost").setPlatformChannelId("Sailpost").setCnName("Sailpost").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Schweizer Post").setPlatformChannelId("Schweizer Post").setCnName("Schweizer Post").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("SDA").setPlatformChannelId("SDA").setCnName("SDA").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Seino").setPlatformChannelId("Seino").setCnName("Seino").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("SEINO TRANSPORTATION").setPlatformChannelId("SEINO TRANSPORTATION").setCnName("SEINO TRANSPORTATION").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Seko Logistics").setPlatformChannelId("Seko Logistics").setCnName("Seko Logistics").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Selem Kargo").setPlatformChannelId("Selem Kargo").setCnName("Selem Kargo").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Self Delivery").setPlatformChannelId("Self Delivery").setCnName("Self Delivery").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Sendcloud").setPlatformChannelId("Sendcloud").setCnName("Sendcloud").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Sending").setPlatformChannelId("Sending").setCnName("Sending").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("SENDLE").setPlatformChannelId("SENDLE").setCnName("SENDLE").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Seur").setPlatformChannelId("Seur").setCnName("Seur").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Seven Senders").setPlatformChannelId("Seven Senders").setCnName("Seven Senders").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("SF Express").setPlatformChannelId("SF Express").setCnName("SF Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("SFC").setPlatformChannelId("SFC").setCnName("SFC").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Ship Delight").setPlatformChannelId("Ship Delight").setCnName("Ship Delight").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Ship Global US").setPlatformChannelId("Ship Global US").setCnName("Ship Global US").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("SHIPA").setPlatformChannelId("SHIPA").setCnName("SHIPA").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("ShipEconomy").setPlatformChannelId("ShipEconomy").setCnName("ShipEconomy").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("ShipGlobal").setPlatformChannelId("ShipGlobal").setCnName("ShipGlobal").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Shipmate").setPlatformChannelId("Shipmate").setCnName("Shipmate").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Shippit").setPlatformChannelId("Shippit").setCnName("Shippit").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Shree Maruti Courier").setPlatformChannelId("Shree Maruti Courier").setCnName("Shree Maruti Courier").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Shree Tirupati Courier").setPlatformChannelId("Shree Tirupati Courier").setCnName("Shree Tirupati Courier").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Shunfeng Express").setPlatformChannelId("Shunfeng Express").setCnName("Shunfeng Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Singapore Post").setPlatformChannelId("Singapore Post").setCnName("Singapore Post").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Sinotrans").setPlatformChannelId("Sinotrans").setCnName("Sinotrans").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Skypostal").setPlatformChannelId("Skypostal").setCnName("Skypostal").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Smartmail").setPlatformChannelId("Smartmail").setCnName("Smartmail").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Smartrlogistics").setPlatformChannelId("Smartrlogistics").setCnName("Smartrlogistics").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("SMSA").setPlatformChannelId("SMSA").setCnName("SMSA").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("SMSA Express").setPlatformChannelId("SMSA Express").setCnName("SMSA Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Soarmall").setPlatformChannelId("Soarmall").setCnName("Soarmall").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Sonstige").setPlatformChannelId("Sonstige").setCnName("Sonstige").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("South Eastern Freight Lines").setPlatformChannelId("South Eastern Freight Lines").setCnName("South Eastern Freight Lines").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Speedaf").setPlatformChannelId("Speedaf").setCnName("Speedaf").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Speedex").setPlatformChannelId("Speedex").setCnName("Speedex").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Spoton").setPlatformChannelId("Spoton").setCnName("Spoton").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("SPRING").setPlatformChannelId("SPRING").setCnName("SPRING").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("spring GDS").setPlatformChannelId("spring GDS").setCnName("spring GDS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Sprint").setPlatformChannelId("Sprint").setCnName("Sprint").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Stahlmann and Sachs").setPlatformChannelId("Stahlmann and Sachs").setCnName("Stahlmann and Sachs").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Stampit").setPlatformChannelId("Stampit").setCnName("Stampit").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Staples").setPlatformChannelId("Staples").setCnName("Staples").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("StarTrack-ArticleID").setPlatformChannelId("StarTrack-ArticleID").setCnName("StarTrack-ArticleID").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("StarTrack-Consignment").setPlatformChannelId("StarTrack-Consignment").setCnName("StarTrack-Consignment").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("STG").setPlatformChannelId("STG").setCnName("STG").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("STO Express").setPlatformChannelId("STO Express").setCnName("STO Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Streamlite").setPlatformChannelId("Streamlite").setCnName("Streamlite").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Sunyou").setPlatformChannelId("Sunyou").setCnName("Sunyou").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("S眉rat Kargo").setPlatformChannelId("S眉rat Kargo").setCnName("S眉rat Kargo").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Susa").setPlatformChannelId("Susa").setCnName("Susa").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Swiss post").setPlatformChannelId("Swiss post").setCnName("Swiss post").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Szendex").setPlatformChannelId("Szendex").setCnName("Szendex").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Target").setPlatformChannelId("Target").setCnName("Target").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("TDN").setPlatformChannelId("TDN").setCnName("TDN").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Tezel Lojistik").setPlatformChannelId("Tezel Lojistik").setCnName("Tezel Lojistik").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("The Delivery Group").setPlatformChannelId("The Delivery Group").setCnName("The Delivery Group").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("The Professional Couriers").setPlatformChannelId("The Professional Couriers").setCnName("The Professional Couriers").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("TIPSA").setPlatformChannelId("TIPSA").setCnName("TIPSA").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("TNT").setPlatformChannelId("TNT").setCnName("TNT").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("TNT Kargo").setPlatformChannelId("TNT Kargo").setCnName("TNT Kargo").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("TNTIT").setPlatformChannelId("TNTIT").setCnName("TNTIT").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Toll").setPlatformChannelId("Toll").setCnName("Toll").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Toll Global Express").setPlatformChannelId("Toll Global Express").setCnName("Toll Global Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Tongda Global").setPlatformChannelId("Tongda Global").setCnName("Tongda Global").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Topyou").setPlatformChannelId("Topyou").setCnName("Topyou").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Total Express").setPlatformChannelId("Total Express").setCnName("Total Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Tourline").setPlatformChannelId("Tourline").setCnName("Tourline").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Trackon").setPlatformChannelId("Trackon").setCnName("Trackon").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Trakpak").setPlatformChannelId("Trakpak").setCnName("Trakpak").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Transaher").setPlatformChannelId("Transaher").setCnName("Transaher").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Transaragon茅s").setPlatformChannelId("Transaragon茅s").setCnName("Transaragon茅s").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("TransFolha").setPlatformChannelId("TransFolha").setCnName("TransFolha").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Translink").setPlatformChannelId("Translink").setCnName("Translink").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Trans-o-Flex").setPlatformChannelId("Trans-o-Flex").setCnName("Trans-o-Flex").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Truline").setPlatformChannelId("Truline").setCnName("Truline").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("TSB").setPlatformChannelId("TSB").setCnName("TSB").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Tuffnells").setPlatformChannelId("Tuffnells").setCnName("Tuffnells").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("TWS").setPlatformChannelId("TWS").setCnName("TWS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("TXT").setPlatformChannelId("TXT").setCnName("TXT").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("TyD").setPlatformChannelId("TyD").setCnName("TyD").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("UBI").setPlatformChannelId("UBI").setCnName("UBI").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("UKMail").setPlatformChannelId("UKMail").setCnName("UKMail").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("UPakWeShip").setPlatformChannelId("UPakWeShip").setCnName("UPakWeShip").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("UPS").setPlatformChannelId("UPS").setCnName("UPS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("UPS Freight").setPlatformChannelId("UPS Freight").setCnName("UPS Freight").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("UPS Mail Innovations").setPlatformChannelId("UPS Mail Innovations").setCnName("UPS Mail Innovations").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Upsilon").setPlatformChannelId("Upsilon").setCnName("Upsilon").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("UPSMI").setPlatformChannelId("UPSMI").setCnName("UPSMI").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Urban Express").setPlatformChannelId("Urban Express").setCnName("Urban Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Uship").setPlatformChannelId("Uship").setCnName("Uship").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("USPS").setPlatformChannelId("USPS").setCnName("USPS").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Verage Shipping").setPlatformChannelId("Verage Shipping").setCnName("Verage Shipping").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Via Xpress").setPlatformChannelId("Via Xpress").setCnName("Via Xpress").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("VIR").setPlatformChannelId("VIR").setCnName("VIR").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("VNLIN").setPlatformChannelId("VNLIN").setCnName("VNLIN").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("WanbExpress").setPlatformChannelId("WanbExpress").setCnName("WanbExpress").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Watkins and Shepard").setPlatformChannelId("Watkins and Shepard").setCnName("Watkins and Shepard").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Wefast").setPlatformChannelId("Wefast").setCnName("Wefast").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("WeWorldExpress").setPlatformChannelId("WeWorldExpress").setCnName("WeWorldExpress").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Whistl").setPlatformChannelId("Whistl").setCnName("Whistl").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Whizzard").setPlatformChannelId("Whizzard").setCnName("Whizzard").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("WINIT").setPlatformChannelId("WINIT").setCnName("WINIT").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("WPX").setPlatformChannelId("WPX").setCnName("WPX").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("XDP").setPlatformChannelId("XDP").setCnName("XDP").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("XPO").setPlatformChannelId("XPO").setCnName("XPO").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("XPO Freight").setPlatformChannelId("XPO Freight").setCnName("XPO Freight").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Xpressbees").setPlatformChannelId("Xpressbees").setCnName("Xpressbees").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("YAMATO").setPlatformChannelId("YAMATO").setCnName("YAMATO").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("YAMATO TRANSPORT").setPlatformChannelId("YAMATO TRANSPORT").setCnName("YAMATO TRANSPORT").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("YANWEN").setPlatformChannelId("YANWEN").setCnName("YANWEN").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("YDH").setPlatformChannelId("YDH").setCnName("YDH").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Yellow Freight").setPlatformChannelId("Yellow Freight").setCnName("Yellow Freight").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("YFHEX").setPlatformChannelId("YFHEX").setCnName("YFHEX").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Yodel").setPlatformChannelId("Yodel").setCnName("Yodel").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("YTO Express").setPlatformChannelId("YTO Express").setCnName("YTO Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Yun Express").setPlatformChannelId("Yun Express").setCnName("Yun Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Yunda Express").setPlatformChannelId("Yunda Express").setCnName("Yunda Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Yurti莽i Kargo").setPlatformChannelId("Yurti莽i Kargo").setCnName("Yurti莽i Kargo").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Zeleris").setPlatformChannelId("Zeleris").setCnName("Zeleris").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("ZTO Express").setPlatformChannelId("ZTO Express").setCnName("ZTO Express").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
            entityList.add(new LogisticsSaleChannelEntity().setCode("Zust Ambrosetti").setPlatformChannelId("Zust Ambrosetti").setCnName("Zust Ambrosetti").setLogisticsPlatform(LogisticsPlatformEnum.AMAZON.getCode()));
      return success(entityList);
    }

    @Override
    public LogisticsPlatformEnum getPlatForm() {
        return LogisticsPlatformEnum.AMAZON;
    }

    @Override
    public ApiResult<List<LogisticsServiceResponseVO>> listLogisticsService(Map<String, String> authMap) {
        return ApiResult.error(-1, "功能未开放");

    }
}
