
package com.sdk.tms.baohong.api.asn;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceForAsn", targetNamespace = "http://www.example.org/ServiceForAsn/", wsdlLocation = "http://exoms.globex.cn/default/receiving-soap/")
public class ServiceForAsn_Service
    extends Service
{

    private final static String NAMESPACE_URI = "http://www.example.org/ServiceForAsn/";
    private final static URL SERVICEFORASN_WSDL_LOCATION;
    private final static WebServiceException SERVICEFORASN_EXCEPTION;
    private final static QName SERVICEFORASN_QNAME = new QName(NAMESPACE_URI, "ServiceForAsn");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://exoms.globex.cn/default/receiving-soap/");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEFORASN_WSDL_LOCATION = url;
        SERVICEFORASN_EXCEPTION = e;
    }

    public ServiceForAsn_Service() {
        super(__getWsdlLocation(), SERVICEFORASN_QNAME);
    }

    public ServiceForAsn_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEFORASN_QNAME, features);
    }

    public ServiceForAsn_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICEFORASN_QNAME);
    }

    public ServiceForAsn_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEFORASN_QNAME, features);
    }

    public ServiceForAsn_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceForAsn_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceForAsn
     */
    @WebEndpoint(name = "ServiceForAsnSOAP")
    public ServiceForAsn getServiceForAsnSOAP() {
        return super.getPort(new QName(NAMESPACE_URI, "ServiceForAsnSOAP"), ServiceForAsn.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceForAsn
     */
    @WebEndpoint(name = "ServiceForAsnSOAP")
    public ServiceForAsn getServiceForAsnSOAP(WebServiceFeature... features) {
        return super.getPort(new QName(NAMESPACE_URI, "ServiceForAsnSOAP"), ServiceForAsn.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEFORASN_EXCEPTION!= null) {
            throw SERVICEFORASN_EXCEPTION;
        }
        return SERVICEFORASN_WSDL_LOCATION;
    }

}
