
package com.sdk.tms.baohong.api.asn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceForAsn", targetNamespace = "http://www.example.org/ServiceForAsn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceForAsn {


    /**
     * 
     * @param asnInfo
     * @param headerRequest
     * @param ask
     * @param message
     * @param error
     * @param asnCode
     */
    @WebMethod(action = "http://www.example.org/ServiceForAsn/createAsn")
    @RequestWrapper(localName = "createAsn", targetNamespace = "http://www.example.org/ServiceForAsn/", className = "org.example.serviceforasn.CreateAsn")
    @ResponseWrapper(localName = "createAsnResponse", targetNamespace = "http://www.example.org/ServiceForAsn/", className = "org.example.serviceforasn.CreateAsnResponse")
    public void createAsn(
        @WebParam(name = "HeaderRequest", targetNamespace = "")
        HeaderRequest headerRequest,
        @WebParam(name = "ASNInfo", targetNamespace = "")
        ASNInfo asnInfo,
        @WebParam(name = "ask", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> ask,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "error", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> error,
        @WebParam(name = "ASNCode", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> asnCode);

    /**
     * 
     * @param updateASNInfo
     * @param headerRequest
     * @param ask
     * @param message
     * @param error
     * @param asnCode
     */
    @WebMethod(action = "http://www.example.org/ServiceForAsn/updateAsn")
    @RequestWrapper(localName = "updateAsn", targetNamespace = "http://www.example.org/ServiceForAsn/", className = "org.example.serviceforasn.UpdateAsn")
    @ResponseWrapper(localName = "updateAsnResponse", targetNamespace = "http://www.example.org/ServiceForAsn/", className = "org.example.serviceforasn.UpdateAsnResponse")
    public void updateAsn(
        @WebParam(name = "HeaderRequest", targetNamespace = "")
        HeaderRequest headerRequest,
        @WebParam(name = "UpdateASNInfo", targetNamespace = "")
        UpdateAsnInfo updateASNInfo,
        @WebParam(name = "ask", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> ask,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "error", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> error,
        @WebParam(name = "ASNCode", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> asnCode);

    /**
     * 
     * @param headerRequest
     * @param data
     * @param ask
     * @param message
     * @param error
     * @param asnCode
     */
    @WebMethod(action = "http://www.example.org/ServiceForAsn/getAsnByCode")
    @RequestWrapper(localName = "getAsnByCode", targetNamespace = "http://www.example.org/ServiceForAsn/", className = "org.example.serviceforasn.GetAsnByCode")
    @ResponseWrapper(localName = "getAsnByCodeResponse", targetNamespace = "http://www.example.org/ServiceForAsn/", className = "org.example.serviceforasn.GetAsnByCodeResponse")
    public void getAsnByCode(
        @WebParam(name = "HeaderRequest", targetNamespace = "")
        HeaderRequest headerRequest,
        @WebParam(name = "ASNCode", targetNamespace = "")
        String asnCode,
        @WebParam(name = "ask", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> ask,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "error", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> error,
        @WebParam(name = "Data", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ASNData> data);

    /**
     * 
     * @param headerRequest
     * @param ask
     * @param message
     * @param error
     * @param asnCode
     */
    @WebMethod(action = "http://www.example.org/ServiceForAsn/confirmAsn")
    @RequestWrapper(localName = "confirmAsn", targetNamespace = "http://www.example.org/ServiceForAsn/", className = "org.example.serviceforasn.ConfirmAsn")
    @ResponseWrapper(localName = "confirmAsnResponse", targetNamespace = "http://www.example.org/ServiceForAsn/", className = "org.example.serviceforasn.ConfirmAsnResponse")
    public void confirmAsn(
        @WebParam(name = "HeaderRequest", targetNamespace = "")
        HeaderRequest headerRequest,
        @WebParam(name = "ASNCode", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> asnCode,
        @WebParam(name = "ask", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> ask,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "error", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> error);

    /**
     * 
     * @param headerRequest
     * @param ask
     * @param message
     * @param error
     * @param asnCode
     */
    @WebMethod(action = "http://www.example.org/ServiceForAsn/pendingAsn")
    @RequestWrapper(localName = "pendingAsn", targetNamespace = "http://www.example.org/ServiceForAsn/", className = "org.example.serviceforasn.PendingAsn")
    @ResponseWrapper(localName = "pendingAsnResponse", targetNamespace = "http://www.example.org/ServiceForAsn/", className = "org.example.serviceforasn.PendingAsnResponse")
    public void pendingAsn(
        @WebParam(name = "HeaderRequest", targetNamespace = "")
        HeaderRequest headerRequest,
        @WebParam(name = "ASNCode", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> asnCode,
        @WebParam(name = "ask", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> ask,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "error", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> error);

    /**
     * 
     * @param headerRequest
     * @param ask
     * @param receivingInfo
     * @param message
     * @param error
     * @param asnCode
     */
    @WebMethod(action = "http://www.example.org/ServiceForAsn/createReceiving")
    @RequestWrapper(localName = "createReceiving", targetNamespace = "http://www.example.org/ServiceForAsn/", className = "org.example.serviceforasn.CreateReceiving")
    @ResponseWrapper(localName = "createReceivingResponse", targetNamespace = "http://www.example.org/ServiceForAsn/", className = "org.example.serviceforasn.CreateReceivingResponse")
    public void createReceiving(
        @WebParam(name = "HeaderRequest", targetNamespace = "")
        HeaderRequest headerRequest,
        @WebParam(name = "ReceivingInfo", targetNamespace = "")
        ReceivingInfo receivingInfo,
        @WebParam(name = "ask", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> ask,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "error", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> error,
        @WebParam(name = "ASNCode", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> asnCode);

}
