spring:
  application:
    name:  erp-chrome
  profiles:
    active: dev
server:
  port: 7040

logging:
  config: classpath:logback-spring.xml
  level:
    com.alibaba.nacos.client.naming: WARN
    com.alibaba.nacos.client.config.impl: WARN