<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>cloud-erp</artifactId>
        <groupId>com.cloud.erp</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>erp-common</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>erp-common-pojo</module>
        <module>erp-common-message</module>
        <module>erp-common-core</module>
        <module>erp-common-web</module>
    </modules>

<!--    <distributionManagement>
        <repository>
            <id>nexus</id>
            <name>nexus Repository RELEASES</name>
            <url>http://172.16.110.11:8089/repository/maven-releases/</url>
        </repository>
        <snapshotRepository>
            <id>nexus</id>
            <name>nexus Repository SNAPSHOTS</name>
            <url>http://172.16.110.11:8089/repository/maven-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>2.3.4.RELEASE</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>-->


</project>