<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>cloud-erp</artifactId>
        <groupId>com.cloud.erp</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>erp-sdk</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>erp-sdk-msg-fs</module>
        <module>erp-sdk-oms-amz-spapi</module>
        <module>erp-sdk-oms-amz-aws</module>
        <module>erp-sdk-oms-walmart</module>
        <module>erp-sdk-oms-shopee</module>
        <module>erp-sdk-wms-antu</module>
        <module>erp-sdk-wms-goodcang</module>
        <module>erp-sdk-wms-iml</module>
        <module>erp-sdk-third-lingxing</module>
        <module>erp-sdk-third-mabang</module>
        <module>erp-sdk-third-guanyi</module>
        <module>erp-sdk-third-kingdee</module>
        <module>erp-sdk-oms-shopify</module>
        <module>erp-sdk-tms-disifang</module>
        <module>erp-sdk-tms-express</module>
        <module>erp-sdk-tms-shopee</module>
        <module>erp-sdk-tms-ubi</module>
        <module>erp-sdk-tms-track123</module>
        <module>erp-sdk-tms-yanwen</module>
        <module>erp-sdk-tms-weishi</module>
        <module>erp-sdk-tms-yuntu</module>
        <module>erp-sdk-tms-tongyou</module>
        <module>erp-sdk-tms-aliexpress</module>
        <module>erp-sdk-oms-aliexpress</module>
        <module>erp-sdk-tms-batong</module>
        <module>erp-sdk-tms-baohong</module>
        <module>erp-sdk-oms-mercado</module>
        <module>erp-sdk-oms-tiktok</module>
        <module>erp-sdk-tms-tiktok</module>
        <module>erp-sdk-third-wangdian</module>
        <module>erp-sdk-third-qimen</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>com.cloud.erp</groupId>
            <artifactId>erp-common-business</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <artifactId>spring-cloud-context</artifactId>
                    <groupId>org.springframework.cloud</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-cloud-commons</artifactId>
                    <groupId>org.springframework.cloud</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-cloud-netflix-archaius</artifactId>
                    <groupId>org.springframework.cloud</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-cloud-netflix-ribbon</artifactId>
                    <groupId>org.springframework.cloud</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-cloud-starter</artifactId>
                    <groupId>org.springframework.cloud</groupId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>dev</id>
            <properties>
                <repository.id>snapshot-test</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-test/</repository.url>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>test</id>
            <properties>
                <repository.id>snapshot-test</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-test/</repository.url>
            </properties>
        </profile>
        <profile>
            <id>uat</id>
            <properties>
                <repository.id>snapshot-prod</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-prod/</repository.url>
            </properties>
        </profile>
        <profile>
            <id>prod</id>
            <properties>
                <repository.id>snapshot-prod</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-prod/</repository.url>
            </properties>
        </profile>
    </profiles>
    <distributionManagement>
        <snapshotRepository>
            <id>${repository.id}</id>
            <url>${repository.url}</url>
        </snapshotRepository>
    </distributionManagement>

</project>