<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>cloud-erp</artifactId>
        <groupId>com.cloud.erp</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>erp-sdk</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>erp-sdk-fs</module>
        <module>erp-sdk-amz-spapi</module>
        <module>erp-sdk-amz-aws</module>
        <module>erp-sdk-walmart</module>
        <module>erp-sdk-shopee</module>
        <module>erp-sdk-goodcang</module>
    </modules>

    <profiles>
        <profile>
            <id>dev</id>
            <properties>
                <repository.id>snapshot-test</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-test/</repository.url>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>test</id>
            <properties>
                <repository.id>snapshot-test</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-test/</repository.url>
            </properties>
        </profile>
        <profile>
            <id>uat</id>
            <properties>
                <repository.id>snapshot-test</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-test/</repository.url>
            </properties>
        </profile>
        <profile>
            <id>prod</id>
            <properties>
                <repository.id>snapshot-prod</repository.id>
                <repository.url>http://172.16.100.11:8089/repository/snapshot-prod/</repository.url>
            </properties>
        </profile>
    </profiles>
    <distributionManagement>
        <snapshotRepository>
            <id>${repository.id}</id>
            <url>${repository.url}</url>
        </snapshotRepository>
    </distributionManagement>

</project>