package com.common.business.enums;

import com.common.core.constant.EnumMessage;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum FileTaskEventEnum implements EnumMessage {
    //bi  暂时不改
    EXPORT_SKU_SALES("EXPORT_SKU_SALES", "sku销售额","","",""),
    EXPORT_BI_ORDER_INFO("EXPORT_BI_ORDER_INFO", "销售数据","","",""),
    EXPORT_BI_RETURN_ORDER_INFO("EXPORT_BI_RETURN_ORDER_INFO", "退货数据","","",""),
    EXPORT_BI_RETURN_INFO("EXPORT_BI_RETURN_INFO", "退款数据导出","","",""),
    EXPORT_BI_DATA_SOURCE_COST("EXPORT_BI_DATA_SOURCE_COST", "成本数据表导出","","",""),
    EXPORT_BI_SHOP_INFO("EXPORT_BI_SHOP_INFO", "店铺数据导出","","",""),
    EXPORT_BI_DATA_SOURCE_CUSTOM("EXPORT_BI_DATA_SOURCE_CUSTOM", "数据分析导出","","",""),
    EXPORT_BI_DATA_SOURCE_CUSTOM_MARKET("EXPORT_BI_DATA_SOURCE_CUSTOM_MARKET", "市场数据导出","","",""),
    EXPORT_BI_DATA_SOURCE_CUSTOM_SUPPLY_CHAIN("EXPORT_BI_DATA_SOURCE_CUSTOM_SUPPLY_CHAIN", "供应链数据导出","","",""),
    EXPORT_BI_DATA_SOURCE_CUSTOM_OPERATE("EXPORT_BI_DATA_SOURCE_CUSTOM_OPERATE", "经营数据导出","","",""),
    EXPORT_BI_DATA_SOURCE_CUSTOM_FINANCE("EXPORT_BI_DATA_SOURCE_CUSTOM_FINANCE", "财务数据导出","","",""),
    EXPORT_BI_TARGET_CATEGORY_SETTING("EXPORT_BI_TARGET_CATEGORY_SETTING", "按品类导出目标报表","","",""),
    EXPORT_BI_TARGET_NEW_PRODUCT_SETTING("EXPORT_BI_TARGET_NEW_PRODUCT_SETTING", "按新品导出目标报表","","",""),
    EXPORT_BI_TARGET_SHOP_SETTING("EXPORT_BI_TARGET_SHOP_SETTING", "按店铺导出目标报表","","",""),
    EXPORT_BI_TARGET_SKU_SETTING("EXPORT_BI_TARGET_SKU_SETTING", "按SKU导出目标报表","","",""),
    EXPORT_BI_TARGET_STAFF_SETTING("EXPORT_BI_TARGET_STAFF_SETTING", "按人员导出目标报表","","",""),
    EXPORT_BI_COUNTRY_SALES("EXPORT_BI_COUNTRY_SALES", "区域国家销售额数据","","",""),
    EXPORT_BI_NEW_AND_OLD_SALES_EXPORT("EXPORT_BI_NEW_AND_OLD_SALES_EXPORT", "新老品销售额","","",""),
    EXPORT_BI_REPORT("EXPORT_BI_REPORT", "新老品销售额报表","","",""),

    //dmp
    EXPORT_PUSH_TASK_HISTORY("EXPORT_PUSH_TASK_HISTORY","中台推送任务历史表","","",""),
    EXPORT_PULL_TASK_HISTORY("EXPORT_PULL_TASK_HISTORY","中台拉取任务历史表","","",""),
    EXPORT_PUSH_TASK("EXPORT_PUSH_TASK","中台推送任务表","","",""),
    EXPORT_PULL_TASK("EXPORT_PULL_TASK","中台拉取任务表","","",""),
    EXPORT_NEW_DMP_PUSH_TASK("EXPORT_NEW_DMP_PUSH_TASK","中台推送任务表","","",""),
    EXPORT_DMP_AFTER_SALE("EXPORT_DMP_AFTER_SALE","售后申请表","","",""),

    //plm
    EXPORT_PLM_BOM("EXPORT_PLM_BOM", "BOM数据","","",""),
    EXPORT_PLM_PRODUCT_CERTIFICATE("EXPORT_PLM_PRODUCT_CERTIFICATE", "产品认证列表","","",""),
    EXPORT_PLM_TASK("EXPORT_PLM_TASK", "产品任务列表","","",""),
    EXPORT_PLM_PRODUCT_DETAIL("EXPORT_PLM_PRODUCT_DETAIL", "产品明细","","",""),
    EXPORT_PLM_SCHEDULE_TASK("EXPORT_PLM_SCHEDULE_TASK", "项目计划","","",""),
    EXPORT_PLM_TASK_TIME_RECORD("EXPORT_PLM_TASK_TIME_RECORD", "工时统计","","",""),
    EXPORT_PLM_LOGISTICS_PRODUCT("EXPORT_PLM_LOGISTICS_PRODUCT", "物流产品列表","","",""),
    EXPORT_PLM_PRODUCT_ALL("EXPORT_PLM_PRODUCT_ALL", "产品列表/任务列表","","",""),
    EXPORT_PLM_PRODUCT_MY_PROJECT("EXPORT_PLM_PRODUCT_MY_PROJECT", "产品列表/任务列表","","",""),
    EXPORT_PLM_PRODUCT_COLLECT("EXPORT_PLM_PRODUCT_COLLECT", "产品列表/任务列表","","",""),
    EXPORT_PLM_PRODUCT_PLAN("EXPORT_PLM_PRODUCT_PLAN", "产品规划","","",""),
    EXPORT_PLM_PROJECT_REPORT_PURCHASE_BUSINESS("EXPORT_PLM_PROJECT_REPORT_PURCHASE_BUSINESS", "项目报表","","",""),
    EXPORT_PLM_PROJECT_REPORT_TASK_DETAIL("EXPORT_PLM_PROJECT_REPORT_TASK_DETAIL", "项目任务明细","","",""),
    EXPORT_PLM_TASK_VIEW("EXPORT_PLM_TASK_VIEW", "产品明细","","",""),
    EXPORT_PLM_PILOT_APPLICATION("EXPORT_PLM_PILOT_APPLICATION", "试产量产单","","",""),
    EXPORT_PLM_MOULD_INFO("EXPORT_PLM_MOULD_INFO", "模具管理导出","","",""),
    EXPORT_PLM_ORDER_TRACKING("EXPORT_PLM_ORDER_TRACKING", "下单跟踪导出","","",""),
    EXPORT_PLM_ORDER_TRACKING_DETAIL("EXPORT_PLM_ORDER_TRACKING_DETAIL", "下单跟踪明细导出","","",""),
    EXPORT_PLM_PRODUCT("EXPORT_PLM_PRODUCT", "产品开发","","",""),
    EXPORT_PLM_SKU("EXPORT_PLM_SKU", "产品管理导出","","",""),
    IMPORT_PLM_SKU_IMAGES("IMPORT_PLM_SKU_IMAGES", "导入SKU图片","com.erp.rpc.plm.feign.ImportPlmFeign","productDetailImages",""),
    EXPORT_PLM_PRODUCT_CUSTOMS("EXPORT_PLM_PRODUCT_CUSTOMS", "目的国清关导出","","",""),
    EXPORT_PLM_SKU_STD_COST("EXPORT_PLM_SKU_STD_COST", "SKU标准成本导出","","",""),
    IMPORT_PLM_SKU_STD_COST("IMPORT_PLM_SKU_STD_COST", "SKU标准成本导入","com.erp.rpc.plm.feign.ImportPlmFeign","skuStdCostDetail",""),
    EXPORT_PLM_MOLD_INFO("EXPORT_PLM_MOLD_INFO", "模具档案导出","","",""),
    IMPORT_PLM_MOLD_INFO("IMPORT_PLM_MOLD_INFO", "模具档案导入","com.erp.rpc.plm.feign.ImportPlmFeign","importMoldInfo",""),
    EXPORT_PLM_MOLD_REF_SKU("EXPORT_PLM_MOLD_REF_SKU", "模具关联SKU导出","","",""),
    IMPORT_PLM_MOLD_REF_SKU("IMPORT_PLM_MOLD_REF_SKU", "模具关联SKU导入","com.erp.rpc.plm.feign.ImportPlmFeign","importMoldRefSku",""),
    EXPORT_PLM_CFG_MOLD_RETURN("EXPORT_PLM_CFG_MOLD_RETURN", "模具返还策略导出","","",""),
    IMPORT_PLM_CFG_MOLD_RETURN("IMPORT_PLM_CFG_MOLD_RETURN", "模具返还策略导入","com.erp.rpc.plm.feign.ImportPlmFeign","importCfgMoldReturn",""),
    EXPORT_PLM_CFG_MOLD_ALERT("EXPORT_PLM_CFG_MOLD_ALERT", "模具预警策略导出","","",""),
    IMPORT_PLM_CFG_MOLD_ALERT("IMPORT_PLM_CFG_MOLD_ALERT", "模具预警策略导入","com.erp.rpc.plm.feign.ImportPlmFeign","importCfgMoldAlert",""),
    EXPORT_PLM_MOLD_MONITOR_RETURN("EXPORT_PLM_MOLD_MONITOR_RETURN", "模具返还监控导出","","",""),
    EXPORT_PLM_MOLD_MONITOR_ALERT("EXPORT_PLM_MOLD_MONITOR_ALERT", "模具预警监控导出","","",""),

    EXPORT_PLM_ASSET_NOTICE("EXPORT_PLM_ASSET_NOTICE","资产通知单导出","","",""),
    IMPORT_PLM_ASSET_NOTICE("IMPORT_PLM_ASSET_NOTICE","资产通知单导入","com.erp.rpc.plm.feign.ImportPlmFeign","importAssetNotice",""),
    EXPORT_PLM_ASSET_PURCHASE_ORDER("EXPORT_PLM_ASSET_PURCHASE_ORDER","资产采购单导出","","",""),
    IMPORT_PLM_ASSET_PURCHASE_ORDER("IMPORT_PLM_ASSET_PURCHASE_ORDER","资产采购单导入","com.erp.rpc.plm.feign.ImportPlmFeign","importAssetPurchaseOrder",""),
    EXPORT_PLM_ASSET_PURCHASE_CHANGE("EXPORT_PLM_ASSET_PURCHASE_CHANGE","资产采购变更单导出","","",""),

    //oms
    EXPORT_OMS_CUSTOMER_B2B_SELLER_CHANGE("EXPORT_OMS_CUSTOMER_B2B_SELLER_CHANGE","客户b2b销售变更单","","",""),
    EXPORT_OMS_SO_CHANGE("EXPORT_OMS_SO_CHANGE","销售变更单列表","","",""),
    EXPORT_OMS_SO_PI("EXPORT_OMS_SO_PI","销售单发票信息","","",""),
    EXPORT_OMS_SO_DOMESTIC_PI("EXPORT_OMS_SO_DOMESTIC_PI","销售单国内发票信息","","",""),
    EXPORT_OMS_SO_RETURN("EXPORT_OMS_SO_RETURN","销售退货订单","","",""),
    EXPORT_OMS_SO_B2C_RETURN("EXPORT_OMS_SO_B2C_RETURN","b2c销售退货订单","","",""),
    EXPORT_OMS_SO("EXPORT_OMS_SO","B2B销售订单","","",""),
    EXPORT_OMS_SO_RECEIPT("EXPORT_OMS_SO_RECEIPT","收款单","","",""),
    EXPORT_OMS_SO_B2C_ABNORMAL("EXPORT_OMS_SO_B2C_ABNORMAL","B2C异常销售订单","","",""),
    EXPORT_OMS_SO_B2C_ABNORMAL_POOLS("EXPORT_OMS_SO_B2C_ABNORMAL_POOLS","B2C异常订单错误池","","",""),
    EXPORT_OMS_SO_B2C("EXPORT_OMS_SO_B2C","B2C销售订单","","",""),
    EXPORT_OMS_FULLY_MANAGED("EXPORT_OMS_FULLY_MANAGED","全托管销售订单","","",""),
    EXPORT_OMS_SO_B2C_DECLARE("EXPORT_OMS_SO_B2C_DECLARE","申报信息","","",""),
    EXPORT_OMS_SO_B2C_PRODUCT_SALES("EXPORT_OMS_SO_B2C_PRODUCT_SALES","产品销售统计","","",""),
    EXPORT_OMS_PLATFORM_SKU("EXPORT_OMS_PLATFORM_SKU","b2c平台sku对照列表","","",""),
    EXPORT_OMS_WAREHOUSE_SKU("EXPORT_OMS_WAREHOUSE_SKU","sku对照列表","","",""),
    EXPORT_OMS_LISTING_PUSH("EXPORT_OMS_LISTING_PUSH","sku对照表推送记录","","",""),
    EXPORT_OMS_CUSTOMER_SKU("EXPORT_OMS_CUSTOMER_SKU","客户sku对照列表","","",""),
    EXPORT_OMS_SHOP("EXPORT_OMS_SHOP","店铺导出","","",""),
    EXPORT_OMS_CUSTOMER("EXPORT_OMS_CUSTOMER","客户列表","","",""),
    EXPORT_INVOICE_INFO("EXPORT_INVOICE_INFO","发票管理","","",""),
    EXPORT_INVOICE_INVALID("EXPORT_INVOICE_INVALID","作废发票号","","",""),
    EXPORT_SO_PRICE("EXPORT_SO_PRICE","销售价目数据","","",""),
    EXPORT_SO_PRICE_CHANGE("EXPORT_SO_PRICE_CHANGE","销售调价数据","","",""),
    EXPORT_OMS_B2B_PLATFORM_SKU("EXPORT_OMS_B2B_PLATFORM_SKU","b2b平台sku对照列表","","",""),
    EXPORT_SO_MULTI_CHANNEL("EXPORT_SO_MULTI_CHANNEL","多渠道订单数据","","",""),

    EXPORT_OMS_EXHIBITION_ORDER("EXPORT_OMS_EXHIBITION_ORDER", "展会订单导出","","",""),
    IMPORT_OMS_EXHIBITION_ORDER("IMPORT_OMS_EXHIBITION_ORDER","展会订单导入","com.erp.rpc.oms.feign.ImportOmsFeign","importExhibitionOrder",""),

    //scm
    EXPORT_SCM_SUPPLIER_USER("EXPORT_SCM_SUPPLIER_USER","供应商协同用户列表","","",""),
    EXPORT_SCM_PURCHASE_PRICE_CHANGE("EXPORT_SCM_PURCHASE_PRICE_CHANGE","采购调价数据","","",""),
    EXPORT_SCM_PURCHASE_CHANGE("EXPORT_SCM_PURCHASE_CHANGE","采购变更数据","","",""),
    EXPORT_SCM_PURCHASE_ORDER("EXPORT_SCM_PURCHASE_ORDER","采购订单数据","","",""),
    EXPORT_SCM_PURCHASE_ORDER_CONTRACT("EXPORT_SCM_PURCHASE_ORDER_CONTRACT","采购单网采合同","","",""),
    EXPORT_SCM_PURCHASE_APPLICATION("EXPORT_SCM_PURCHASE_APPLICATION","采购申请单数据","","",""),
    EXPORT_SCM_SALES_DEMAND("EXPORT_SCM_SALES_DEMAND","备货申请单数据","","",""),
    EXPORT_SCM_SUBCONTRACT_CHANGE_ORDER("EXPORT_SCM_SUBCONTRACT_CHANGE_ORDER","委外变更单导出","","",""),
    EXPORT_SCM_PURCHASE_PRICE("EXPORT_SCM_PURCHASE_PRICE","采购价目数据","","",""),
    EXPORT_SCM_SUPPLIER("EXPORT_SCM_SUPPLIER","供应商数据","","",""),
    EXPORT_SCM_SUPPLIER_REPORT("EXPORT_SCM_SUPPLIER_REPORT","供应商报表导出","","",""),
    EXPORT_SCM_CFG_SUPPLIER_SALES_REPORT("EXPORT_SCM_CFG_SUPPLIER_SALES_REPORT","销量配置导出","","",""),
    EXPORT_SCM_SUPPLIER_REF_WAREHOUSE("EXPORT_SCM_SUPPLIER_REF_WAREHOUSE","仓库绑定导出","","",""),
    EXPORT_SCM_SUPPLIER_CREDENTIAL_REPORT("EXPORT_SCM_SUPPLIER_CREDENTIAL_REPORT","供应商证照管理导出","","",""),
    EXPORT_SCM_SUPPLIER_VISIT_REPORT("EXPORT_SCM_SUPPLIER_VISIT_REPORT","供应商现场考察导出","","",""),
    EXPORT_SCM_CONTRACT_INFO_REPORT("EXPORT_SCM_CONTRACT_INFO_REPORT","合同管理单导出","","",""),
    EXPORT_SCM_DYNAMIC_SUPPLIER("EXPORT_SCM_DYNAMIC_SUPPLIER","供应商数据","","",""),
    EXPORT_SCM_SUPPLIER_PHASE("EXPORT_SCM_SUPPLIER_PHASE","供应商阶段数据","","",""),
    EXPORT_SCM_DYNAMIC_SUPPLIER_PHASE("EXPORT_SCM_DYNAMIC_SUPPLIER_PHASE","供应商阶段数据","","",""),
    EXPORT_SCM_PURCHASE_ORDER_ADJUST("EXPORT_SCM_PURCHASE_ORDER_ADJUST","历史未完结订单","","",""),
    EXPORT_SCM_PO_RECONCILIATION_DETAIL("EXPORT_SCM_PO_RECONCILIATION_DETAIL","采购对账单-明细数据导出","","",""),

    //srm
    EXPORT_SRM_SALES_SHARING_REPORT("EXPORT_SRM_SALES_SHARING_REPORT","销量共享导出","","",""),

    //SCM
    EXPORT_SRM_PO_RECONCILIATION_SCM("EXPORT_SRM_PO_RECONCILIATION_SCM","对账单导出","","",""),
    EXPORT_SRM_PO_RECONCILIATION_SCM_EXPORT("EXPORT_SRM_PO_RECONCILIATION_SCM_EXPORT","对账单Excel导出","","",""),
    EXPORT_SRM_PO_RECONCILIATION_DETAIL_SCM("EXPORT_SRM_PO_RECONCILIATION_DETAIL_SCM","对账明细导出","","",""),

    //sys
    EXPORT_SYS_CITY("EXPORT_SYS_CITY","城市Excel导出","","",""),
    EXPORT_SYS_COUNTRY("EXPORT_SYS_COUNTRY","国家Excel导出","","",""),
    EXPORT_SYS_CITY_PROVINCE("EXPORT_SYS_CITY_PROVINCE","省份Excel导出","","",""),
    EXPORT_SYS_GLOBAL_AREA("EXPORT_SYS_GLOBAL_AREA","区域Excel导出","","",""),
    EXPORT_SYS_THIRD_NOTICE("EXPORT_SYS_THIRD_NOTICE", "三方通知配置导出","","",""),
    EXPORT_SYS_THIRD_NOTICE_RECORD("EXPORT_SYS_THIRD_NOTICE_RECORD", "三方通知推送导出","","",""),
    //wms
    EXPORT_WMS_INVENTORY("EXPORT_WMS_INVENTORY","即时库存导出","","",""),
    EXPORT_WMS_B2C_DELIVERY_ORDER("EXPORT_WMS_B2C_DELIVERY_ORDER", "发货单导出","","",""),
    EXPORT_WMS_PACKAGE_FORECAST("EXPORT_WMS_PACKAGE_FORECAST", "组包预报列表","","",""),
    EXPORT_WMS_WAREHOUSE_LOCATION("EXPORT_WMS_WAREHOUSE_LOCATION", "仓位数据导出","","",""),
    EXPORT_WMS_REQUISITION_APPLICATION("EXPORT_WMS_REQUISITION_APPLICATION", "要货申请单导出","","",""),
    EXPORT_WMS_REQUISITION_APPLICATION_CHANGE("EXPORT_WMS_REQUISITION_APPLICATION_CHANGE", "要货申请变更单导出","","",""),
    EXPORT_WMS_WAREHOUSE_LOCATION_SAFETY_INVENTORY("EXPORT_WMS_WAREHOUSE_LOCATION_SAFETY_INVENTORY", "仓位安全库存","","",""),
    EXPORT_WMS_VIRTUAL_INVENTORY_DIFF("EXPORT_WMS_VIRTUAL_INVENTORY_DIFF", "库存差异列表信息","","",""),
    EXPORT_WMS_VIRTUAL_WAREHOUSE_ALLOCATION("EXPORT_WMS_VIRTUAL_WAREHOUSE_ALLOCATION", "分货单导出","","",""),
    EXPORT_WMS_ALIEXPRESS_DELIVERY_EXPORT("EXPORT_WMS_ALIEXPRESS_DELIVERY_EXPORT", "速卖通发货单","","",""),
    EXPORT_WMS_VIRTUAL_TRANS_FLOW("EXPORT_WMS_VIRTUAL_TRANS_FLOW", "虚拟库存流水列表信息","","",""),
    EXPORT_WMS_VIRTUAL_INVENTORY("EXPORT_WMS_VIRTUAL_INVENTORY", "虚拟仓库库存信息","","",""),
    EXPORT_WMS_SO_DELIVERY_NOTICE("EXPORT_WMS_SO_DELIVERY_NOTICE", "销售发货通知单","","",""),
    EXPORT_WMS_SO_DELIVERY_NOTICE_CHANGE("EXPORT_WMS_SO_DELIVERY_NOTICE_CHANGE", "销售发货通知变更单","","",""),
    EXPORT_WMS_FBA_DELIVERY("EXPORT_WMS_FBA_DELIVERY", "发货单导出","","",""),
    EXPORT_WMS_OVERSEAS_WAREHOUSE_INBOUND("EXPORT_WMS_OVERSEAS_WAREHOUSE_INBOUND", "海外入库单数据","","",""),
    EXPORT_WMS_OVERSEAS_DELIVERY_PLAN("EXPORT_WMS_OVERSEAS_DELIVERY_PLAN", "发货计划导出","","",""),
    EXPORT_WMS_PICKING_LISTS("EXPORT_WMS_PICKING_LISTS", "拣货单","","",""),
    EXPORT_WMS_FBA_SHIPMENT("EXPORT_WMS_FBA_SHIPMENT", "FBA货件导出","","",""),
    EXPORT_WMS_FBA_SHIPMENT_PACKING("EXPORT_WMS_FBA_SHIPMENT_PACKING", "FBA货件装箱导出","","",""),
    EXPORT_WMS_STOCKTAKING_PROFIT_LOSS("EXPORT_WMS_STOCKTAKING_PROFIT_LOSS", "盘盈盘亏单","","",""),
    EXPORT_WMS_STOCKTAKING_TASK_DETAIL("EXPORT_WMS_STOCKTAKING_TASK_DETAIL", "盘点任务明细列表","","",""),
    EXPORT_WMS_INVENTORY_TRANS_FLOW("EXPORT_WMS_INVENTORY_TRANS_FLOW", "库存流水明细导出","","",""),
    EXPORT_WMS_INVENTORY_DAILY("EXPORT_WMS_INVENTORY_DAILY", "每日库存导出","","",""),
    EXPORT_WMS_INIT_STOCK("EXPORT_WMS_INIT_STOCK", "期初库存数据","","",""),
    EXPORT_WMS_FBA_INVENTORY("EXPORT_WMS_FBA_INVENTORY", "FBA库存导出","","",""),
    EXPORT_WMS_OVERSEAS_INVENTORY("EXPORT_WMS_OVERSEAS_INVENTORY", "海外仓库数据","","",""),
    EXPORT_WMS_MACHINE_INFO("EXPORT_WMS_MACHINE_INFO", "加工单导出","","",""),
    EXPORT_WMS_OTHER_OUT_STOCK("EXPORT_WMS_OTHER_OUT_STOCK", "其他出库单导出","","",""),
    EXPORT_WMS_OTHER_IN_STOCK("EXPORT_WMS_OTHER_IN_STOCK", "其他入库单导出","","",""),
    EXPORT_WMS_PACKING_TASK("EXPORT_WMS_PACKING_TASK", "装箱任务导出","","",""),
    EXPORT_WMS_PACKING_TASK_DETAIL("EXPORT_WMS_PACKING_TASK_DETAIL", "装箱清单导出(同箱规不合并)","","",""),
    EXPORT_WMS_PACKING_TASK_DETAIL_MERGE("EXPORT_WMS_PACKING_TASK_DETAIL_MERGE", "装箱清单导出(同箱规合并)","","",""),
    EXPORT_WMS_UN_PACKING_TASK_DETAIL("EXPORT_WMS_UN_PACKING_TASK_DETAIL", "未装箱明细导出","","",""),
    EXPORT_WMS_FIRST_MILE_PACKING_TASK_DETAIL("EXPORT_WMS_FIRST_MILE_PACKING_TASK_DETAIL", "发货单装箱清单导出","","",""),
    EXPORT_WMS_FIRST_MILE_PACKING_BOX("EXPORT_WMS_FIRST_MILE_PACKING_BOX", "箱号对照表清单导出","","",""),
    EXPORT_WMS_WAREHOUSE_LOCATION_REPLENISH("EXPORT_WMS_WAREHOUSE_LOCATION_REPLENISH", "仓位补货","","",""),
    EXPORT_WMS_DAILY_QC_BILL("EXPORT_WMS_DAILY_QC_BILL", "质检日报数据","","",""),
    EXPORT_WMS_QC_BILL("EXPORT_WMS_QC_BILL", "质检单数据","","",""),
    EXPORT_WMS_QC_REPORT_DETAIL("EXPORT_WMS_QC_REPORT_DETAIL", "质检报告数据","","",""),
    EXPORT_WMS_QC_EFFECTIVENESS_PERSONNEL("EXPORT_WMS_QC_EFFECTIVENESS_PERSONNEL", "质检报表质检人员","","",""),
    EXPORT_WMS_QC_EFFECTIVENESS_DOCUMENT("EXPORT_WMS_QC_EFFECTIVENESS_DOCUMENT", "质检报表单据","","",""),
    EXPORT_WMS_WAREHOUSE_RECEIVE("EXPORT_WMS_WAREHOUSE_RECEIVE", "仓库收货单","","",""),
    EXPORT_WMS_INVENTORY_TRANSPORT("EXPORT_WMS_INVENTORY_TRANSPORT", "在途库存导出","","",""),
    EXPORT_WMS_INVENTORY_AGE("EXPORT_WMS_INVENTORY_AGE", "库龄计算表数据","","",""),
    EXPORT_WMS_INVENTORY_IN_OUT_STOCK("EXPORT_WMS_INVENTORY_IN_OUT_STOCK", "出入库流水数据","","",""),
    EXPORT_WMS_INVENTORY_IN_OUT_STOCK_SUMMARY("EXPORT_WMS_INVENTORY_IN_OUT_STOCK_SUMMARY", "出入库列表数据","","",""),
    EXPORT_WMS_PURCHASE_BUSINESS("EXPORT_WMS_PURCHASE_BUSINESS", "采购业务汇总表","","",""),
    EXPORT_WMS_PURCHASE_RETURN_ORDER("EXPORT_WMS_PURCHASE_RETURN_ORDER", "退货单","","",""),
    EXPORT_WMS_SO_OUT_STOCK("EXPORT_WMS_SO_OUT_STOCK", "销售订单出库列表","","",""),
    EXPORT_WMS_SO_RETURN_NOTICE("EXPORT_WMS_SO_RETURN_NOTICE", "销售退货通知单","","",""),
    EXPORT_WMS_SO_RETURN_RECEIVE("EXPORT_WMS_SO_RETURN_RECEIVE", "销售退货签收单","","",""),
    EXPORT_WMS_SO_RETURN_IN_STOCK("EXPORT_WMS_SO_RETURN_IN_STOCK", "销售退货入库单","","",""),
    EXPORT_WMS_PO_IN_STOCK("EXPORT_WMS_PO_IN_STOCK", "采购入库单数据","","",""),
    EXPORT_WMS_SUBCONTRACT_ISSUE("EXPORT_WMS_SUBCONTRACT_ISSUE", "委外发料单导出","","",""),
    EXPORT_WMS_SUPPLIER_DELIVERY_ORDER("EXPORT_WMS_SUPPLIER_DELIVERY_ORDER", "供应商送货单","","",""),
    EXPORT_WMS_TRANSFER_APPLICATION("EXPORT_WMS_TRANSFER_APPLICATION", "调拨申请单导出","","",""),
    EXPORT_WMS_TRANSFER_INFO("EXPORT_WMS_TRANSFER_INFO", "直接调拨单导出","","",""),
    EXPORT_WMS_TRANSFER_IN("EXPORT_WMS_TRANSFER_IN", "分布式调入订单列表","","",""),
    EXPORT_WMS_TRANSFER_OUT("EXPORT_WMS_TRANSFER_OUT", "分布式调出订单列表","","",""),
    EXPORT_WMS_PDA_WAREHOUSE_LOCATION_MOVE_INFO("EXPORT_WMS_PDA_WAREHOUSE_LOCATION_MOVE_INFO", "仓库移动导出","","",""),
    EXPORT_WMS_WAREHOUSE("EXPORT_WMS_WAREHOUSE", "仓库数据","","",""),
    EXPORT_WMS_REPORT_ORDER_DEMAND_DETAIL("EXPORT_WMS_REPORT_ORDER_DEMAND_DETAIL", "订单需求明细报表","","",""),
    EXPORT_WMS_REPORT_ORDER_DEMAND("EXPORT_WMS_REPORT_ORDER_DEMAND", "缺货统计报表","","",""),
    EXPORT_WMS_REPORT_ORDER_SALES("EXPORT_WMS_REPORT_ORDER_SALES", "销售看板报表","","",""),
    EXPORT_WMS_REMOTE_POSTCODE("EXPORT_WMS_REMOTE_POSTCODE", "偏远邮编导出","","",""),
    EXPORT_WMS_VIRTUAL_STATISTICS("EXPORT_WMS_VIRTUAL_STATISTICS", "分货统计","","",""),
    EXPORT_WMS_SO_B2B_PROCESSING("EXPORT_WMS_SO_B2B_PROCESSING", "b2b虚拟仓订单","","",""),
    EXPORT_WMS_SO_B2C_PROCESSING("EXPORT_WMS_SO_B2C_PROCESSING", "b2c虚拟仓订单","","",""),
    EXPORT_WMS_FIRST_MILE_PROCESSING("EXPORT_WMS_FIRST_MILE_PROCESSING", "头程虚拟仓订单","","",""),
    EXPORT_WMS_SAMPLE_RECIPIENT("EXPORT_WMS_SAMPLE_RECIPIENT","样品领用单","com.erp.rpc.tms.feign.ImportTmsFeign","",""),
    IMPORT_WMS_SAMPLE_RECIPIENT("IMPORT_WMS_SAMPLE_RECIPIENT","导入样品领用单","com.erp.rpc.wms.feign.ImportWmsFeign","importSampleRecipient",""),



    EXPORT_WMS_VIRTUAL_INVENTORY_AGE("EXPORT_WMS_VIRTUAL_INVENTORY_AGE", "库龄分析","","",""),
    EXPORT_WMS_VIRTUAL_HIS_INVENTORY_AGE("EXPORT_WMS_VIRTUAL_HIS_INVENTORY_AGE", "历史库龄","","",""),
    EXPORT_WMS_VIRTUAL_HIS_INVENTORY_AGE_DETAIL("EXPORT_WMS_VIRTUAL_HIS_INVENTORY_AGE_DETAIL", "历史库龄明细","","",""),
    EXPORT_WMS_VIRTUAL_TRANS_FLOW_DETAIL("EXPORT_WMS_VIRTUAL_TRANS_FLOW_DETAIL", "库龄流水","","",""),
    EXPORT_WMS_FRAME_VIRTUAL_HIS_INVENTORY_AGE_DETAIL("EXPORT_WMS_FRAME_VIRTUAL_HIS_INVENTORY_AGE_DETAIL", "列表历史库龄明细","","",""),

    EXPORT_WMS_FBA_TRANSIT_REPORT("EXPORT_WMS_FBA_TRANSIT_REPORT", "FBA在途核对列表导出","","",""),
    EXPORT_WMS_VIRTUAL_WAREHOUSE_REPORT("EXPORT_WMS_VIRTUAL_WAREHOUSE_REPORT", "虚拟仓库设置导出","","",""),
    EXPORT_WMS_QC_NOTICE_REPORT("EXPORT_WMS_QC_NOTICE_REPORT", "质检通知单导出","","",""),
    EXPORT_WMS_VIRTUAL_ADJUST_REPORT("EXPORT_WMS_VIRTUAL_ADJUST_REPORT", "虚拟库存调整导出","","",""),
    EXPORT_WMS_THIRD_WAREHOUSE_DELIVERY_REPORT("EXPORT_WMS_THIRD_WAREHOUSE_DELIVERY_REPORT", "三方仓发货单导出","","",""),
    EXPORT_WMS_B2B_TOTAL_PROCESSING_EXPORT("EXPORT_WMS_B2B_TOTAL_PROCESSING_EXPORT", "b2b冻结订单汇总导出","","",""),
    EXPORT_WMS_B2C_TOTAL_PROCESSING_EXPORT("EXPORT_WMS_B2C_TOTAL_PROCESSING_EXPORT", "b2c冻结订单汇总导出","","",""),
    EXPORT_WMS_FIRST_MILE_TOTAL_PROCESSING_EXPORT("EXPORT_WMS_FIRST_MILE_TOTAL_PROCESSING_EXPORT", "头程冻结订单汇总导出","","",""),




    EXPORT_WMS_SAMPLE_BORROW_INFO("EXPORT_WMS_SAMPLE_BORROW_INFO", "样品借出单导出","","",""),
    IMPORT_WMS_SAMPLE_BORROW_INFO("IMPORT_WMS_SAMPLE_BORROW_INFO","样品借出单导入","com.erp.rpc.wms.feign.ImportWmsFeign","importSampleBorrow",""),
    EXPORT_WMS_SAMPLE_RETURN_INFO("EXPORT_WMS_SAMPLE_RETURN_INFO", "样品归还单导出","","",""),
    EXPORT_WMS_SAMPLE_SCRAP_INFO("EXPORT_WMS_SAMPLE_SCRAP_INFO", "样品报废单导出","","",""),
    IMPORT_WMS_SAMPLE_SCRAP_INFO("IMPORT_WMS_SAMPLE_SCRAP_INFO","样品报废单导入","com.erp.rpc.wms.feign.ImportWmsFeign","importSampleScrap",""),

    EXPORT_WMS_SAMPLE_RECIPIENT_REPORT("EXPORT_WMS_SAMPLE_RECIPIENT_REPORT", "样品领用单导出","","",""),
    EXPORT_WMS_SAMPLE_LEDGER_REPORT("EXPORT_WMS_SAMPLE_LEDGER_REPORT", "样品台账导出","","",""),
    EXPORT_WMS_SAMPLE_LEDGER_FLOW_REPORT("EXPORT_WMS_SAMPLE_LEDGER_FLOW_REPORT", "样品台账流水导出","","",""),
    EXPORT_WMS_SAMPLE_BACK_INFO_REPORT("EXPORT_WMS_SAMPLE_BACK_INFO_REPORT", "样品退回单导出","","",""),
    IMPORT_WMS_SAMPLE_BACK_INFO("IMPORT_WMS_SAMPLE_BACK_INFO","导入样品退回单","com.erp.rpc.wms.feign.ImportWmsFeign","importSampleBackInfo",""),
    EXPORT_WMS_SAMPLE_INITIAL_LEDGER_REPORT("EXPORT_WMS_SAMPLE_INITIAL_LEDGER_REPORT", "样品期初台账导出","","",""),
    IMPORT_WMS_SAMPLE_INITIAL_LEDGER("IMPORT_WMS_SAMPLE_INITIAL_LEDGER","样品期初台账导入","com.erp.rpc.wms.feign.ImportWmsFeign","importSampleInitialLedger",""),


    //tms
    EXPORT_TMS_LOGISTICS_ADDRESS("EXPORT_TMS_LOGISTICS_ADDRESS", "物流地址列表","","",""),
    EXPORT_TMS_LOGISTICS_SUPPLIER("EXPORT_TMS_LOGISTICS_SUPPLIER", "物流商列表","","",""),
    EXPORT_TMS_SHIPPING_TEMPLATE("EXPORT_TMS_SHIPPING_TEMPLATE", "运费模板列表","","",""),
    EXPORT_TMS_TMS_WAREHOUSE_MAPPING("EXPORT_TMS_TMS_WAREHOUSE_MAPPING", "仓库匹配列表","","",""),
    EXPORT_TMS_TMS_B2B_DECLARE_BILL("EXPORT_TMS_TMS_B2B_DECLARE_BILL", "报关单","","",""),
    EXPORT_TMS_TMS_B2B_DECLARE_DECLARE_BILL("EXPORT_TMS_TMS_B2B_DECLARE_DECLARE_BILL", "B2B报关单导出","","",""),
    EXPORT_TMS_TRANSFER_DECLARE("EXPORT_TMS_TRANSFER_DECLARE", "中转报关单导出","","",""),
    EXPORT_TMS_TRANSFER_LOGISTICS_SUPPLIER("EXPORT_TMS_TRANSFER_LOGISTICS_SUPPLIER", "中转报关服务商列表","","",""),
    EXPORT_TMS_PRODUCT_REGISTRATION("EXPORT_TMS_PRODUCT_REGISTRATION", "备案列表","","",""),
    EXPORT_TMS_TMS_FM_DECLARE_BILL("EXPORT_TMS_TMS_FM_DECLARE_BILL", "报关单","","",""),
    EXPORT_TMS_TMS_FM_DECLARE_BILL_DECLARE("EXPORT_TMS_TMS_FM_DECLARE_BILL_DECLARE", "报关单导出","","",""),
    EXPORT_TMS_CFG_RECONCILIATION_FIELD("EXPORT_TMS_CFG_RECONCILIATION_FIELD", "对账字段配置数据","","",""),
    EXPORT_TMS_TMS_B2C_DECLARE_RECONCILIATION("EXPORT_TMS_TMS_B2C_DECLARE_RECONCILIATION", "b2c报关对账单导出","","",""),
    EXPORT_TMS_TMS_B2C_DECLARE_RECONCILIATION_DETAIL("EXPORT_TMS_TMS_B2C_DECLARE_RECONCILIATION_DETAIL", "b2c报关对账单明细导出","","",""),
    EXPORT_TMS_TMS_FIRST_MILE_RECONCILIATION("EXPORT_TMS_TMS_FIRST_MILE_RECONCILIATION", "头程对账单导出","","",""),
    EXPORT_TMS_TMS_FIRST_MILE_RECONCILIATION_DETAIL("EXPORT_TMS_TMS_FIRST_MILE_RECONCILIATION_DETAIL", "头程对账单明细导出","","",""),
    EXPORT_TMS_LOGISTICS_LAST_MILE_COST("EXPORT_TMS_LOGISTICS_LAST_MILE_COST", "尾程费用列表","","",""),
    EXPORT_TMS_LOGISTICS_BILL_COST("EXPORT_TMS_LOGISTICS_BILL_COST", "自发货列表","","",""),
    EXPORT_SMALL_BAG_COST_ALLOCATION("EXPORT_SMALL_BAG_COST_ALLOCATION", "小包费用分摊列表","","",""),
    EXPORT_TRANSFER_DECLARE_COST_ALLOCATION("EXPORT_TRANSFER_DECLARE_COST_ALLOCATION", "中转费用分摊列表","","",""),
    EXPORT_TMS_SHIPPING_CALCULATION("EXPORT_TMS_SHIPPING_CALCULATION", "运费计算列表","","",""),
    EXPORT_TMS_LOGISTICS_BILL("EXPORT_TMS_LOGISTICS_BILL", "自发货物流单列表","","",""),
    EXPORT_WMS_SUBCONTRACT_RETURN("EXPORT_WMS_SUBCONTRACT_RETURN", "委外退料单导出","","",""),
    EXPORT_TMS_FIRST_MILE_COST_ALLOCATION("EXPORT_TMS_FIRST_MILE_COST_ALLOCATION", "费用分摊明细列表","","",""),
    EXPORT_TMS_INIT_FIRST_MILE_ALLOCATION("EXPORT_TMS_INIT_FIRST_MILE_ALLOCATION", "期初头程分摊列表","","",""),
    EXPORT_TMS_INVENTORY_SKU_COST("EXPORT_TMS_INVENTORY_SKU_COST", "SKU成本列表","","",""),
    EXPORT_TMS_FM_ESTIMATED_BILL("EXPORT_TMS_FM_ESTIMATED_BILL", "头程暂估账单导出","","",""),
    EXPORT_TMS_FM_WEIGHT_ALLOCATION("EXPORT_TMS_FM_WEIGHT_ALLOCATION", "头程重量分摊导出","","",""),
    EXPORT_TMS_LOGISTICS_LARGE("EXPORT_TMS_LOGISTICS_LARGE", "物流大表导出","","",""),
    EXPORT_TMS_FIRST_MILE_CHANGE_RECORD("EXPORT_TMS_FIRST_MILE_CHANGE_RECORD", "头程调整记录导出","","",""),
    EXPORT_TMS_LOGISTICS_THIRD_CHANNEL_REF("EXPORT_TMS_LOGISTICS_THIRD_CHANNEL_REF", "物流-第三方渠道关系表导出","","",""),
    EXPORT_TMS_DICT_HS_CODE("EXPORT_TMS_DICT_HS_CODE", "出口申报要素导出","","",""),
    EXPORT_TMS_CFG_SAILING("EXPORT_TMS_CFG_SAILING", "截单开船导出","","",""),

    IMPORT_TMS_LOGISTICS_BILL_COST("IMPORT_TMS_LOGISTICS_BILL_COST", "导入自发货费用","com.erp.rpc.tms.feign.ImportTmsFeign","importLogisticsBillCost",""),
    IMPORT_TMS_LOGISTICS_LAST_MILE_COST("IMPORT_TMS_LOGISTICS_LAST_MILE_COST", "导入尾程费用","com.erp.rpc.tms.feign.ImportTmsFeign","importLogisticsLastMileCost",""),
    IMPORT_TMS_LOGISTICS_TRACK_INFO("IMPORT_TMS_LOGISTICS_TRACK_INFO", "导入物流单信息","com.erp.rpc.tms.feign.ImportTmsFeign","importLogisticsTrackInfo",""),

    //mrp
    EXPORT_MRP_REPLENISHMENT_RULE("EXPORT_MRP_REPLENISHMENT_RULE", "补货规则","","",""),
    EXPORT_MRP_HISTORY_SALES_QTY("EXPORT_MRP_HISTORY_SALES_QTY", "历史销量","","",""),
    EXPORT_MRP_PURCHASE_SUGGESTION("EXPORT_MRP_PURCHASE_SUGGESTION", "补货计划_采购建议","","",""),
    EXPORT_MRP_FBA_INVENTORY("EXPORT_MRP_FBA_INVENTORY", "FBA每日库存","","",""),
    EXPORT_MRP_OVERSEAS_INVENTORY("EXPORT_MRP_OVERSEAS_INVENTORY", "海外仓每日库存","","",""),
    EXPORT_MRP_LOCAL_INVENTORY("EXPORT_MRP_LOCAL_INVENTORY", "本地仓每日库存","","",""),
    EXPORT_MRP_VIRTUAL_INVENTORY("EXPORT_MRP_VIRTUAL_INVENTORY", "虚拟仓库每日库存信息","","",""),
    EXPORT_MRP_DELIVERY_SUGGESTION("EXPORT_MRP_DELIVERY_SUGGESTION", "补货计划_发货建议","","",""),
    EXPORT_MRP_HISTORY_SALES_CALC("EXPORT_MRP_HISTORY_SALES_CALC", "历史销量导出(销量试算)","","",""),

    EXPORT_MRP_PURCHASE_SUGGESTION_ENTITY("EXPORT_MRP_PURCHASE_SUGGESTION_ENTITY", "采购建议","","",""),
    EXPORT_MRP_PURCHASE_SUGGESTION_MERGE_ENTITY("EXPORT_MRP_PURCHASE_SUGGESTION_MERGE_ENTITY", "采购建议(合并)","","",""),

    EXPORT_MRP_DELIVERY_SUGGESTION_ENTITY("EXPORT_MRP_DELIVERY_SUGGESTION_ENTITY", "补货建议","","",""),

    EXPORT_MRP_SALES_CALC("EXPORT_MRP_SALES_CALC", "销量试算","","",""),
    EXPORT_MRP_SALES_CALC_LIST("EXPORT_MRP_SALES_CALC_LIST", "销量试算任务列表","","",""),
    EXPORT_MRP_SALES_CALC_TEMPLATE_LIST("EXPORT_MRP_SALES_CALC_TEMPLATE_LIST", "销量试算模板列表","","",""),
    EXPORT_MRP_SUGGESTION_CALC_DATA("EXPORT_MRP_SUGGESTION_CALC_DATA", "补货建议计算数据","","",""),


    //workflow
    EXPORT_PROCESS_MANAGEMENT("EXPORT_PROCESS_MANAGEMENT", "流程管理","","",""),
    EXPORT_PROCESS_DEFINITION("EXPORT_PROCESS_DEFINITION", "流程设计记录","","",""),
    EXPORT_PROCESS_DELEGATE("EXPORT_PROCESS_DELEGATE", "委托审批导出","","",""),
    EXPORT_PROCESS_CFG_APPROVE_SYNC("EXPORT_PROCESS_CFG_APPROVE_SYNC", "ERP审批同步配置导出","","",""),
    EXPORT_PROCESS_CFG_PROCESS("EXPORT_PROCESS_CFG_PROCESS","流程配置Excel导出","","",""),
    EXPORT_PROCESS_THIRD_PROCESS("EXPORT_PROCESS_THIRD_PROCESS", "三方审批生成导出","","",""),
    EXPORT_APPROVE_TASK("EXPORT_APPROVE_TASK", "三方生成查询导出","","",""),
    EXPORT_PROCESS_APPROVE_SYNC_RECORD("EXPORT_PROCESS_APPROVE_SYNC_RECORD", "三方推送记录导出","","",""),
    EXPORT_THIRD_PROCESS_DEFINITION("EXPORT_THIRD_PROCESS_DEFINITION", "审批定义导出","","",""),

    //fms
    EXPORT_FMS_ASSET_LOCATION("EXPORT_FMS_ASSET_LOCATION","资产位置导出","","","ExportFmsAssetLocationHandler"),
    EXPORT_FMS_ASSET_ACCEPT_REPORT("EXPORT_FMS_ASSET_ACCEPT_REPORT","资产验收表导出","","","ExportFmsAssetAcceptHandler"),
    EXPORT_FMS_ASSET_CARD("EXPORT_FMS_ASSET_CARD","资产卡片导出","","","ExportFmsAssetCardHandler"),
    EXPORT_FMS_ASSET_STOCKTAKING_PLAN("EXPORT_FMS_ASSET_STOCKTAKING_PLAN","资产盘点方案导出","","","ExportFmsAssetStocktakingPlanHandler"),
    IMPORT_FMS_ASSET_LOCATION("IMPORT_FMS_ASSET_LOCATION","导入资产位置","com.erp.rpc.fms.feign.ImportFmsFeign","importAssetLocation",""),
    IMPORT_FMS_ASSET_ACCEPT("IMPORT_FMS_ASSET_ACCEPT","导入资产验收表","com.erp.rpc.fms.feign.ImportFmsFeign","importAssetAccept",""),
    IMPORT_FMS_ASSET_CARD("IMPORT_FMS_ASSET_CARD","导入资产卡片","com.erp.rpc.fms.feign.ImportFmsFeign","importAssetCard",""),
    IMPORT_FMS_ASSET_STOCKTAKING_PLAN("IMPORT_FMS_ASSET_STOCKTAKING_PLAN","导入资产盘点方案","com.erp.rpc.fms.feign.ImportFmsFeign","importAssetStocktakingPlan",""),

    DEFAULT("DEFAULT", "默认","","","");
    private final String code;
    private final String name;
    private final String className;
    private final String methodName;
    private final String handler;

    @Override
    public String getCode() {
        return code;
    }

    @Override
    public String getName() {
        return name;
    }
    public static FileTaskEventEnum getByCode(String code) {
        for (FileTaskEventEnum eventEnum : FileTaskEventEnum.values()) {
            if (eventEnum.getCode().equals(code)) {
                return eventEnum;
            }
        }
        return null;
    }
}
