package com.common.business.enums;

import com.common.core.constant.EnumMessage;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum FileTaskEventEnum implements EnumMessage {
    //bi
    EXPORT_SKU_SALES("EXPORT_SKU_SALES", "sku销售额"),
    EXPORT_BI_ORDER_INFO("EXPORT_BI_ORDER_INFO", "销售数据"),
    EXPORT_BI_RETURN_ORDER_INFO("EXPORT_BI_RETURN_ORDER_INFO", "退货数据"),
    EXPORT_BI_RETURN_INFO("EXPORT_BI_RETURN_INFO", "退款数据导出"),
//
    EXPORT_BI_DATA_SOURCE_COST("EXPORT_BI_DATA_SOURCE_COST", "成本数据表导出"),
    EXPORT_BI_SHOP_INFO("EXPORT_BI_SHOP_INFO", "店铺数据导出"),
//
    EXPORT_BI_DATA_SOURCE_CUSTOM("EXPORT_BI_DATA_SOURCE_CUSTOM", "数据分析导出"),
    EXPORT_BI_DATA_SOURCE_CUSTOM_MARKET("EXPORT_BI_DATA_SOURCE_CUSTOM_MARKET", "市场数据导出"),
    EXPORT_BI_DATA_SOURCE_CUSTOM_SUPPLY_CHAIN("EXPORT_BI_DATA_SOURCE_CUSTOM_SUPPLY_CHAIN", "供应链数据导出"),
    EXPORT_BI_DATA_SOURCE_CUSTOM_OPERATE("EXPORT_BI_DATA_SOURCE_CUSTOM_OPERATE", "经营数据导出"),
    EXPORT_BI_DATA_SOURCE_CUSTOM_FINANCE("EXPORT_BI_DATA_SOURCE_CUSTOM_FINANCE", "财务数据导出"),
    EXPORT_BI_TARGET_CATEGORY_SETTING("EXPORT_BI_TARGET_CATEGORY_SETTING", "按品类导出目标报表"),
    EXPORT_BI_TARGET_NEW_PRODUCT_SETTING("EXPORT_BI_TARGET_NEW_PRODUCT_SETTING", "按新品导出目标报表"),
    EXPORT_BI_TARGET_SHOP_SETTING("EXPORT_BI_TARGET_SHOP_SETTING", "按店铺导出目标报表"),
    EXPORT_BI_TARGET_SKU_SETTING("EXPORT_BI_TARGET_SKU_SETTING", "按SKU导出目标报表"),
    EXPORT_BI_TARGET_STAFF_SETTING("EXPORT_BI_TARGET_STAFF_SETTING", "按人员导出目标报表"),
    EXPORT_BI_COUNTRY_SALES("EXPORT_BI_COUNTRY_SALES", "区域国家销售额数据"),
    EXPORT_BI_NEW_AND_OLD_SALES_EXPORT("EXPORT_BI_NEW_AND_OLD_SALES_EXPORT", "新老品销售额"),
    EXPORT_BI_REPORT("EXPORT_BI_REPORT", "新老品销售额"),
    //plm
    EXPORT_PLM_BOM("EXPORT_PLM_BOM", "BOM数据"),
    EXPORT_PLM_PRODUCT_CERTIFICATE("EXPORT_PLM_PRODUCT_CERTIFICATE", "产品认证列表"),
    EXPORT_PLM_TASK("EXPORT_PLM_TASK", "产品任务列表"),
    PRODUCT_DETAIL_EXPORT("PRODUCT_DETAIL_EXPORT", "产品明细"),

    //oms
    EXPORT_OMS_CUSTOMER_B2B_SELLER_CHANGE("EXPORT_OMS_CUSTOMER_B2B_SELLER_CHANGE","客户b2b销售变更单"),
    EXPORT_OMS_SO_CHANGE("EXPORT_OMS_SO_CHANGE","销售变更单列表"),
    EXPORT_OMS_SO_PI("EXPORT_OMS_SO_PI","销售单发票信息"),
    EXPORT_OMS_SO_RETURN("EXPORT_OMS_SO_RETURN","销售退货订单"),
    EXPORT_OMS_SO("EXPORT_OMS_SO","销售退货订单"),
    EXPORT_OMS_SO_B2C_ABNORMAL("EXPORT_OMS_SO_B2C_ABNORMAL","B2C异常销售订单"),
    EXPORT_OMS_SO_B2C("EXPORT_OMS_SO_B2C","B2C销售订单"),
    EXPORT_OMS_SO_B2C_DECLARE("EXPORT_OMS_SO_B2C_DECLARE","申报信息"),
    EXPORT_OMS_SO_B2C_PRODUCT_SALES("EXPORT_OMS_SO_B2C_PRODUCT_SALES","产品销售统计"),
    EXPORT_OMS_PLATFORM_SKU("EXPORT_OMS_PLATFORM_SKU","sku对照列表"),
    EXPORT_OMS_WAREHOUSE_SKU("EXPORT_OMS_WAREHOUSE_SKU","sku对照列表"),
    EXPORT_OMS_SHOP("EXPORT_OMS_SHOP","店铺导出"),
    EXPORT_OMS_CUSTOMER("EXPORT_OMS_CUSTOMER","客户列表"),

    //wms
    EXPORT_WMS_INVENTORY("EXPORT_WMS_INVENTORY","即时库存导出"),
    EXPORT_WMS_B2C_DELIVERY_ORDER("EXPORT_WMS_B2C_DELIVERY_ORDER", "发货单导出"),
    EXPORT_WMS_PACKAGE_FORECAST("EXPORT_WMS_PACKAGE_FORECAST", "组包预报列表"),
    EXPORT_WMS_WAREHOUSE_LOCATION("EXPORT_WMS_WAREHOUSE_LOCATION", "仓位数据导出"),
    EXPORT_WMS_REQUISITION_APPLICATION("EXPORT_WMS_REQUISITION_APPLICATION", "要货申请单导出"),
    EXPORT_WMS_WAREHOUSE_LOCATION_SAFETY_INVENTORY("EXPORT_WMS_WAREHOUSE_LOCATION_SAFETY_INVENTORY", "仓位安全库存"),
    EXPORT_WMS_VIRTUAL_INVENTORY_DIFF("EXPORT_WMS_VIRTUAL_INVENTORY_DIFF", "库存差异列表信息"),
    EXPORT_WMS_VIRTUAL_WAREHOUSE_ALLOCATION("EXPORT_WMS_VIRTUAL_WAREHOUSE_ALLOCATION", "分货单导出"),

    EXPORT_WMS_ALIEXPRESS_DELIVERY_EXPORT("EXPORT_WMS_ALIEXPRESS_DELIVERY_EXPORT", "速卖通发货单"),
    EXPORT_WMS_VIRTUAL_TRANS_FLOW("EXPORT_WMS_VIRTUAL_TRANS_FLOW", "虚拟库存流水列表信息"),
    EXPORT_WMS_VIRTUAL_INVENTORY("EXPORT_WMS_VIRTUAL_INVENTORY", "虚拟仓库库存信息"),
    EXPORT_WMS_SO_DELIVERY_NOTICE("EXPORT_WMS_SO_DELIVERY_NOTICE", "销售发货通知单"),
    EXPORT_WMS_FBA_DELIVERY("EXPORT_WMS_FBA_DELIVERY", "发货单导出"),
    EXPORT_WMS_OVERSEAS_WAREHOUSE_INBOUND("EXPORT_WMS_OVERSEAS_WAREHOUSE_INBOUND", "海外入库单数据"),
    EXPORT_WMS_OVERSEAS_DELIVERY_PLAN("EXPORT_WMS_OVERSEAS_DELIVERY_PLAN", "发货计划导出"),
    EXPORT_WMS_PICKING_LISTS("EXPORT_WMS_PICKING_LISTS", "拣货单"),
    EXPORT_WMS_FBA_SHIPMENT("EXPORT_WMS_FBA_SHIPMENT", "FBA货件导出"),
    EXPORT_WMS_STOCKTAKING_PROFIT_LOSS("EXPORT_WMS_STOCKTAKING_PROFIT_LOSS", "盘盈盘亏单"),
    EXPORT_WMS_STOCKTAKING_TASK_DETAIL("EXPORT_WMS_STOCKTAKING_TASK_DETAIL", "盘点任务明细列表"),
    EXPORT_WMS_INVENTORY_TRANS_FLOW("EXPORT_WMS_INVENTORY_TRANS_FLOW", "库存流水明细导出"),
    EXPORT_WMS_INVENTORY_DAILY("EXPORT_WMS_INVENTORY_DAILY", "每日库存导出"),
    EXPORT_WMS_INIT_STOCK("EXPORT_WMS_INIT_STOCK", "期初库存数据"),
    EXPORT_WMS_FBA_INVENTORY("EXPORT_WMS_FBA_INVENTORY", "FBA库存导出"),
    EXPORT_WMS_OVERSEAS_INVENTORY("EXPORT_WMS_OVERSEAS_INVENTORY", "海外仓库数据"),
    EXPORT_WMS_MACHINE_INFO("EXPORT_WMS_MACHINE_INFO", "加工单导出"),
    EXPORT_WMS_OTHER_OUT_STOCK("EXPORT_WMS_OTHER_OUT_STOCK", "其他出库单导出"),
    EXPORT_WMS_OTHER_IN_STOCK("EXPORT_WMS_OTHER_IN_STOCK", "其他入库单导出"),
    EXPORT_WMS_PACKING_TASK("EXPORT_WMS_PACKING_TASK", "装箱任务导出"),
    EXPORT_WMS_PACKING_TASK_DETAIL("EXPORT_WMS_PACKING_TASK_DETAIL", "装箱清单导出"),
    EXPORT_WMS_WAREHOUSE_LOCATION_REPLENISH("EXPORT_WMS_WAREHOUSE_LOCATION_REPLENISH", "仓位补货"),
    EXPORT_WMS_DAILY_QC_BILL("EXPORT_WMS_DAILY_QC_BILL", "质检日报数据"),
    EXPORT_WMS_QC_BILL("EXPORT_WMS_QC_BILL", "质检单数据"),
    EXPORT_WMS_QC_REPORT_DETAIL("EXPORT_WMS_QC_REPORT_DETAIL", "质检报告数据"),
    EXPORT_WMS_QC_EFFECTIVENESS_PERSONNEL("EXPORT_WMS_QC_EFFECTIVENESS_PERSONNEL", "质检报表质检人员"),
    EXPORT_WMS_QC_EFFECTIVENESS_DOCUMENT("EXPORT_WMS_QC_EFFECTIVENESS_DOCUMENT", "质检报表单据"),
    EXPORT_WMS_WAREHOUSE_RECEIVE("EXPORT_WMS_WAREHOUSE_RECEIVE", "仓库收货单"),
    EXPORT_WMS_INVENTORY_TRANSPORT("EXPORT_WMS_INVENTORY_TRANSPORT", "在途库存导出"),
    EXPORT_WMS_INVENTORY_AGE("EXPORT_WMS_INVENTORY_AGE", "库龄计算表数据"),
    EXPORT_WMS_INVENTORY_IN_OUT_STOCK("EXPORT_WMS_INVENTORY_IN_OUT_STOCK", "出入库流水数据"),
    EXPORT_WMS_INVENTORY_IN_OUT_STOCK_SUMMARY("EXPORT_WMS_INVENTORY_IN_OUT_STOCK_SUMMARY", "出入库列表数据"),
    EXPORT_WMS_PURCHASE_BUSINESS("EXPORT_WMS_PURCHASE_BUSINESS", "采购业务汇总表"),
    EXPORT_WMS_PURCHASE_RETURN_ORDER("EXPORT_WMS_PURCHASE_RETURN_ORDER", "退货单"),
    EXPORT_WMS_SO_OUT_STOCK("EXPORT_WMS_SO_OUT_STOCK", "销售订单出库列表"),
    EXPORT_WMS_SO_RETURN_NOTICE("EXPORT_WMS_SO_RETURN_NOTICE", "销售退货通知单"),
    EXPORT_WMS_SO_RETURN_RECEIVE("EXPORT_WMS_SO_RETURN_RECEIVE", "销售退货签收单"),
    EXPORT_WMS_SO_RETURN_IN_STOCK("EXPORT_WMS_SO_RETURN_IN_STOCK", "销售退货入库单"),
    EXPORT_WMS_PO_IN_STOCK("EXPORT_WMS_PO_IN_STOCK", "采购入库单数据"),
    EXPORT_WMS_SUBCONTRACT_ISSUE("EXPORT_WMS_SUBCONTRACT_ISSUE", "委外发料单导出"),
    EXPORT_WMS_SUPPLIER_DELIVERY_ORDER("EXPORT_WMS_SUPPLIER_DELIVERY_ORDER", "供应商送货单"),
    EXPORT_WMS_TRANSFER_APPLICATION("EXPORT_WMS_TRANSFER_APPLICATION", "调拨申请单导出"),
    EXPORT_WMS_TRANSFER_INFO("EXPORT_WMS_TRANSFER_INFO", "直接调拨单导出"),
    EXPORT_WMS_TRANSFER_IN("EXPORT_WMS_TRANSFER_IN", "分布式调入订单列表"),
    EXPORT_WMS_TRANSFER_OUT("EXPORT_WMS_TRANSFER_OUT", "分布式调出订单列表"),
    EXPORT_WMS_PDA_WAREHOUSE_LOCATION_MOVE_INFO("EXPORT_WMS_PDA_WAREHOUSE_LOCATION_MOVE_INFO", "仓库移动导出"),
    EXPORT_WMS_WAREHOUSE("EXPORT_WMS_WAREHOUSE", "仓库数据"),

    //workflow
    PROCESS_MANAGEMENT_EXPORT("PROCESS_MANAGEMENT_EXPORT", "流程管理"),
    DEFAULT("DEFAULT", "默认");
    private final String code;
    private final String name;

    @Override
    public String getCode() {
        return code;
    }

    @Override
    public String getName() {
        return name;
    }

}
