package com.common.business.enums;

import com.common.core.constant.EnumMessage;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum FileTaskEventEnum implements EnumMessage {
    //bi
    EXPORT_SKU_SALES("EXPORT_SKU_SALES", "sku销售额"),
    EXPORT_BI_ORDER_INFO("EXPORT_BI_ORDER_INFO", "销售数据"),
    EXPORT_BI_RETURN_ORDER_INFO("EXPORT_BI_RETURN_ORDER_INFO", "退货数据"),
    EXPORT_BI_RETURN_INFO("EXPORT_BI_RETURN_INFO", "退款数据导出"),
//
    EXPORT_BI_DATA_SOURCE_COST("EXPORT_BI_DATA_SOURCE_COST", "成本数据表导出"),
    EXPORT_BI_SHOP_INFO("EXPORT_BI_SHOP_INFO", "店铺数据导出"),
//
    EXPORT_BI_DATA_SOURCE_CUSTOM("EXPORT_BI_DATA_SOURCE_CUSTOM", "数据分析导出"),
    EXPORT_BI_DATA_SOURCE_CUSTOM_MARKET("EXPORT_BI_DATA_SOURCE_CUSTOM_MARKET", "市场数据导出"),
    EXPORT_BI_DATA_SOURCE_CUSTOM_SUPPLY_CHAIN("EXPORT_BI_DATA_SOURCE_CUSTOM_SUPPLY_CHAIN", "供应链数据导出"),
    EXPORT_BI_DATA_SOURCE_CUSTOM_OPERATE("EXPORT_BI_DATA_SOURCE_CUSTOM_OPERATE", "经营数据导出"),
    EXPORT_BI_DATA_SOURCE_CUSTOM_FINANCE("EXPORT_BI_DATA_SOURCE_CUSTOM_FINANCE", "财务数据导出"),
    EXPORT_BI_TARGET_CATEGORY_SETTING("EXPORT_BI_TARGET_CATEGORY_SETTING", "按品类导出目标报表"),
    EXPORT_BI_TARGET_NEW_PRODUCT_SETTING("EXPORT_BI_TARGET_NEW_PRODUCT_SETTING", "按新品导出目标报表"),
    EXPORT_BI_TARGET_SHOP_SETTING("EXPORT_BI_TARGET_SHOP_SETTING", "按店铺导出目标报表"),
    EXPORT_BI_TARGET_SKU_SETTING("EXPORT_BI_TARGET_SKU_SETTING", "按SKU导出目标报表"),
    EXPORT_BI_TARGET_STAFF_SETTING("EXPORT_BI_TARGET_STAFF_SETTING", "按人员导出目标报表"),
    EXPORT_BI_COUNTRY_SALES("EXPORT_BI_COUNTRY_SALES", "区域国家销售额数据"),
    EXPORT_BI_NEW_AND_OLD_SALES_EXPORT("EXPORT_BI_NEW_AND_OLD_SALES_EXPORT", "新老品销售额"),
    EXPORT_BI_REPORT("EXPORT_BI_REPORT", "新老品销售额"),
    //plm
    EXPORT_PLM_BOM("EXPORT_PLM_BOM", "BOM数据"),
    EXPORT_PLM_PRODUCT_CERTIFICATE("EXPORT_PLM_PRODUCT_CERTIFICATE", "产品认证列表"),
    EXPORT_PLM_TASK("EXPORT_PLM_TASK", "产品任务列表"),
    PRODUCT_DETAIL_EXPORT("PRODUCT_DETAIL_EXPORT", "产品明细"),

    //wms
    INVENTORY_EXPORT("INVENTORY_EXPORT","即时库存"),
    ALIEXPRESS_DELIVERY_EXPORT("ALIEXPRESS_DELIVERY_EXPORT", "速卖通发货单"),
    B2C_DELIVERY_ORDER_EXPORT("B2C_DELIVERY_ORDER_EXPORT", "发货单导出"),
    //workflow
    PROCESS_MANAGEMENT_EXPORT("PROCESS_MANAGEMENT_EXPORT", "流程管理"),
    DEFAULT("DEFAULT", "默认");
    private final String code;
    private final String name;

    @Override
    public String getCode() {
        return code;
    }

    @Override
    public String getName() {
        return name;
    }

}
