<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>cloud-erp</artifactId>
        <groupId>com.cloud.erp</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>erp-server</artifactId>
    <packaging>pom</packaging>

    <properties>
        <alibaba.druid.verison>1.2.15</alibaba.druid.verison>
        <seata.version>1.5.2</seata.version>
        <xxl-job.version>2.3.0</xxl-job.version>
    </properties>
    <modules>
        <module>erp-server-auth</module>
        <module>erp-server-admin</module>
        <module>erp-server-sys</module>
        <module>erp-server-workflow</module>
        <module>erp-server-plm</module>
        <module>erp-server-dmp</module>
        <module>erp-server-bi</module>
        <module>erp-server-scm</module>
        <module>erp-server-wms</module>
        <module>erp-server-msg</module>
        <module>erp-server-oms</module>
        <module>erp-server-tms</module>
        <module>erp-server-srm</module>
        <module>erp-server-mrp</module>
        <module>erp-server-file</module>
    </modules>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <!--      optional 表示依赖是否向下传递 true表示不向下传递  默认值是false向下传递      -->
            <optional>true</optional>
        </dependency>
        <!--seata-->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
            <version>2021.1</version>
            <exclusions>
                <exclusion>
                    <artifactId>seata-all</artifactId>
                    <groupId>io.seata</groupId>
                </exclusion>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>${seata.version}</version>
        </dependency>
    </dependencies>

</project>