apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-server-admin
  namespace: dev #namespace
  labels:
    app: erp-server-admin
spec:
  replicas: 2
  minReadySeconds: 60  # 从容器启动到应用正常提供服务
  strategy: # k8s更新策略
    type: RollingUpdate #滚动更新
    rollingUpdate:
      maxSurge: 2  # 更新时允许最大激增的容器数，默认 replicas 的 1/4 向上取整
      maxUnavailable: 1  # 更新时允许最大 unavailable 容器数，默认 replicas 的 1/4 向下取整
  template:
    metadata:
      labels:
        app: erp-server-admin
    spec:
      imagePullSecrets: #使用imagePullSecrets参数指定镜像拉取秘钥
        - name: harbor-registry        #使用我们的secret，即harbor-registry
      automountServiceAccountToken: true
      containers:
        - name: erp-server-admin
          image: 172.16.100.92:5000/sdc-erp/erp-server-admin:1.0.0 #Tag
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "300m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: SPRING_PROFILES_ACTIVE
                  name: erp-config

          ports:
            - containerPort: 8080
              name: server
              protocol: TCP #修改成你项目的端口
          livenessProbe: #检查是否存活
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 240 #首次检查在多少时间后
            periodSeconds: 180 #检查周期
            timeoutSeconds: 3 #超时时间
            failureThreshold: 3 #失败的阈值，连续三次
          readinessProbe: #检查是否成功启动
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 140 #首次检查在多少时间后
            periodSeconds: 300 #检查周期
            timeoutSeconds: 3 #超时时间
  selector:
    matchLabels:
      app: erp-server-admin
---
apiVersion: v1
kind: Service
metadata:
  name: erp-server-admin
  namespace: dev #namespace
  labels:
    app: erp-server-admin
spec:
  selector:
    app: erp-server-admin
  ports:
    - name: tcp
      # 修改你的项目端口号
      port: 8080
      # 容器暴露的访问端口 要确定与其他服务不冲突
      targetPort: 8040
      nodePort: 30040
  type: NodePort
