
package com.sdk.tms.baohong.api.product;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceForProduct", targetNamespace = "http://www.example.org/ServiceForProduct/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceForProduct {


    /**
     * 
     * @param headerRequest
     * @param ask
     * @param skuNo
     * @param message
     * @param error
     * @param errorCodeMsg
     * @param productInfo
     */
    @WebMethod(action = "http://www.example.org/ServiceForProduct/createProduct")
    @RequestWrapper(localName = "createProduct", targetNamespace = "http://www.example.org/ServiceForProduct/", className = "org.example.serviceforproduct.CreateProduct")
    @ResponseWrapper(localName = "createProductResponse", targetNamespace = "http://www.example.org/ServiceForProduct/", className = "org.example.serviceforproduct.CreateProductResponse")
    public void createProduct(
        @WebParam(name = "HeaderRequest", targetNamespace = "")
        HeaderRequest headerRequest,
        @WebParam(name = "ProductInfo", targetNamespace = "")
        ProductInfo productInfo,
        @WebParam(name = "ask", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> ask,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "skuNo", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> skuNo,
        @WebParam(name = "error", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<ErrorType>> error,
        @WebParam(name = "errorCodeMsg", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<ErrorCodeMsgType>> errorCodeMsg);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.example.serviceforproduct.CreateRecordResponse
     */
    @WebMethod(action = "http://www.example.org/ServiceForProduct/createRecord")
    @WebResult(name = "createRecordResponse", targetNamespace = "http://www.example.org/ServiceForProduct/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public CreateRecordResponse createRecord(
        @WebParam(name = "createRecordRequest", targetNamespace = "http://www.example.org/ServiceForProduct/", partName = "parameters")
        CreateRecordRequest parameters);

    /**
     * 
     * @param headerRequest
     * @param data
     * @param skuNo
     * @param ask
     * @param message
     * @param errorCodeMsg
     */
    @WebMethod(action = "http://www.example.org/ServiceForProduct/getStock")
    @RequestWrapper(localName = "getStock", targetNamespace = "http://www.example.org/ServiceForProduct/", className = "org.example.serviceforproduct.GetStock")
    @ResponseWrapper(localName = "getStockResponse", targetNamespace = "http://www.example.org/ServiceForProduct/", className = "org.example.serviceforproduct.GetStockResponse")
    public void getStock(
        @WebParam(name = "HeaderRequest", targetNamespace = "")
        HeaderRequest headerRequest,
        @WebParam(name = "skuNo", targetNamespace = "")
        String skuNo,
        @WebParam(name = "ask", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> ask,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "data", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<InventoryRow>> data,
        @WebParam(name = "errorCodeMsg", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<ErrorCodeMsgType>> errorCodeMsg);


    /**
     * 
     * @param headerRequest
     * @param data
     * @param skuNo
     * @param ask
     * @param message
     * @param errorCodeMsg
     */
    @WebMethod(action = "http://www.example.org/ServiceForProduct/getProduct")
    @RequestWrapper(localName = "getProduct", targetNamespace = "http://www.example.org/ServiceForProduct/", className = "org.example.serviceforproduct.GetProduct")
    @ResponseWrapper(localName = "getProductResponse", targetNamespace = "http://www.example.org/ServiceForProduct/", className = "org.example.serviceforproduct.GetProductResponse")
    public void getProduct(
        @WebParam(name = "HeaderRequest", targetNamespace = "")
        HeaderRequest headerRequest,
        @WebParam(name = "skuNo", targetNamespace = "")
        String skuNo,
        @WebParam(name = "ask", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> ask,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "data", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ProductRow> data,
        @WebParam(name = "errorCodeMsg", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<ErrorCodeMsgType>> errorCodeMsg);

    /**
     * 
     * @param total
     * @param headerRequest
     * @param dataList
     * @param ask
     * @param pageSize
     * @param page
     * @param message
     */
    @WebMethod(action = "http://www.example.org/ServiceForProduct/getProductList")
    @RequestWrapper(localName = "getProductList", targetNamespace = "http://www.example.org/ServiceForProduct/", className = "org.example.serviceforproduct.GetProductList")
    @ResponseWrapper(localName = "getProductListResponse", targetNamespace = "http://www.example.org/ServiceForProduct/", className = "org.example.serviceforproduct.GetProductListResponse")
    public void getProductList(
        @WebParam(name = "HeaderRequest", targetNamespace = "")
        HeaderRequest headerRequest,
        @WebParam(name = "page", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Integer> page,
        @WebParam(name = "pageSize", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Integer> pageSize,
        @WebParam(name = "ask", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> ask,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "total", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> total,
        @WebParam(name = "dataList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<DataRow>> dataList);

    /**
     * 
     * @param headerRequest
     * @param skuNoArr
     * @param data
     * @param ask
     * @param message
     * @param error
     * @param errorCodeMsg
     */
    @WebMethod(action = "http://www.example.org/ServiceForProduct/getBatchStock")
    @RequestWrapper(localName = "getBatchStock", targetNamespace = "http://www.example.org/ServiceForProduct/", className = "org.example.serviceforproduct.GetBatchStock")
    @ResponseWrapper(localName = "getBatchStockResponse", targetNamespace = "http://www.example.org/ServiceForProduct/", className = "org.example.serviceforproduct.GetBatchStockResponse")
    public void getBatchStock(
        @WebParam(name = "HeaderRequest", targetNamespace = "")
        HeaderRequest headerRequest,
        @WebParam(name = "skuNoArr", targetNamespace = "")
        List<String> skuNoArr,
        @WebParam(name = "ask", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> ask,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "error", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<String>> error,
        @WebParam(name = "data", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<InventoryRow>> data,
        @WebParam(name = "errorCodeMsg", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<ErrorCodeMsgType>> errorCodeMsg);

}
