
package com.sdk.tms.baohong.api.product;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceForProduct", targetNamespace = "http://www.example.org/ServiceForProduct/", wsdlLocation = "http://exoms.globex.cn/default/product-soap/")
public class ServiceForProduct_Service
    extends Service
{

    private final static String NAMESPACE_URI = "http://www.example.org/ServiceForProduct/";
    private final static URL SERVICEFORPRODUCT_WSDL_LOCATION;
    private final static WebServiceException SERVICEFORPRODUCT_EXCEPTION;
    private final static QName SERVICEFORPRODUCT_QNAME = new QName(NAMESPACE_URI, "ServiceForProduct");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://exoms.globex.cn/default/product-soap/");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEFORPRODUCT_WSDL_LOCATION = url;
        SERVICEFORPRODUCT_EXCEPTION = e;
    }

    public ServiceForProduct_Service() {
        super(__getWsdlLocation(), SERVICEFORPRODUCT_QNAME);
    }

    public ServiceForProduct_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEFORPRODUCT_QNAME, features);
    }

    public ServiceForProduct_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICEFORPRODUCT_QNAME);
    }

    public ServiceForProduct_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEFORPRODUCT_QNAME, features);
    }

    public ServiceForProduct_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceForProduct_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceForProduct
     */
    @WebEndpoint(name = "ServiceForProductSOAP")
    public ServiceForProduct getServiceForProductSOAP() {
        return super.getPort(new QName(NAMESPACE_URI, "ServiceForProductSOAP"), ServiceForProduct.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceForProduct
     */
    @WebEndpoint(name = "ServiceForProductSOAP")
    public ServiceForProduct getServiceForProductSOAP(WebServiceFeature... features) {
        return super.getPort(new QName(NAMESPACE_URI, "ServiceForProductSOAP"), ServiceForProduct.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEFORPRODUCT_EXCEPTION!= null) {
            throw SERVICEFORPRODUCT_EXCEPTION;
        }
        return SERVICEFORPRODUCT_WSDL_LOCATION;
    }

}
