
package com.sdk.tms.baohong.api.order;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceForOrder", targetNamespace = "http://www.example.org/ServiceForOrder/", wsdlLocation = "http://exoms.globex.cn/default/order-soap/")
public class ServiceForOrder_Service
    extends Service
{

    private final static URL SERVICEFORORDER_WSDL_LOCATION;
    private final static WebServiceException SERVICEFORORDER_EXCEPTION;
    private final static QName SERVICEFORORDER_QNAME = new QName("http://www.example.org/ServiceForOrder/", "ServiceForOrder");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://exoms.globex.cn/default/order-soap/");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEFORORDER_WSDL_LOCATION = url;
        SERVICEFORORDER_EXCEPTION = e;
    }

    public ServiceForOrder_Service() {
        super(__getWsdlLocation(), SERVICEFORORDER_QNAME);
    }

    public ServiceForOrder_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEFORORDER_QNAME, features);
    }

    public ServiceForOrder_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICEFORORDER_QNAME);
    }

    public ServiceForOrder_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEFORORDER_QNAME, features);
    }

    public ServiceForOrder_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceForOrder_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceForOrder
     */
    @WebEndpoint(name = "ServiceForOrderSOAP")
    public ServiceForOrder getServiceForOrderSOAP() {
        return super.getPort(new QName("http://www.example.org/ServiceForOrder/", "ServiceForOrderSOAP"), ServiceForOrder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceForOrder
     */
    @WebEndpoint(name = "ServiceForOrderSOAP")
    public ServiceForOrder getServiceForOrderSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/ServiceForOrder/", "ServiceForOrderSOAP"), ServiceForOrder.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEFORORDER_EXCEPTION!= null) {
            throw SERVICEFORORDER_EXCEPTION;
        }
        return SERVICEFORORDER_WSDL_LOCATION;
    }

}
