package com.erp.server.wms.rocketmq.consumer;

import cn.hutool.core.date.LocalDateTimeUtil;
import cn.hutool.json.JSONUtil;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.TypeReference;
import com.common.business.dto.PlatformInboundDTO;
import com.common.business.enums.OverseasInstockStatusEnum;
import com.common.business.enums.WarehousePlatformTypeEnum;
import com.erp.server.wms.ErpServerWmsApplication;
import com.sdk.wms.iml.dto.response.ImlProductResp;
import com.sdk.wms.iml.dto.response.ImlResponse;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import javax.annotation.Resource;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerWmsApplication.class})
public class PlatformInboundConsumerServiceTest {

    @Resource
    private PlatformInboundConsumerService service;

    @Test
    public void handleTest() {
        String json = "{\n" +
                "  \"warehousePlatformType\":\"overseasWarehouse\",\n" +
                "  \"provider\":\"iml\",\n" +
                "  \"receivingCode\":\"RV86526-231107-0002\",\n" +
                "  \"receivingStatus\":\"signed\",\n" +
                "  \"downloadTime\":1702020612307,\n" +
                "  \"items\":[\n" +
                "    {\n" +
                "      \"productSku\":\"2806\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"1\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2806\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"2\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2806\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"3\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2806\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"4\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2806\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"5\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2907\",\n" +
                "      \"receivedQuantity\":48,\n" +
                "      \"putawayQuantity\":48,\n" +
                "      \"boxNo\":\"6\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2907\",\n" +
                "      \"receivedQuantity\":48,\n" +
                "      \"putawayQuantity\":48,\n" +
                "      \"boxNo\":\"7\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2907\",\n" +
                "      \"receivedQuantity\":48,\n" +
                "      \"putawayQuantity\":48,\n" +
                "      \"boxNo\":\"8\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2907\",\n" +
                "      \"receivedQuantity\":48,\n" +
                "      \"putawayQuantity\":48,\n" +
                "      \"boxNo\":\"9\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2907\",\n" +
                "      \"receivedQuantity\":48,\n" +
                "      \"putawayQuantity\":48,\n" +
                "      \"boxNo\":\"10\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2907\",\n" +
                "      \"receivedQuantity\":48,\n" +
                "      \"putawayQuantity\":48,\n" +
                "      \"boxNo\":\"11\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2907\",\n" +
                "      \"receivedQuantity\":48,\n" +
                "      \"putawayQuantity\":48,\n" +
                "      \"boxNo\":\"12\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2873\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"13\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2873\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"14\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2873\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"15\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2873\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"16\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2873\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"17\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2248\",\n" +
                "      \"receivedQuantity\":25,\n" +
                "      \"putawayQuantity\":25,\n" +
                "      \"boxNo\":\"18\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2248\",\n" +
                "      \"receivedQuantity\":25,\n" +
                "      \"putawayQuantity\":25,\n" +
                "      \"boxNo\":\"19\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3336\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"20\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3336\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"21\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3336\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"22\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3025\",\n" +
                "      \"receivedQuantity\":16,\n" +
                "      \"putawayQuantity\":16,\n" +
                "      \"boxNo\":\"23\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3030\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"24\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3030\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"25\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3030\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"26\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3030\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"27\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3030\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"28\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3030\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"29\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3030\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"30\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3030\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"31\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3030\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"32\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3030\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"33\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3030\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"34\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"T075GBB1\",\n" +
                "      \"receivedQuantity\":25,\n" +
                "      \"putawayQuantity\":25,\n" +
                "      \"boxNo\":\"35\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"T075GBB1\",\n" +
                "      \"receivedQuantity\":25,\n" +
                "      \"putawayQuantity\":25,\n" +
                "      \"boxNo\":\"36\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3029\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"37\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3029\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"38\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3029\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"39\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2784\",\n" +
                "      \"receivedQuantity\":16,\n" +
                "      \"putawayQuantity\":16,\n" +
                "      \"boxNo\":\"40\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2784\",\n" +
                "      \"receivedQuantity\":16,\n" +
                "      \"putawayQuantity\":16,\n" +
                "      \"boxNo\":\"41\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2784\",\n" +
                "      \"receivedQuantity\":16,\n" +
                "      \"putawayQuantity\":16,\n" +
                "      \"boxNo\":\"42\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2784\",\n" +
                "      \"receivedQuantity\":16,\n" +
                "      \"putawayQuantity\":16,\n" +
                "      \"boxNo\":\"43\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2784\",\n" +
                "      \"receivedQuantity\":16,\n" +
                "      \"putawayQuantity\":16,\n" +
                "      \"boxNo\":\"44\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2487\",\n" +
                "      \"receivedQuantity\":18,\n" +
                "      \"putawayQuantity\":18,\n" +
                "      \"boxNo\":\"45\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2287\",\n" +
                "      \"receivedQuantity\":22,\n" +
                "      \"putawayQuantity\":22,\n" +
                "      \"boxNo\":\"46\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2487\",\n" +
                "      \"receivedQuantity\":12,\n" +
                "      \"putawayQuantity\":12,\n" +
                "      \"boxNo\":\"46\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3030\",\n" +
                "      \"receivedQuantity\":1,\n" +
                "      \"putawayQuantity\":1,\n" +
                "      \"boxNo\":\"46\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2287\",\n" +
                "      \"receivedQuantity\":14,\n" +
                "      \"putawayQuantity\":14,\n" +
                "      \"boxNo\":\"47\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2248\",\n" +
                "      \"receivedQuantity\":20,\n" +
                "      \"putawayQuantity\":20,\n" +
                "      \"boxNo\":\"47\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2806\",\n" +
                "      \"receivedQuantity\":4,\n" +
                "      \"putawayQuantity\":4,\n" +
                "      \"boxNo\":\"48\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2873\",\n" +
                "      \"receivedQuantity\":5,\n" +
                "      \"putawayQuantity\":5,\n" +
                "      \"boxNo\":\"48\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2287\",\n" +
                "      \"receivedQuantity\":11,\n" +
                "      \"putawayQuantity\":11,\n" +
                "      \"boxNo\":\"49\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2806\",\n" +
                "      \"receivedQuantity\":1,\n" +
                "      \"putawayQuantity\":1,\n" +
                "      \"boxNo\":\"49\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2666\",\n" +
                "      \"receivedQuantity\":10,\n" +
                "      \"putawayQuantity\":10,\n" +
                "      \"boxNo\":\"49\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"T049GBB1\",\n" +
                "      \"receivedQuantity\":5,\n" +
                "      \"putawayQuantity\":5,\n" +
                "      \"boxNo\":\"49\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3029\",\n" +
                "      \"receivedQuantity\":3,\n" +
                "      \"putawayQuantity\":3,\n" +
                "      \"boxNo\":\"50\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3089\",\n" +
                "      \"receivedQuantity\":6,\n" +
                "      \"putawayQuantity\":6,\n" +
                "      \"boxNo\":\"50\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"T049GBB1\",\n" +
                "      \"receivedQuantity\":15,\n" +
                "      \"putawayQuantity\":15,\n" +
                "      \"boxNo\":\"50\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3051\",\n" +
                "      \"receivedQuantity\":20,\n" +
                "      \"putawayQuantity\":20,\n" +
                "      \"boxNo\":\"50\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3336\",\n" +
                "      \"receivedQuantity\":3,\n" +
                "      \"putawayQuantity\":3,\n" +
                "      \"boxNo\":\"50\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2638\",\n" +
                "      \"receivedQuantity\":63,\n" +
                "      \"putawayQuantity\":63,\n" +
                "      \"boxNo\":\"51\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2638\",\n" +
                "      \"receivedQuantity\":63,\n" +
                "      \"putawayQuantity\":63,\n" +
                "      \"boxNo\":\"52\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2587\",\n" +
                "      \"receivedQuantity\":12,\n" +
                "      \"putawayQuantity\":12,\n" +
                "      \"boxNo\":\"53\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2495\",\n" +
                "      \"receivedQuantity\":41,\n" +
                "      \"putawayQuantity\":41,\n" +
                "      \"boxNo\":\"53\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2638\",\n" +
                "      \"receivedQuantity\":7,\n" +
                "      \"putawayQuantity\":7,\n" +
                "      \"boxNo\":\"53\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2587\",\n" +
                "      \"receivedQuantity\":54,\n" +
                "      \"putawayQuantity\":54,\n" +
                "      \"boxNo\":\"54\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"L040GBB1\",\n" +
                "      \"receivedQuantity\":3,\n" +
                "      \"putawayQuantity\":3,\n" +
                "      \"boxNo\":\"54\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"M013GBB1\",\n" +
                "      \"receivedQuantity\":4,\n" +
                "      \"putawayQuantity\":4,\n" +
                "      \"boxNo\":\"55\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2587\",\n" +
                "      \"receivedQuantity\":16,\n" +
                "      \"putawayQuantity\":16,\n" +
                "      \"boxNo\":\"55\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"L040GBB1\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"55\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"M013GBB1\",\n" +
                "      \"receivedQuantity\":8,\n" +
                "      \"putawayQuantity\":8,\n" +
                "      \"boxNo\":\"56\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2587\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"56\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"L040GBB1\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"56\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"M013GBB1\",\n" +
                "      \"receivedQuantity\":8,\n" +
                "      \"putawayQuantity\":8,\n" +
                "      \"boxNo\":\"57\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2587\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"57\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"L040GBB1\",\n" +
                "      \"receivedQuantity\":9,\n" +
                "      \"putawayQuantity\":9,\n" +
                "      \"boxNo\":\"57\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3050\",\n" +
                "      \"receivedQuantity\":5,\n" +
                "      \"putawayQuantity\":5,\n" +
                "      \"boxNo\":\"58\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2495\",\n" +
                "      \"receivedQuantity\":46,\n" +
                "      \"putawayQuantity\":46,\n" +
                "      \"boxNo\":\"58\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3050\",\n" +
                "      \"receivedQuantity\":5,\n" +
                "      \"putawayQuantity\":5,\n" +
                "      \"boxNo\":\"59\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2495\",\n" +
                "      \"receivedQuantity\":46,\n" +
                "      \"putawayQuantity\":46,\n" +
                "      \"boxNo\":\"59\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2287\",\n" +
                "      \"receivedQuantity\":33,\n" +
                "      \"putawayQuantity\":33,\n" +
                "      \"boxNo\":\"60\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"1907\",\n" +
                "      \"receivedQuantity\":11,\n" +
                "      \"putawayQuantity\":11,\n" +
                "      \"boxNo\":\"60\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3050\",\n" +
                "      \"receivedQuantity\":5,\n" +
                "      \"putawayQuantity\":5,\n" +
                "      \"boxNo\":\"60\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2895\",\n" +
                "      \"receivedQuantity\":10,\n" +
                "      \"putawayQuantity\":10,\n" +
                "      \"boxNo\":\"60\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"1907\",\n" +
                "      \"receivedQuantity\":33,\n" +
                "      \"putawayQuantity\":33,\n" +
                "      \"boxNo\":\"61\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2495\",\n" +
                "      \"receivedQuantity\":20,\n" +
                "      \"putawayQuantity\":20,\n" +
                "      \"boxNo\":\"61\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2134\",\n" +
                "      \"receivedQuantity\":30,\n" +
                "      \"putawayQuantity\":30,\n" +
                "      \"boxNo\":\"62\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2250\",\n" +
                "      \"receivedQuantity\":6,\n" +
                "      \"putawayQuantity\":6,\n" +
                "      \"boxNo\":\"62\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2090\",\n" +
                "      \"receivedQuantity\":10,\n" +
                "      \"putawayQuantity\":10,\n" +
                "      \"boxNo\":\"62\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2250\",\n" +
                "      \"receivedQuantity\":4,\n" +
                "      \"putawayQuantity\":4,\n" +
                "      \"boxNo\":\"63\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2029\",\n" +
                "      \"receivedQuantity\":48,\n" +
                "      \"putawayQuantity\":48,\n" +
                "      \"boxNo\":\"63\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2907\",\n" +
                "      \"receivedQuantity\":14,\n" +
                "      \"putawayQuantity\":14,\n" +
                "      \"boxNo\":\"64\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2108\",\n" +
                "      \"receivedQuantity\":22,\n" +
                "      \"putawayQuantity\":22,\n" +
                "      \"boxNo\":\"64\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3064\",\n" +
                "      \"receivedQuantity\":25,\n" +
                "      \"putawayQuantity\":25,\n" +
                "      \"boxNo\":\"64\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2809\",\n" +
                "      \"receivedQuantity\":10,\n" +
                "      \"putawayQuantity\":10,\n" +
                "      \"boxNo\":\"64\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2029\",\n" +
                "      \"receivedQuantity\":2,\n" +
                "      \"putawayQuantity\":2,\n" +
                "      \"boxNo\":\"64\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2250\",\n" +
                "      \"receivedQuantity\":5,\n" +
                "      \"putawayQuantity\":5,\n" +
                "      \"boxNo\":\"65\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"1678\",\n" +
                "      \"receivedQuantity\":19,\n" +
                "      \"putawayQuantity\":19,\n" +
                "      \"boxNo\":\"65\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2268\",\n" +
                "      \"receivedQuantity\":20,\n" +
                "      \"putawayQuantity\":20,\n" +
                "      \"boxNo\":\"65\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"B01002\",\n" +
                "      \"receivedQuantity\":20,\n" +
                "      \"putawayQuantity\":20,\n" +
                "      \"boxNo\":\"65\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2135\",\n" +
                "      \"receivedQuantity\":20,\n" +
                "      \"putawayQuantity\":20,\n" +
                "      \"boxNo\":\"66\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3064\",\n" +
                "      \"receivedQuantity\":25,\n" +
                "      \"putawayQuantity\":25,\n" +
                "      \"boxNo\":\"66\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2809\",\n" +
                "      \"receivedQuantity\":40,\n" +
                "      \"putawayQuantity\":40,\n" +
                "      \"boxNo\":\"66\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3089\",\n" +
                "      \"receivedQuantity\":4,\n" +
                "      \"putawayQuantity\":4,\n" +
                "      \"boxNo\":\"66\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3025\",\n" +
                "      \"receivedQuantity\":4,\n" +
                "      \"putawayQuantity\":4,\n" +
                "      \"boxNo\":\"67\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2250\",\n" +
                "      \"receivedQuantity\":5,\n" +
                "      \"putawayQuantity\":5,\n" +
                "      \"boxNo\":\"67\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"1678\",\n" +
                "      \"receivedQuantity\":29,\n" +
                "      \"putawayQuantity\":29,\n" +
                "      \"boxNo\":\"67\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"E004GBA1\",\n" +
                "      \"receivedQuantity\":10,\n" +
                "      \"putawayQuantity\":10,\n" +
                "      \"boxNo\":\"67\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"1907\",\n" +
                "      \"receivedQuantity\":6,\n" +
                "      \"putawayQuantity\":6,\n" +
                "      \"boxNo\":\"68\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"0673\",\n" +
                "      \"receivedQuantity\":17,\n" +
                "      \"putawayQuantity\":17,\n" +
                "      \"boxNo\":\"68\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2326\",\n" +
                "      \"receivedQuantity\":14,\n" +
                "      \"putawayQuantity\":14,\n" +
                "      \"boxNo\":\"68\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2895\",\n" +
                "      \"receivedQuantity\":20,\n" +
                "      \"putawayQuantity\":20,\n" +
                "      \"boxNo\":\"68\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2885\",\n" +
                "      \"receivedQuantity\":50,\n" +
                "      \"putawayQuantity\":50,\n" +
                "      \"boxNo\":\"69\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3032\",\n" +
                "      \"receivedQuantity\":15,\n" +
                "      \"putawayQuantity\":15,\n" +
                "      \"boxNo\":\"69\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2134\",\n" +
                "      \"receivedQuantity\":20,\n" +
                "      \"putawayQuantity\":20,\n" +
                "      \"boxNo\":\"69\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2660\",\n" +
                "      \"receivedQuantity\":15,\n" +
                "      \"putawayQuantity\":15,\n" +
                "      \"boxNo\":\"69\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3282A\",\n" +
                "      \"receivedQuantity\":10,\n" +
                "      \"putawayQuantity\":10,\n" +
                "      \"boxNo\":\"70\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2503A\",\n" +
                "      \"receivedQuantity\":37,\n" +
                "      \"putawayQuantity\":37,\n" +
                "      \"boxNo\":\"70\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3032\",\n" +
                "      \"receivedQuantity\":5,\n" +
                "      \"putawayQuantity\":5,\n" +
                "      \"boxNo\":\"71\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2108\",\n" +
                "      \"receivedQuantity\":21,\n" +
                "      \"putawayQuantity\":21,\n" +
                "      \"boxNo\":\"71\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2502B\",\n" +
                "      \"receivedQuantity\":25,\n" +
                "      \"putawayQuantity\":25,\n" +
                "      \"boxNo\":\"71\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"1672\",\n" +
                "      \"receivedQuantity\":40,\n" +
                "      \"putawayQuantity\":40,\n" +
                "      \"boxNo\":\"71\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"1678\",\n" +
                "      \"receivedQuantity\":12,\n" +
                "      \"putawayQuantity\":12,\n" +
                "      \"boxNo\":\"72\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3282A\",\n" +
                "      \"receivedQuantity\":10,\n" +
                "      \"putawayQuantity\":10,\n" +
                "      \"boxNo\":\"72\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2503A\",\n" +
                "      \"receivedQuantity\":33,\n" +
                "      \"putawayQuantity\":33,\n" +
                "      \"boxNo\":\"72\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2028\",\n" +
                "      \"receivedQuantity\":10,\n" +
                "      \"putawayQuantity\":10,\n" +
                "      \"boxNo\":\"73\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"1672\",\n" +
                "      \"receivedQuantity\":10,\n" +
                "      \"putawayQuantity\":10,\n" +
                "      \"boxNo\":\"73\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"C072GBB1\",\n" +
                "      \"receivedQuantity\":30,\n" +
                "      \"putawayQuantity\":30,\n" +
                "      \"boxNo\":\"73\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2481\",\n" +
                "      \"receivedQuantity\":5,\n" +
                "      \"putawayQuantity\":5,\n" +
                "      \"boxNo\":\"73\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2878\",\n" +
                "      \"receivedQuantity\":50,\n" +
                "      \"putawayQuantity\":50,\n" +
                "      \"boxNo\":\"73\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2108\",\n" +
                "      \"receivedQuantity\":7,\n" +
                "      \"putawayQuantity\":7,\n" +
                "      \"boxNo\":\"74\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2502B\",\n" +
                "      \"receivedQuantity\":25,\n" +
                "      \"putawayQuantity\":25,\n" +
                "      \"boxNo\":\"74\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3050\",\n" +
                "      \"receivedQuantity\":1,\n" +
                "      \"putawayQuantity\":1,\n" +
                "      \"boxNo\":\"74\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2482\",\n" +
                "      \"receivedQuantity\":30,\n" +
                "      \"putawayQuantity\":30,\n" +
                "      \"boxNo\":\"74\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2287\",\n" +
                "      \"receivedQuantity\":20,\n" +
                "      \"putawayQuantity\":20,\n" +
                "      \"boxNo\":\"75\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2028\",\n" +
                "      \"receivedQuantity\":40,\n" +
                "      \"putawayQuantity\":40,\n" +
                "      \"boxNo\":\"75\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3050\",\n" +
                "      \"receivedQuantity\":4,\n" +
                "      \"putawayQuantity\":4,\n" +
                "      \"boxNo\":\"75\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2495\",\n" +
                "      \"receivedQuantity\":30,\n" +
                "      \"putawayQuantity\":30,\n" +
                "      \"boxNo\":\"75\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"0673\",\n" +
                "      \"receivedQuantity\":33,\n" +
                "      \"putawayQuantity\":33,\n" +
                "      \"boxNo\":\"76\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2326\",\n" +
                "      \"receivedQuantity\":6,\n" +
                "      \"putawayQuantity\":6,\n" +
                "      \"boxNo\":\"76\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2495\",\n" +
                "      \"receivedQuantity\":17,\n" +
                "      \"putawayQuantity\":17,\n" +
                "      \"boxNo\":\"76\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2481\",\n" +
                "      \"receivedQuantity\":15,\n" +
                "      \"putawayQuantity\":15,\n" +
                "      \"boxNo\":\"76\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"1781\",\n" +
                "      \"receivedQuantity\":140,\n" +
                "      \"putawayQuantity\":140,\n" +
                "      \"boxNo\":\"77\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2638\",\n" +
                "      \"receivedQuantity\":67,\n" +
                "      \"putawayQuantity\":67,\n" +
                "      \"boxNo\":\"77\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3033\",\n" +
                "      \"receivedQuantity\":27,\n" +
                "      \"putawayQuantity\":27,\n" +
                "      \"boxNo\":\"78\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"1781\",\n" +
                "      \"receivedQuantity\":60,\n" +
                "      \"putawayQuantity\":60,\n" +
                "      \"boxNo\":\"79\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"3033\",\n" +
                "      \"receivedQuantity\":23,\n" +
                "      \"putawayQuantity\":23,\n" +
                "      \"boxNo\":\"79\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2991\",\n" +
                "      \"receivedQuantity\":20,\n" +
                "      \"putawayQuantity\":20,\n" +
                "      \"boxNo\":\"80\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2991\",\n" +
                "      \"receivedQuantity\":20,\n" +
                "      \"putawayQuantity\":20,\n" +
                "      \"boxNo\":\"81\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2991\",\n" +
                "      \"receivedQuantity\":20,\n" +
                "      \"putawayQuantity\":20,\n" +
                "      \"boxNo\":\"82\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2991\",\n" +
                "      \"receivedQuantity\":20,\n" +
                "      \"putawayQuantity\":20,\n" +
                "      \"boxNo\":\"83\"\n" +
                "    },\n" +
                "    {\n" +
                "      \"productSku\":\"2991\",\n" +
                "      \"receivedQuantity\":20,\n" +
                "      \"putawayQuantity\":20,\n" +
                "      \"boxNo\":\"84\"\n" +
                "    }\n" +
                "  ],\n" +
                "  \"hasReceivedData\":false,\n" +
                "  \"uniqueId\":\"09aa33b9e92da0a0194750c61d3b4d11\",\n" +
                "  \"platform\":\"iml\"\n" +
                "}"
                ;
        PlatformInboundDTO dto = JSONObject.parseObject(json,new TypeReference<PlatformInboundDTO>() {}.getType());
//        PlatformInboundDTO dto = new PlatformInboundDTO();
//        dto.setWarehousePlatformType(WarehousePlatformTypeEnum.OVERSEAS_WAREHOUSE.code);
//        dto.setReceivingCode("RVG1149-231207-0001");
//        dto.setProvider("goodcang");
//        dto.setPlatform("goodcang");
//        dto.setDownloadTime(LocalDateTime.now());
//        dto.setReceivingStatus(OverseasInstockStatusEnum.FINISH.getCode());
//        List<PlatformInboundDTO.Item> itemList = new ArrayList<>();
//        dto.setItems(itemList);
//        PlatformInboundDTO.Item item = new PlatformInboundDTO.Item();
//        item.setProductSku("QC6SHR-045700EU-ML000");
//        item.setReceivedQuantity(20);
//        itemList.add(item);
//        dto.setHasReceivedData(false);
//        List<PlatformInboundDTO.Receiving> receivings = new ArrayList<>();
//        LocalDateTime localDateTime = LocalDateTime.now();
//        PlatformInboundDTO.Receiving receiving = new PlatformInboundDTO.Receiving();
//        receiving.setProductSku("QC6SHR-045700EU-ML000");
//        receiving.setReceiveQty(10);
//        receiving.setReceiveTime(localDateTime);
//        receivings.add(receiving);
//        dto.setReceivingDataList(receivings);
        service.handle(JSONUtil.parse(dto));
    }
}