/*
 * Selling Partner API for Sellers
 * The Selling Partner API for Sellers lets you retrieve information on behalf of sellers about their seller account, such as the marketplaces they participate in. Along with listing the marketplaces that a seller can sell in, the API also provides additional information about the marketplace such as the default language and the default currency. The API also provides seller-specific information such as whether the seller has suspended listings in that marketplace.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.erp.sdk.oms.amz.spapi.download;

import cn.hutool.core.util.StrUtil;
import cn.hutool.json.JSONArray;
import com.common.business.constant.MongoTableNameContant;
import com.common.core.utils.StrUtils;
import com.erp.sdk.oms.amz.spapi.client.JSON;
import com.erp.sdk.oms.amz.spapi.csv.ReportFbaInventoryPlanningCsvEntity;
import com.erp.sdk.oms.amz.spapi.csv.ReportFbaMyiAllInventoryCsvEntity;
import com.erp.sdk.oms.amz.spapi.csv.ReportReservedCsvEntity;
import com.erp.sdk.oms.amz.spapi.documents.DownloadHandler;
import com.erp.sdk.oms.amz.spapi.dto.ReportFbaInventoryPlanningMongoDTO;
import com.erp.sdk.oms.amz.spapi.dto.ReportFbaMyiAllInventoryMongoDTO;
import com.erp.sdk.oms.amz.spapi.dto.ReportReservedMongoDTO;
import com.erp.sdk.oms.amz.spapi.utils.AmazonSpApiReportUtils;
import com.opencsv.CSVReader;


import java.io.IOException;
import java.util.*;


/**
 * API tests for DownloadParseCsv
 */
public class DownloadParseCsvTest {


    public static void main3(String[] args) {
        Map<String, String> map = new HashMap<>();
        map.put("item-name", "itemName");
        map.put("item-description", "itemDescription");
        map.put("listing-id", "listingId");
        map.put("seller-sku", "sellerSku");
        map.put("price", "price");
        map.put("quantity", "quantity");
        map.put("open-date", "openDate");
        map.put("item-is-marketplace", "itemIsMarketplace");
        map.put("product-id-type", "productIdType");
        map.put("zshop-shipping-fee", "zshopShippingFee");
        map.put("item-note", "itemNote");
        map.put("item-condition", "itemCondition");
        map.put("zshop-category1", "zshopCategory1");
        map.put("zshop-browse-path", "zshopBrowsePath");
        map.put("zshop-storefront-feature", "zshopStorefrontFeature");
        map.put("asin1", "asin1");
        map.put("asin2", "asin2");
        map.put("asin3", "asin3");
        map.put("will-ship-internationally", "willShipInternationally");
        map.put("expedited-shipping", "expeditedShipping");
        map.put("zshop-boldface", "zshopBoldface");
        map.put("product-id", "productId");
        map.put("bid-for-featured-placement", "bidForFeaturedPlacement");
        map.put("add-delete", "addDelete");
        map.put("pending-quantity", "pendingQuantity");
        map.put("fulfillment-channel", "fulfillmentChannel");
        map.put("merchant-shipping-group","merchantShippingGroup");
        String url= "https://tortuga-prod-fe.s3-us-west-2.amazonaws.com/01eefe2a-4bc3-47b6-9ab6-bb4a851ab659.amzn1.tortuga.4.fe.T1C80YM5G5MN3L?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231221T064255Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=AKIAX3R62LVBHWGWVBWT%2F20231221%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Signature=921cb9dfb1678bebcbd5634398e5c00fbb2d28475bae8f2713406e784194cb51";
        String compressionAlgorithm = "";
        DownloadHandler obj = new DownloadHandler();
        try {
            JSONArray download = obj.download(url, compressionAlgorithm, map);
            System.out.println(download);
        } catch (IOException | IllegalArgumentException e) {
            //Handle exception here.
        }
    }


    public static void main(String[] args) {
        String url= "https://tortuga-prod-fe.s3-us-west-2.amazonaws.com/01eefe2a-4bc3-47b6-9ab6-bb4a851ab659.amzn1.tortuga.4.fe.T1C80YM5G5MN3L?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231221T073308Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=AKIAX3R62LVBHWGWVBWT%2F20231221%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Signature=737b2b2b924fe9366f95421dde0021b7e74c387b87df41cff5a187723159d003";
        Set<String> columnName = null;
        try {
            columnName = DownloadHandler.getReportTitleFromUrl(url,"");
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        LinkedHashMap<String, String> hashMap = new LinkedHashMap<>();
        for (String s : columnName) {
            System.out.println(s);
        }

        System.out.println("每个字段信息结束=====");
        for (String s : columnName) {
            if (s.contains("-")){
                String camelStr = StrUtils.underlineToCamel(s, true);
                hashMap.put(s, camelStr);
                System.out.println(camelStr);
            } else {
                hashMap.put(s, s);
            }
        }
        System.out.println("每个字段驼峰信息结束=====");
//        Long id= 1680776062189170030L;
//        String recordType = "GET_MERCHANT_LISTINGS_DATA";
        Long id= 1500000000000000001L;
        String recordType = "GET_FBA_MYI_ALL_INVENTORY_DATA";
//        Long id= 140000000000000000L;
//        String recordType = "GET_RESERVED_INVENTORY_DATA";
//        Long id= 130000000000000000L;
//        String recordType = "GET_FBA_INVENTORY_PLANNING_DATA";


        for (Map.Entry<String, String> entry : hashMap.entrySet()) {
            String sqlStr = "INSERT INTO \"public\".\"report_column_config\"  (\"id\",\"remark\", \"column_name\", \"field_name\", \"report_type\", \"status\") VALUES  ('{}','','{}','{}', '{}', 't');";
            String currentSql = StrUtil.format(sqlStr, id, entry.getKey(), entry.getValue(), recordType);
            System.out.println(currentSql);
            id ++;
        }

    }
    
}
