/*
 * Selling Partner API for Tokens
 * The Selling Partner API for Tokens provides a secure way to access a customer's PII (Personally Identifiable Information). You can call the Tokens API to get a Restricted Data Token (RDT) for one or more restricted resources that you specify. The RDT authorizes subsequent calls to restricted operations that correspond to the restricted resources that you specified.  For more information, see the [Tokens API Use Case Guide](doc:tokens-api-use-case-guide).
 *
 * OpenAPI spec version: 2021-03-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.erp.server.dmp.mongo;

import cn.hutool.json.JSONNull;
import cn.hutool.json.JSONUtil;
import com.amazonaws.util.json.Jackson;
import com.erp.sdk.oms.amz.spapi.dto.ReportFulfilledShipmentsMongoDTO;
import com.erp.server.dmp.ErpServerDmpApplication;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Profile;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.aggregation.*;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.test.context.junit4.SpringRunner;
import org.bson.types.ObjectId;

import javax.annotation.Resource;
import java.util.List;

/**
 * API tests for Mongo
 */
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerDmpApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@Profile("dev")
public class MongoTemplateTest {

    @Resource
    private MongoTemplate mongoTemplate;

    @Test
    public void joinQuery() {
        List<ReportFulfilledShipmentsMongoDTO> resultData = performJoinAndFilter2("6659e3971b4f5d1b16a27fe8", 10);
        System.out.println(JSONUtil.toJsonStr(resultData));
    }

    public List<ReportFulfilledShipmentsMongoDTO> performJoinAndFilter2(String specifiedId, int size) {
        MatchOperation matchStage = Aggregation.match(Criteria.where("_id").gt(new ObjectId(specifiedId)));

        LookupOperation lookupStage = LookupOperation.newLookup()
                .from("third_system_Amazon_so_out_stock")
                .localField("shipmentItemId")
                .foreignField("shipmentItemId")
                .as("joinedResults");

        AggregationOperation filterStage = Aggregation.match(
                new Criteria().orOperator(
                        Criteria.where("joinedResults").size(0), // joinedResults 数组为空的情况
                        new Criteria().andOperator(
                                Criteria.where("shipmentItemId").exists(true),
                                Criteria.where("joinedResults.shipmentItemId").exists(false)
                        ), // shipmentItemId 存在，但不在 joinedResults.shipmentItemId 中
                        new Criteria().andOperator(
                                Criteria.where("joinedResults.shipmentItemId").exists(true),
                                Criteria.where("quantityShipped").ne("$joinedResults.quantityShipped")
                        ) // quantityShipped 不等于 joinedResults 中的 quantityShipped
                )
        );

        Aggregation aggregation = Aggregation.newAggregation(
                matchStage,
                lookupStage,
                filterStage,
                Aggregation.limit(size)
        );

        AggregationResults<ReportFulfilledShipmentsMongoDTO> results = mongoTemplate.aggregate(aggregation, "data_report_amz_fulfilled_shipments", ReportFulfilledShipmentsMongoDTO.class);
        return results.getMappedResults();
    }



}