/*
 * Selling Partner API for Tokens
 * The Selling Partner API for Tokens provides a secure way to access a customer's PII (Personally Identifiable Information). You can call the Tokens API to get a Restricted Data Token (RDT) for one or more restricted resources that you specify. The RDT authorizes subsequent calls to restricted operations that correspond to the restricted resources that you specified.  For more information, see the [Tokens API Use Case Guide](doc:tokens-api-use-case-guide).
 *
 * OpenAPI spec version: 2021-03-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.erp.server.dmp.lingxing;

import cn.hutool.core.bean.BeanUtil;
import cn.hutool.json.JSONUtil;
import com.erp.server.dmp.ErpServerDmpApplication;
import com.sdk.third.lingxing.dto.*;
import com.sdk.third.lingxing.utils.LingxingApiUtils;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Profile;
import org.springframework.test.context.junit4.SpringRunner;

import java.time.LocalDate;
import java.util.*;

/**
 * API tests for Lingxing
 */
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerDmpApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@Profile("dev")
public class LingxingApiTest {

    @Test
    public void getShopList(){
//        Result<List<ShopInfoDTO>> result = LingxingApiUtils.getAndSign(LingxingApiUtils.SHOP_LIST_URI, new TreeMap<>());
////        System.out.println(JSONUtil.toJsonStr(result));
//        List<ShopInfoDTO> data = result.getData();
        List<ShopInfoDTO> data = LingxingApiUtils.getAllShopList();
        System.out.println("店铺列表");
        System.out.println(JSONUtil.toJsonStr(data));
    }

    @Test
    public void receivedInventory(){
        LocalDate startTime = LocalDate.of(2024,2,4);
        FbaReceiveReqDTO receivedDTO = new FbaReceiveReqDTO(125, startTime);
        Map<String, Object> objectMap = BeanUtil.beanToMap(receivedDTO);
        Result<Object> result = LingxingApiUtils.postAndSign(LingxingApiUtils.FBA_SHIPMENT_DETAIL_RUI, objectMap);
        System.out.println("FBA货件明细总结果");
        System.out.println(JSONUtil.toJsonStr(result));
        Object data = result.getData();
        System.out.println("FBA货件明细列表");
        System.out.println(JSONUtil.toJsonStr(data));
    }

    @Test
    public void allReceivedInventory(){
        Integer sid = 126;
        LocalDate receivedDate = LocalDate.of(2024,1,20);
        List<FbaShipmentReceiveDTO> data = LingxingApiUtils.getAllReceivedInventory(sid, receivedDate);
        System.out.println("FBA货件明细列表");
        System.out.println(JSONUtil.toJsonStr(data));
    }


    @Test
    public void warehouseList(){
        Map<String, Object> objectMap = new HashMap<>();
        Result<Object> result = LingxingApiUtils.postAndSign(LingxingApiUtils.WAREHOUSE_URI, objectMap);
        System.out.println("领星仓库总结果");
        System.out.println(JSONUtil.toJsonStr(result));
        Object data = result.getData();
        System.out.println("领星仓库数据结果");
        System.out.println(JSONUtil.toJsonStr(data));
    }

    @Test
    public void fastOutbound(){
        OrderFastOutboundPackageDTO.PackageInfo packageInfo = new OrderFastOutboundPackageDTO.PackageInfo();
        packageInfo.setGlobalOrderNo("103521548118516736");
        packageInfo.setLogisticsTypeId("4-9");
        packageInfo.setWaybillNo("SF7444493503348");
        packageInfo.setWid(Long.valueOf("96"));
        Result<Object> objectResult = LingxingApiUtils.fastOutbound(Collections.singletonList(packageInfo));
        System.out.println("结果列表");
        System.out.println(JSONUtil.toJsonStr(objectResult));
    }

    @Test
    public void cancelOrderByOrderList(){
        Result<Object> objectResult = LingxingApiUtils.cancelOrderByOrderList(Collections.singletonList("103522157705927168"));
        System.out.println("结果列表");
        System.out.println(JSONUtil.toJsonStr(objectResult));
    }


    @Test
    public void addOrUpdateProduct(){
        ProductInfo productInfo = new ProductInfo();
        productInfo.setSku("2667");
        productInfo.setSkuIdentifier("1619184295035801601");
        productInfo.setProductName("VIJIM P001 手机/平板夹支架 2222");
        Result<Object> objectResult = LingxingApiUtils.checkAddOrUpdateProduct(productInfo);
        System.out.println("商品同步结果");
        System.out.println(JSONUtil.toJsonStr(objectResult));
    }

    @Test
    public void addList(){
        Result<Object> result = LingxingApiUtils.getAndSign(LingxingApiUtils.PRODUCT_LIST_URI, new HashMap<>());
        Object data = result.getData();
        System.out.println("结果");
        System.out.println(data);
    }

    @Test
    public void skuIdentifierList(){
        TreeMap<String, Object> treeMap = new TreeMap<>();
        treeMap.put("sku_identifier_list", Collections.singletonList("1619184295035801601"));
        Result<Object> result = LingxingApiUtils.postAndSignCheckListConvert(LingxingApiUtils.PRODUCT_LIST_URI, treeMap);
        Object data = result.getData();
        System.out.println("结果");
        System.out.println(data);
    }

}