/*
 * Selling Partner API for Tokens
 * The Selling Partner API for Tokens provides a secure way to access a customer's PII (Personally Identifiable Information). You can call the Tokens API to get a Restricted Data Token (RDT) for one or more restricted resources that you specify. The RDT authorizes subsequent calls to restricted operations that correspond to the restricted resources that you specified.  For more information, see the [Tokens API Use Case Guide](doc:tokens-api-use-case-guide).
 *
 * OpenAPI spec version: 2021-03-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.erp.server.dmp.lingxing;

import cn.hutool.core.bean.BeanUtil;
import cn.hutool.core.date.DatePattern;
import cn.hutool.core.date.LocalDateTimeUtil;
import cn.hutool.json.JSONUtil;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.erp.server.dmp.ErpServerDmpApplication;
import com.erp.server.dmp.inout.dto.base.DmpInputTaskInitDTO;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.sdk.third.lingxing.dto.*;
import com.sdk.third.lingxing.utils.LingxingApiUtils;
import org.apache.commons.collections4.CollectionUtils;
import org.apache.commons.lang3.StringUtils;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Profile;
import org.springframework.test.context.junit4.SpringRunner;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.*;

/**
 * API tests for Lingxing
 */
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ErpServerDmpApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@Profile("dev")
public class LingxingApiTest {

    @Test
    public void getShopList(){
//        Result<List<ShopInfoDTO>> result = LingxingApiUtils.getAndSign(LingxingApiUtils.SHOP_LIST_URI, new TreeMap<>());
////        System.out.println(JSONUtil.toJsonStr(result));
//        List<ShopInfoDTO> data = result.getData();
        List<ShopInfoDTO> data = LingxingApiUtils.getAllShopList();
        System.out.println("店铺列表");
        System.out.println(JSONUtil.toJsonStr(data));
    }

    @Test
    public void receivedInventory(){
        LocalDate startTime = LocalDate.of(2024,2,4);
        FbaReceiveReqDTO receivedDTO = new FbaReceiveReqDTO(125, startTime);
        Map<String, Object> objectMap = BeanUtil.beanToMap(receivedDTO);
        Result<Object> result = LingxingApiUtils.postAndSign(LingxingApiUtils.FBA_SHIPMENT_DETAIL_RUI, objectMap);
        System.out.println("FBA货件明细总结果");
        System.out.println(JSONUtil.toJsonStr(result));
        Object data = result.getData();
        System.out.println("FBA货件明细列表");
        System.out.println(JSONUtil.toJsonStr(data));
    }

    @Test
    public void allReceivedInventory(){
        Integer sid = 126;
        LocalDate receivedDate = LocalDate.of(2024,1,20);
        List<FbaShipmentReceiveDTO> data = LingxingApiUtils.getAllReceivedInventory(sid, receivedDate);
        System.out.println("FBA货件明细列表");
        System.out.println(JSONUtil.toJsonStr(data));
    }


    @Test
    public void warehouseList(){
        Map<String, Object> objectMap = new HashMap<>();
        Result<Object> result = LingxingApiUtils.postAndSign(LingxingApiUtils.WAREHOUSE_URI, objectMap);
        System.out.println("领星仓库总结果");
        System.out.println(JSONUtil.toJsonStr(result));
        Object data = result.getData();
        System.out.println("领星仓库数据结果");
        System.out.println(JSONUtil.toJsonStr(data));
    }

    @Test
    public void fastOutbound(){
        OrderFastOutboundPackageDTO.PackageInfo packageInfo = new OrderFastOutboundPackageDTO.PackageInfo();
        packageInfo.setGlobalOrderNo("103521548118516736");
        packageInfo.setLogisticsTypeId("4-9");
        packageInfo.setWaybillNo("SF7444493503348");
        packageInfo.setWid(Long.valueOf("96"));
        Result<Object> objectResult = LingxingApiUtils.fastOutbound(Collections.singletonList(packageInfo));
        System.out.println("结果列表");
        System.out.println(JSONUtil.toJsonStr(objectResult));
    }

    @Test
    public void cancelOrderByOrderList(){
        Result<Object> objectResult = LingxingApiUtils.cancelOrderByOrderList(Collections.singletonList("103522157705927168"));
        System.out.println("结果列表");
        System.out.println(JSONUtil.toJsonStr(objectResult));
    }


    @Test
    public void addOrUpdateProduct(){
        ProductInfo productInfo = new ProductInfo();
        productInfo.setSku("2667");
        productInfo.setProductName("VIJIM P001 手机/平板夹支架 2222");
        Result<Object> objectResult = LingxingApiUtils.checkAddOrUpdateProduct(productInfo);
        System.out.println("商品同步结果");
        System.out.println(JSONUtil.toJsonStr(objectResult));
    }

    @Test
    public void addList(){
        Result<Object> result = LingxingApiUtils.getAndSign(LingxingApiUtils.PRODUCT_LIST_URI, new HashMap<>());
        Object data = result.getData();
        System.out.println("结果");
        System.out.println(data);
    }

    @Test
    public void skuIdentifierList(){
        TreeMap<String, Object> treeMap = new TreeMap<>();
        treeMap.put("sku_identifier_list", Collections.singletonList("1619184295035801601"));
        Result<Object> result = LingxingApiUtils.postAndSignCheckListConvert(LingxingApiUtils.PRODUCT_LIST_URI, treeMap);
        Object data = result.getData();
        System.out.println("结果");
        System.out.println(data);
    }

    @Test
    public void test(){
        List<String> storeIds = Arrays.asList("110537432579020800");
        String apiType = "basicOpen/multiplatform/temu/list";

        // 分页参数
        int length = 1000;
        TreeMap<String, Object> requestMap = new TreeMap<>();
        if (CollectionUtils.isNotEmpty(storeIds)){
            requestMap.put("store_ids", storeIds);
        }
        requestMap.put("length", length);

        Result<Object> result = LingxingApiUtils.postAndSignCheckListConvert(apiType, requestMap);
        Object data = result.getData();
        if (null == data){
            System.out.println("空");
        }


        JSONObject dataResultMap = JSON.parseObject(JSON.toJSONString(data));
        Object listObj = dataResultMap.get("list");
        Object countObj = dataResultMap.get("count");

        JSONArray resultList = JSONArray.parseArray(JSON.toJSONString(listObj));

        int total = Integer.parseInt(countObj.toString());
        if (length <= total){
            int totalPageSize = (total + length - 1) / length; // 计算总页数
            for (int i = 1; i < totalPageSize; i++) {
                // 从第二页开始请求
                requestMap.put("offset", i);
                // 当前请求
                Result<Object> curResult = LingxingApiUtils.postRequestDataAndRetry(apiType, requestMap);
                Object curData = curResult.getData();
                if (null == curData){
                    break;
                }
                JSONObject curDataResultMap = JSON.parseObject(JSON.toJSONString(data));
                Object curListObj = curDataResultMap.get("list");
                JSONArray curJsonArray = JSONArray.parseArray(JSON.toJSONString(curListObj));
                resultList.addAll(curJsonArray);
            }
        }
        System.out.println(JSON.toJSONString(resultList));
    }


    @Test
    public void testOrder(){

        // 请求参数
        TreeMap<String, Object> requestMap = new TreeMap<>();
        // 主表扩展参数
        String extendJson = "{\"platform_code\": [10003, 10015, 10024]}";
        if (StringUtils.isNotBlank(extendJson)){
            TreeMap<String, Object> mainTreeMap = JSON.parseObject(extendJson, TreeMap.class);
            requestMap.putAll(mainTreeMap);
        }

        // 明细扩展参数
        String detailExtendJson = "{\"length\": 200, \"date_type\": \"update_time\", \"order_status\": 4}";
        if (StringUtils.isNotBlank(detailExtendJson)){
            TreeMap<String, Object> detailTreeMap = JSON.parseObject(detailExtendJson, TreeMap.class);
            requestMap.putAll(detailTreeMap);
        }

        // 时间
        // start_time 开始时间，时间戳格式【单位：秒】，双开区间	是	[int]	1710925191
        long startEpochSecond = LocalDateTimeUtil.parse("2025-05-26 09:50:00.088", DatePattern.NORM_DATETIME_MS_PATTERN).atZone(ZoneId.systemDefault()).toInstant().getEpochSecond();
        requestMap.put("start_time", startEpochSecond);
        // end_time 结束时间，时间戳格式【单位：秒】，双开区间	是	[int]	1713430791
        long endEpochSecond = LocalDateTimeUtil.parse("2025-05-26 10:51:45.099", DatePattern.NORM_DATETIME_MS_PATTERN).atZone(ZoneId.systemDefault()).toInstant().getEpochSecond();
        requestMap.put("end_time", endEpochSecond);

        // 分页参数
        int page = 0;
        int pageSize = 500;
        requestMap.put("offset", page);
        requestMap.put("length", pageSize);
        System.out.println("请求报文");
        System.out.println(JSONUtil.toJsonStr(requestMap));
        // 首次请求
        Result<Object> result = LingxingApiUtils.postRequestDataAndRetry("pb/mp/order/v2/list", requestMap);
        System.out.println("响应报文");
        System.out.println(JSONUtil.toJsonStr(result));
    }

    @Test
    public void shipment(){
        TreeMap<String, Object> treeMap = new TreeMap<>();
        treeMap.put("sid", "140,141,142,186,168,220,221,222,223,224,225,226,227,228,229,231,232,233,213,216,217,218,219,215,144,187,188,210,134,119,120,121,122,123,138,156,171,200,201,189,190,191,192,193,194,195,196,126,108,135,214,151,157,158,159,160,161,162,163,173,202,207,205,153,117,175,176,208,125,174,230,204,118,101,107,133,172,206,109,143,185,209,102,103,104,105,106,137,164,170,198,199,112,113,114,115,116,139,155,177,178,197,179,180,149,110,111,211,212,154,166,181,203,124");
        //treeMap.put("sid","213");
        treeMap.put("start_date", "2026-01-01");
        treeMap.put("end_date", "2026-02-10");
        treeMap.put("shipment_id", "FBA15LBNC9Y9");
        Result<List<Object>> result = LingxingApiUtils.postAndSign(LingxingApiUtils.FBA_SHIPMENT_LIST_RUI, treeMap);
        Object data = result.getData();
        System.out.println("结果");
        System.out.println(data);
        // 文件路径
        String filePath = System.getProperty("user.home") + "/Desktop/awd.txt";
        ObjectMapper mapper = new ObjectMapper();
        try {
            mapper.writeValue(new File(filePath), data);
            System.out.println("对象已以JSON格式保存到桌面: " + filePath);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Test
    public void shipmentId() throws IOException {
        ObjectMapper mapper = new ObjectMapper();

        //读取桌面上的 awd.txt 文件
        String desktopPath = System.getProperty("user.home") + "/Desktop/awd.txt";
        String content = new String(Files.readAllBytes(Paths.get(desktopPath)));

        //解析 JSON
        JsonNode rootNode = mapper.readTree(content);

        //检查是否存在 "list" 数组
        if (rootNode.has("list") && rootNode.get("list").isArray()) {
            JsonNode listNode = rootNode.get("list");

            //遍历 "list" 数组
            for (JsonNode item : listNode) {
                //检查 is_sta=1
                if (item.has("is_sta") && item.get("is_sta").asInt() == 1) {
                    //输出 shipment_id
                    if (item.has("shipment_id")) {
                        System.out.println(item.get("shipment_id").asText());
                    }
                }
            }
        }
    }
}