package com.erp.server.tms.schedule;


import cn.hutool.core.bean.BeanUtil;
import cn.hutool.core.util.ObjectUtil;
import com.common.core.controller.BaseController;
import com.common.core.utils.MathUtil;
import com.erp.model.tms.dto.CfgSettingValueDTO;
import com.erp.model.tms.entity.CfgSettingEntity;
import com.erp.model.tms.enums.CfgSettingEnum;
import com.erp.model.wms.enums.ReconciliationTypeEnum;
import com.erp.server.tms.service.CfgSettingService;
import com.erp.server.tms.service.TmsB2cDeclareReconciliationDetailService;
import com.xxl.job.core.biz.model.ReturnT;
import com.xxl.job.core.context.XxlJobHelper;
import com.xxl.job.core.handler.annotation.XxlJob;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;
import java.time.LocalDate;
import java.time.temporal.TemporalAdjusters;

/**
 * @description: 报关对账单定时器
 * @author Will
 * @date: 2024/4/7 9:16
 */
@Component
@Slf4j
@EnableScheduling
public class TmsB2cDeclareReconciliationJob extends BaseController {

    @Resource
    private TmsB2cDeclareReconciliationDetailService tmsB2cDeclareReconciliationDetailService;

    @Resource
    private CfgSettingService cfgSettingService;

    /**
     * @description: 生成B2C报关对账单
     * @author Will
     * @date: 2024/4/7 9:16
     * @return ReturnT
     */
    @XxlJob("autoGenerate")
    public ReturnT<String> autoGenerate() {
        XxlJobHelper.log("====开始生成对账单=====");
        //查询系统配置
        CfgSettingEntity cfgSettingEntity = cfgSettingService.getByKey(CfgSettingEnum.RECONCILIATION_CYCLE.getCode());
        if (ObjectUtil.isEmpty(cfgSettingEntity) || ObjectUtil.isEmpty(cfgSettingEntity.getDataJson())) {
            XxlJobHelper.log("无生成对账单配置数据");
            return ReturnT.SUCCESS;
        }
        CfgSettingValueDTO.ReconciliationCycleDTO dto = BeanUtil.toBean(cfgSettingEntity.getDataJson(), CfgSettingValueDTO.ReconciliationCycleDTO.class);
        //自然月生成
        if (ReconciliationTypeEnum.CREAT_BY_MONTH.getCode().equals(dto.getDeclareReconciliationType())) {
            int dayOfMonth = LocalDate.now().getDayOfMonth();
            if (dayOfMonth != MathUtil.ONE.intValue()) {
                XxlJobHelper.log("自然月生成仅每月1号执行任务");
                return ReturnT.SUCCESS;
            }
            LocalDate startDate = LocalDate.now().minusMonths(1).with(TemporalAdjusters.firstDayOfMonth());
            LocalDate endDate = LocalDate.now().minusMonths(1).with(TemporalAdjusters.lastDayOfMonth());
            tmsB2cDeclareReconciliationDetailService.autoGenerateDeclareReconciliation(startDate,endDate);
        } else {
            int dayOfMonth = LocalDate.now().getDayOfMonth();
            if (dayOfMonth != dto.getDeclareReconciliationDate().intValue() ) {
                XxlJobHelper.log("未达到任务配置执行天【{}】，无需执行任务",dayOfMonth);
                return ReturnT.SUCCESS;
            }
            LocalDate endDate = LocalDate.now().minusDays(1);
            LocalDate startDate = LocalDate.now().minusMonths(1);
            tmsB2cDeclareReconciliationDetailService.autoGenerateDeclareReconciliation(startDate,endDate);
        }
        XxlJobHelper.log("====结束生成对账单====");
        return ReturnT.SUCCESS;
    }

}
